### ISSUE TITLE
Request: configurable volume up/down buttons

### ISSUE THREAD

**Issue by gerard33** [kalkih/mini-media-player#10]
When using the mini media player for my Sonos players the volume slider is not working very good when I am on my phone, because I usually only use volumes between 1-10 and that is very difficult to handle with the slider.

When using the volume up/down buttons, these use steps of 5 were I would prefer steps of 1.

Is it possible to make the steps in which the volume is changed configurable?

**Comment by kalkih** [comment]
That would indeed be a great configurable option.
Right now the vol up/down buttons trigger the [media player](https://www.home-assistant.io/components/media_player/) `volume_up` & `volume_down` service. I'm not sure if it accepts a `step` parameter but I'll look into it.

**Comment by gerard33** [comment]
I have checked and `volume_up` and `volume_down` don't accept steps.

This [post](https://community.home-assistant.io/t/media-player-volume-up-steps/17677/2?u=gerard33
) has a solution by using `volume_set`. Hopefully that can be used :grin:

![screenshot_2](https://user-images.githubusercontent.com/11230573/46177448-1a3dea80-c2b3-11e8-951d-561e1b2c93ec.jpg)

**Comment by kalkih** [comment]
Ok, the main reason behind adding optional volume buttons was from the beginning to add volume control for players without `volume_set` and/or `volume_level` support (see #3). I want to keep them to the `volume_up` / `volume_down` command, at least for now.

I know the volume slider can get really small in some configuration and that's an issue, I'll try to improve this.

**Comment by gerard33** [comment]
I saw that my TV uses other volume steps than my Sonos.
Checked the code and the volume step of the Sonos is [hardcoded](https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/media_player/sonos.py#L339) to 5.

So will make an issue to see if this can be configurable in the Sonos component, because a step of 5 is way to big in my opinion.

**Comment by kalkih** [comment]
Ok, that's interesting, I see now that it's handled very differently among the different media player components.

Yes, hopefully that could be added to the component, you could maybe try to create a PR with the changes to increase the chances of it happening?

**Comment by gerard33** [comment]
Discussed this on Discord with amelchio and the volume_step will be changed to 2 so it mimics the behaviour of the volume buttons on the Sonos.
With the `0.82` update the volume slider is also much more accurate for my needs by setting `max_volume` to 20.
