### ISSUE TITLE
Source select not visible when using Sonos Group

### ISSUE THREAD

**Issue by richardmayo** [kalkih/mini-media-player#104]
When using the Sonos Group function, the Source Select arrow seems to disappear

```
                - type: custom:mini-media-player
                  entity: media_player.sonos_office
                  info: scroll
                  artwork: cover
                  hide:
                    name: true
                    icon: true
                  sonos:
                    entities:
                      - entity_id: media_player.sonos_bedroom
                        name: Bedroom
                      - entity_id: media_player.sonos_lounge
                        name: Living
                      - entity_id: media_player.sonos_office
                        name: Office
                    sync_volume: true
```
![image](https://user-images.githubusercontent.com/17880620/55677050-21fedb80-5935-11e9-8245-25ebad3ba2c1.png)

**Comment by kalkih** [comment]
Please post the card config inside a [code block](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code-and-syntax-highlighting), would be great if you could post a screenshot too.
Thanks.

**Comment by richardmayo** [comment]
> Please post the card config inside a [code block](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code-and-syntax-highlighting), would be great if you could post a screenshot too.
> Thanks.

updated

**Comment by kalkih** [comment]
Hmm, I'm not able to reproduce this, are you sure the Sonos entity actually has sources exposed? The source button/icon will not be rendered if there are zero sources or if the `source_list` attribute doesn't exist at all.

![hyperion_8123_lovelace_4 (1)](https://user-images.githubusercontent.com/457678/55677163-2ef2df00-58e3-11e9-881b-ab48748d04f4.png)

Please check if the Sonos entity has an attribute called `source_list` and if it includes any sources. You can easily do this by navigating to `/dev-state` in HA.

**Comment by kalkih** [comment]
@richardmayo Did you have time to check the attributes?

**Comment by richardmayo** [comment]
Hi

This is a snapshot of the entity
[image: image.png]

**Comment by kalkih** [comment]
Okay, that's it, the source list is empty.
There are no sources to display so the source select is hidden.

**Comment by richardmayo** [comment]
Problem was related to this. Issue is now resolved

https://github.com/home-assistant/home-assistant/issues/22714
