### ISSUE TITLE
Question & Help Please

### ISSUE THREAD

**Issue by twistp** [kalkih/mini-media-player#105]
Hi

Cool project. Congrats. Any chance you can share your ui-lovelace file as an example or post an example file? I am new to this and I am struggling with documentation. I am also getting an error "specify an entity from within the media_player domain". This is all I have in "ui-loveloca.yaml"

resources:
  - url: /local/mini-media-player-bundle.js?v=1.0.3
    type: module
title: Our Home
views:
  - icon: mdi:home-assistant
    id: home
    # Name of the view. Will be used as the tooltip for tab icon
    title: Home
    # theme: darkorange
    cards:
      - entiy: media_player.home_theatre
        type: custom:mini-media-player 
  
media_player.home_theatre is an object accessible from the default view.

Thanks for the help and for putting this together

Best
p

**Comment by Norien** [comment]
Feel free to hop over to my repo, I'm using this custom card a couple different ways!

**Comment by kalkih** [comment]
Hey, check out @Norien's repo and see if that is of help.

I think you have a typo in your card configuration, hence the error.

> cards:
> * entiy: media_player.home_theatre
>   type: custom:mini-media-player

entiy should be entity.

Please let me know if that resolved it or if you have any further questions.

**Comment by twistp** [comment]
> Hey, check out @Norien's repo and see if that is of help.
> 
> I think you have a typo in your card configuration, hence the error.
> 
> > cards:
> > 
> > * entiy: media_player.home_theatre
> >   type: custom:mini-media-player
> 
> entiy should be entity.
> 
> Please let me know if that resolved it or if you have any further questions.

SUPER THANKS :) It was indeed a typo ... it works like charm :)
Thanks again

**Comment by twistp** [comment]
Thanks a lot @Norien

> Feel free to hop over to my repo, I'm using this custom card a couple different ways!

Thanks a lot @Norien. Will take a look now ;)

**Comment by kalkih** [comment]
Awesome! Closing this issue, feel free to reopen it or open another one if you have any other issues or questions.
