### ISSUE TITLE
Volume slider and  volume up & down buttons, - both

### ISSUE THREAD

**Issue by Tom-ahawk** [kalkih/mini-media-player#107]
It would be nice to have the option to both have the volume slider and the up & down buttons.
Not only to swap out the volume slider for volume up & down buttons.

The up & down buttons for minute adjustment.

Cheers!

**Comment by kalkih** [comment]
Hey,
I don't think this will get added sorry, there's simply not enough horizontal space in the control row to show both volume buttons and the slider.

I would suggest using [lovelace-popup-card](https://github.com/thomasloven/lovelace-popup-card) to possibly show volume buttons when pressing the card.

**Comment by Tom-ahawk** [comment]
I see your point, it’s a reason for its called mini-media-player : )
Just one last idea, why not make the source drop-down-list be inter changeable with volume -/+?

![image](https://user-images.githubusercontent.com/35527507/56355255-2bf6c900-61d6-11e9-8c41-3ea8a47b03e0.png)

**Comment by kalkih** [comment]
Yes, that's a viable solution, I think they would have to be even smaller though, in order to not interfere with the card padding.
Drawback: could be difficult to hit the small buttons on touch screens.

But yes, could maybe add that in the future, thanks.

**Comment by Tom-ahawk** [comment]
👍😊
