### ISSUE TITLE
idle artwork

### ISSUE THREAD

**Issue by richardmayo** [kalkih/mini-media-player#108]
Hi

Is it possible to have an idle artwork picture when nothing in playing?

Thanks

**Comment by kalkih** [comment]
Hello,
Yes this is possible through the `background` [option](https://github.com/kalkih/mini-media-player#options).

**Comment by jer78** [comment]
Further to this...when using sonos and the TV source is active no artwork will be displayed since there is none. Is it possible to use the background for this state as well?

**Comment by kalkih** [comment]
@jer78 Yes, but only when you have `artwork: cover` or `artwork: full-cover`.
When artwork is present it will temporarily render above the set background.

**Comment by richardmayo** [comment]
It does not seem to render the whole artwork.

im using a test image that is 1000 x 1000 (so a square) but its not rendering like that. i have tried `artwork: full-cover` & `artwork: full-cover-fit` but neither work

![image](https://user-images.githubusercontent.com/17880620/56553273-060c6280-65e2-11e9-92ef-3e3d6569589d.png)

**Comment by kalkih** [comment]
That's right, that's the intended behavior. The background has no effect on the card size, it's simply applied as the card background through CSS.

Artwork setting is not applied to the background, only to media artwork coming from the entity.
