### ISSUE TITLE
Request: When paused, grey out media info text and remove volume sliders/buttons

### ISSUE THREAD

**Issue by gerard33** [kalkih/mini-media-player#11]
When a Sonos is stopped the state is `paused`.

This [change](https://github.com/torbjorn2000/mini-media-player/commit/2582a5ef06a41d1830b7d2a53e71c9e3e48b2b7b) by @torbjorn2000 sets a different color to the media info text and removes the volume sliders/buttons.

Forum [post](https://community.home-assistant.io/t/lovelace-mini-media-player/68459/43?u=gerard33).

Would you mind implementing this? I think it's a nice addition to keep the card cleaner when Sonos is paused (which is kind of the off status).

**Comment by kalkih** [comment]
That's cool, but since this is a universal media player card, some features that are very specific might not be suitable.

Could possibly add as an optional feature in the feature if there is more demand.

**Comment by gerard33** [comment]
You're right, this needs to be a configurable item as it is a specific thing for in this case the Sonos.

Would be great if this can be implemented as a optional feature.

**Comment by kalkih** [comment]
This is now possible through the `consider_idle_after` option added in [v0.8.9](https://github.com/kalkih/mini-media-player/releases/tag/v0.8.9)

- Added: `consider_idle_after` option, to display player as idle after x amount of time

  <img src="https://user-images.githubusercontent.com/457678/47925288-1c045a80-debe-11e8-8178-1bab32c9773e.gif" width="500" alt="v0.8.9 example 2" />

It's not exactly what you requested but after other requests and discussion regarding [this kind of functionality](https://community.home-assistant.io/t/lovelace-mini-media-player/68459/200?u=kalkih), this is what we ended up with.

**Comment by gerard33** [comment]
Thanks!
