### ISSUE TITLE
Feature request: Card with media shortcuts, collapsible panel.

### ISSUE THREAD

**Issue by Tom-ahawk** [kalkih/mini-media-player#111]
Considering one can make a lot of buttons to control several features on a media player. Grouping buttons into panels which could be collapsible would make the GUI more user friendly, save space when buttons are not in use.

Be able to specify number of buttons in a row,  would be welcomed .

![image](https://user-images.githubusercontent.com/35527507/56862910-41c37580-69b0-11e9-9301-796e2c678cdc.png)

**Comment by kalkih** [comment]
There's the `list` option in the [shortcuts object](https://github.com/kalkih/mini-media-player#shortcuts-object) already that basically does exactly this and, can be useful if you want to save vertical space. You can even use both a list & buttons in the same card.

![hyperion_8123_lovelace_4](https://user-images.githubusercontent.com/457678/56865910-ab08b000-69d3-11e9-9056-5c269c2fa1cd.png)

**Comment by Tom-ahawk** [comment]
Aha, - I can see list can be used. And a "hide_when_off" object. That’s a nice thing. 

Looking at the "Shortcut item object->id", is it possible to use a service with an argument. Does not look like it, looking at the type- and id-values ? (That would be a nice thing to be able to)

I am not able (have tried) to specify different rows with different columns (with different number of buttons), if I understand correctly?

        shortcuts:
          columns: 4
             buttons:           
        columns: 2
            buttons:

**Comment by kalkih** [comment]
> Looking at the "Shortcut item object->id", is it possible to use a service with an argument. Does not look like it, looking at the type- and id-values ? (That would be a nice thing to be able to)

I really want to keep the shortcut functionality really simple for this card, think of it as a small extra feature.

I feel like Lovelace is already so highly customizable and there are a ton of core/custom cards out there, so extending the button functionality further in this card is like reinventing the wheel.

> I am not able (have tried) to specify different rows with different columns (with different number of buttons), if I understand correctly?

The config is invalid, the `shortcuts` object only accepts a single `list` and/or `buttons` object.
The `columns` option is basically maximum buttons allowed per row and applies to all button shortcuts, so you can't specify it at a row basis.

```yaml
shortcuts:
  columns: 4
  buttons:
    ...
  list:
    ...
```

For more advanced button functionality/layouts I would highly recommend checking out the [button-card](https://github.com/custom-cards/button-card) and arrange the button layout with horizontal & vertical-stacks.
You could then wrap everything (including the mini-media-player) inside a [vertical-stack-in-card](https://github.com/custom-cards/vertical-stack-in-card) to achieve the "single card" look.

**Comment by Tom-ahawk** [comment]
I totally see your point. I appreciate your patient.
