### ISSUE TITLE
long-press shortcuts

### ISSUE THREAD

**Issue by iantrich** [kalkih/mini-media-player#113]
I don't necessarily think you need it, but I did just add long-press support over on my radial-menu card and thought you might be able to take advantage.
https://github.com/custom-cards/radial-menu/commit/078cd6b8d91b5f59ecf1443572ef073d76558900

**Comment by kalkih** [comment]
That's very neat!

Trying to keep the button functionality fairly simple for this card (since I believe there are better alternatives for buttons out there), so might hold off on this one, at least for now.

Thanks for letting me know though Ian, appreciate it!

**Comment by iantrich** [comment]
Fair. FYI I’m in the process of extracting a lot of core functionality into a npm module. Long press is in there plus a lot more and more to come so we don’t have to all replicate work. https://github.com/custom-cards/custom-card-helpers
