### ISSUE TITLE
Volume spacing not right

### ISSUE THREAD

**Issue by damusmf** [kalkih/mini-media-player#114]
Updated everything to latest, v1.1.0 and running home assistant 0.92.1

When using volume_stateless:true it appears the spacing of the volume buttons got all messed up somewhere along the line.  They used to be all neat on the left side but now they are spread out. 

![Annotation 2019-05-05 133532](https://user-images.githubusercontent.com/31552122/57198639-afd0e500-6f3a-11e9-8eeb-8d18a8b471f5.jpg)

Update:  Downgraded back to v.1.0.4 and the volume buttons are back where they should be
![Annotation2](https://user-images.githubusercontent.com/31552122/57198698-6df46e80-6f3b-11e9-9195-8c6c194d1d41.jpg)

**Comment by kalkih** [comment]
Should be fixed in the latest release, let me know if you have any more issues.
Thanks!
