### ISSUE TITLE
local background image is not loading

### ISSUE THREAD

**Issue by dnguyen800** [kalkih/mini-media-player#115]
Hi,

I updated from version 1.04 (I think) to 1.11 and saw that the background images I used before are no longer showing. This is the image used in the 'background:' config option. To be specific, upon browser refresh, I would see the background image for a split second, and then it would disappear back to plain white background.

This issue is present on all browsers I tested. Google Chrome on Windows 10, Google Chrome on Amazon Fire tablet, Home Assistant iOS app on iPad.

Before, the card would look something like this:

![image](https://user-images.githubusercontent.com/25126347/57264724-71195880-7028-11e9-9b85-faea0f90da3d.png)

Now, it looks like this:

![image](https://user-images.githubusercontent.com/25126347/57264733-7ecede00-7028-11e9-9375-f7e5fb5b08ad.png)

I tried creating a basic mini-media-player card with the settings below but still run into the issue. I have also tried clearing browser cache with no luck.

```
          - type: custom:mini-media-player
            entity: media_player.tv
            background: "/local/images/tv.png"  
```

I am running Home Assistant v0.92.2, using Hass.io.

**Comment by kalkih** [comment]
Thanks for reporting.
Fixed, should work as expected in the next release, sorry for the inconvenience.

**Comment by dnguyen800** [comment]
Awesome, thanks for the quick turnaround!

**Comment by kalkih** [comment]
Should be fixed in the latest release, thanks!
