### ISSUE TITLE
Upgrade to the released lit-element package

### ISSUE THREAD

**Issue by justinfagnani** [kalkih/mini-media-player#117]
The `@polymer/lit-element` npm package has been moved to `lit-element`. `@polymer/lit-element` is deprecated and not receiving any updates, so please upgrade to `lit-element@^2.0.0` as soon as possible.

Thanks!

**Comment by kalkih** [comment]
Hey, Is this a bot? I've already switched over a long time ago.
https://github.com/kalkih/mini-media-player/blob/6dd097b581f35cc85ee1632ff98f5befdc5336c7/package.json#L20

**Comment by justinfagnani** [comment]
Sorry, not a bot, I just clicked through a bunch of dependants of `@polymer/lit-element` on npm. Do you need to publish to npm?

**Comment by kalkih** [comment]
Oh dang, you are absolutely right! Almost forgot I published this to npm.
Will publish the latest release to npm, thanks for the reminder!
