### ISSUE TITLE
[Feature Request] Set artwork overlay opacity (and maybe color)

### ISSUE THREAD

**Issue by noxhirsch** [kalkih/mini-media-player#118]
By default the artwork has a black translucent overlay (or the image has a lower opacity in front of a  black background). I'd like to decrease the visibility of the artwork to increase the readability of the text/buttons.
It would be cool if there's a setting for that. 
Additionally maybe some people would like to change that overlay to white to fit it in a bright HomeAssistant template.

By the way: Thank you for your hard work on this amazing player card 👍

**Comment by kalkih** [comment]
Absolutely, the visibility can get pretty bad, especially with certain artwork colors/patterns. Tried to take kind of a middle ground approach with a bit of darkening of the artwork paired with white buttons/text/icons.

I think this would be a perfect use case for [theme variables](/https://github.com/kalkih/mini-media-player#theme-variables), I could potentially add one for the overlay and another one for the text/icon/text color when artwork cover is used and there is artwork present.
What do you think?

This would apply to `cover`, `full-cover` & `full-cover-fit` artwork options.

**Comment by noxhirsch** [comment]
Great idea! I think this is the best solution 👍

**Comment by kalkih** [comment]
Example of the variables in action:

```yaml
# theme...
mini-media-player-overlay-color: rgba(255, 255, 255, 0.75)
mini-media-player-overlay-base-color: #000
```
![hyperion_8123_lovelace_4 copy 3](https://user-images.githubusercontent.com/457678/57532093-48040b00-733b-11e9-8e40-f581fe47ea89.png)

**Comment by iantrich** [comment]
Very nice!

**Comment by noxhirsch** [comment]
I love it!

**Comment by kalkih** [comment]
Now available in the latest release, would love to see screenshots if you end up using it!

**Comment by noxhirsch** [comment]
Of course I'm using it! :) Here are two screenshots - even if it is very unspectacular in my case, because I only use my blueish tinted background-color as overlay. I think there will be much more creative mini-media-player in the wild, soon ;)
![player1](https://user-images.githubusercontent.com/30938717/57949652-4b703700-78e5-11e9-8afc-9f6917ffdceb.JPG)
![player2](https://user-images.githubusercontent.com/30938717/57949651-4ad7a080-78e5-11e9-8889-4f8349b406fa.JPG)
By the way: I noticed, that the runtime seems to be a little bit of.

**Comment by kalkih** [comment]
Looks great, the runtime misplacement has been fixed https://github.com/kalkih/mini-media-player/issues/119.

I played around with the theme variables a bit more and noticed it would be great to be able to change the accent color when artwork is present as well, so I've now added `mini-media-player-overlay-accent-color`, which will be available in the next release.
