### ISSUE TITLE
Sometimes the hass object is undefined

### ISSUE THREAD

**Issue by RomRider** [kalkih/mini-media-player#120]
Hey,

Sometimes on load, the `hass` object is undefined (in my setup this card is inside a conditional card), I don't know why but this pops a javascript error here:
https://github.com/kalkih/mini-media-player/blob/master/src/main.js#L70

You might want to test if `hass` exists before accessing the state array.

**Comment by kalkih** [comment]
Oooh okay, never seen that actually, thanks for letting me know, will add a guard 👍
