### ISSUE TITLE
Service as an shortcut item option type?

### ISSUE THREAD

**Issue by Tom-ahawk** [kalkih/mini-media-player#121]
I have been trying to find out if your card can use services (with service data) for a shortcut button.
Is it possible, if not, any change it will be implemented?

![image](https://user-images.githubusercontent.com/35527507/57969379-9b4b0e80-7976-11e9-96b0-d170a5e2083f.png)

Here is my code for a custom button card:
"           ....
            tap_action:
              action: service
              service: media_player.rotel_send_command
              service_data:
                command_name: TREBLE_UP
                entity_id: media_player.rotel_rsp_1570
            type: 'custom:button-card'
"

**Comment by kalkih** [comment]
No, service is not accepted as type.
As for data:
> <sup>1</sup> Only compatible with script shortcuts, useful for sending variables to script.

I don't think support for service will be added, sorry, I want to keep the shortcut functionality really simple, I recommend using the custom button card for more advanced uses, could always wrap it together with the media player inside a vertical-stack-in-card.
You could also create a script which calls desired service by either provided variables or hard coded.

**Comment by kalkih** [comment]
But never say never, could potentially be added, I guess it wouldn't require much extra code and should be pretty simple to implement if we reuse the `id` option as `[domain].[service]`.

If anyone else is interested in this, A PR would be much appreciated.

**Comment by Tom-ahawk** [comment]
"Pull requests let you tell others about changes you've pushed to a branch in a repository on GitHub."

I dont have the know-how to make changes to your card code unforttunatly :  (
But please have this in mind for future functionality : D

**Comment by kalkih** [comment]
Now possible with the latest release

**Comment by exetico** [comment]
I would just like to say thank you for this, and other awesome options in this solution :-D That's all!
