### ISSUE TITLE
update cards to use HACS

### ISSUE THREAD

**Issue by vMeph** [kalkih/mini-media-player#124]
would it be possible to update cards to be used with HACS
https://custom-components.github.io/hacs/

**Comment by kalkih** [comment]
Maybe, not sure. You could try by following [these instructions](https://custom-components.github.io/hacs/#add-custom-repos).

**Comment by vMeph** [comment]
its seems you might need to add something 
``Could not add repo 'https://github.com/kalkih/mini-media-player' at this time, if the repo meet all requirements try again later.``

**Comment by iantrich** [comment]
I believe that is just a bug. @kalkih does releases and that should be supported asaik

**Comment by vMeph** [comment]
on logger os HACS getting
``Expected file mini-media-player.js not found in ['rollup.config.js' - for kalkih/mini-media-player``
not sure if that helps

**Comment by kalkih** [comment]
From reading the requirements I'm not really sure if it's supposed to work or not.

Not sure if it actually grabs the code from release assets though? if it does it should work.
> * The repository uses GitHub releases (Optional)
>   * If there is releases:
>     * When installing/upgrading it will scan the content in the latest release.

But... If these two points has to be met, I'm afraid my cards won't be supported.
> * There are .js files under ROOT_OF_THE_REPO/dist/ or directly in the root of the repository.
> * One of the .js files have the same name as the repository.


> Expected file mini-media-player.js not found in ['rollup.config.js' - for kalkih/mini-media-player

Umm.. That error make no sense to me, is it looking for the source inside another file?

**Comment by iantrich** [comment]
@ludeeus care to clear this up when you get a chance? Thanks.

**Comment by ludeeus** [comment]
Sure thing :)

Like @kalkih suspect his cards cannot be supported at this point, I will at a later stage investigate the option to use release artifacts as an additional source.

`rollup.config.js` is from the root of the repo, so that message is fully expected :)

**Comment by ludeeus** [comment]
When version `0.3.0` of HACS releases it will have support for release assets
![mediaplayerdemo](https://user-images.githubusercontent.com/15093472/58286398-f0d84e80-7dae-11e9-8bf4-ddd4c104fdcb.gif)

**Comment by kalkih** [comment]
You're great @ludeeus, really useful and cool project!

**Comment by kalkih** [comment]
@vMeph Have you tried adding the card with the updated HACS yet?

**Comment by ludeeus** [comment]
@kalkih with this, <https://custom-components.github.io/hacs/#include-default-repositories> it would no longer be an issue :)

**Comment by ludeeus** [comment]
Since a version that ships with this as default is now published, I think you can close this one :)
