### ISSUE TITLE
Sonos join/unjoin service names changed in 0.93

### ISSUE THREAD

**Issue by nununo** [kalkih/mini-media-player#125]
Hello,

When I now try to join/unjoin Sonos devices using `mini-media-player` I get the following error message:

> Failed to call service media_player/sonos_JOIN. Service not found

The Sonos specific services recently changed (in version 0.93 I believe) as can be seen in this page:
https://www.home-assistant.io/components/sonos/

So, probably the code must be updated to align with these HA changes.

Thanks,
Nuno

**Comment by kalkih** [comment]
Hey, I've already switched over to the new service calls https://github.com/kalkih/mini-media-player/commit/9dacdb66a159f91da773c6e2c735bc77d3fb0dca in the latest release 
[v1.1.3](https://github.com/kalkih/mini-media-player/releases/tag/v1.1.3)

Try clearing your cache if you have issues loading the latest version of the card.

**Comment by nununo** [comment]
Oh! Sorry for wasting your time. I will. Thanks!
