### ISSUE TITLE
No card type found

### ISSUE THREAD

**Issue by aweb-01** [kalkih/mini-media-player#126]
For some reason I can't get this to work at all, I get "No card type found" error when I try to add this to my lovelace. Any suggestions?

**Comment by kalkih** [comment]
Hey, hard to tell without access to your config, but check this issue kalkih/mini-graph-card#100
You might have to add/remove the dash before `type`, depending on the placement in the config.

**Comment by aweb-01** [comment]
Thanks, changing the dash fixed it... simple mistake, thanks again :-)

**Comment by bobneubaum-personal** [comment]
Having this issue too, I installed this with HACs so I assumed it would just work, it doesn't.  I added the resource reference then in configuration.yaml and it says the integration is not installed.  I'm sure i'm missing something, just don't know what.

**Comment by bobneubaum-personal** [comment]
> Having this issue too, I installed this with HACs so I assumed it would just work, it doesn't. I added the resource reference then in configuration.yaml and it says the integration is not installed. I'm sure i'm missing something, just don't know what.

Fixed it... I was adding the " - " thats in the instructions... Thats not needed.
