### ISSUE TITLE
Add extra attribute for information on what is playing

### ISSUE THREAD

**Issue by gerard33** [kalkih/mini-media-player#13]
I have a Sony TV which uses `media_series_title` to show the information on the channel which is playing.
That attribute is part of the custom component I have made, but there are more `media_players` which use this attribute -> https://github.com/home-assistant/home-assistant/search?q=media_series_title&unscoped_q=media_series_title

I now have simply added
`<span class='mediaartist'>${this._getAttribute(entity, 'media_series_title')}</span>`
after
`<span class='mediaartist'>${this._getAttribute(entity, 'media_artist')}</span>` in your code.

But without doubt there is a more elegant way to show `media_series_title` in case `media_artist` is not available.

**Comment by kalkih** [comment]
Added with [v0.8.3](https://github.com/kalkih/mini-media-player/releases/tag/v0.8.3), let me know how it works.

**Comment by gerard33** [comment]
Thanks! Works great :grinning:
