### ISSUE TITLE
WebOS TV use TTS notify services 

### ISSUE THREAD

**Issue by michelebossa** [kalkih/mini-media-player#136]
Hi,
I d'like to use the TTS services with webos TV mediaplayer, the standard component expose a notify services. it is possible to add another type of platform "webos" ? inside we can use the entity_id to call it.

Usually i call my notify services with:
      service: notify.livingroom_tv
      data:
        message: "Test Message"

maybe something like this: 
    else if (config.platform === 'webos')
      this.hass.callService('notify', opts.entity_id, { message });

Thanks.

**Comment by kalkih** [comment]
Sure!

**Comment by kalkih** [comment]
This is now available in the latest release.
Platform `webos`, The card entity has to match the notify service name e.g. `media_player.livingroom_tv` & `notify.livingroom_tv`, if they don't match you can manually specify the notify service name through the `entity_id` option in the tts option object.

**Comment by michelebossa** [comment]
Work great!! Thanks a lot
