### ISSUE TITLE
Strange error

### ISSUE THREAD

**Issue by folrewef** [kalkih/mini-media-player#14]
Hi,

I get the following error:

018-10-05 12:44:11 ERROR (MainThread) [frontend.js.latest.201809270] https://redacted.duckdns.org:8123/local/custom_ui/mini-media-player.js?v=0.8.3:680:22 NotSupportedError: Cannot define multiple custom elements with the same tag name

I also updated to 0.8.3 and have tried to use the options:
hide_volume (Sonos and Apple TV) and show_progress (Sonos) without effect.

Any help is much appreciated.

**Comment by kalkih** [comment]
Seems like the old version of the code is still loaded from cache, hence why it says `Cannot define multiple custom elements with the same tag name`.
What browser(s) are you getting this issue on?
Try to restart Home Assistant and/or clear your browser(s) cache.

**Comment by folrewef** [comment]
Emptying the cache solved it (Safari).

Thank you

**Comment by kalkih** [comment]
Awesome, thanks!
