### ISSUE TITLE
Overriding source list, volume slider and icon

### ISSUE THREAD

**Issue by IDmedia** [kalkih/mini-media-player#141]
I have a few questions:

1. I'm using an HDMI Matrix instead of my TVs Source-list. Is there a way to override the Source list to replace it with my own list of items (scripts)?

2. I'm able to change the icon, but when I do it stays the same regardless of status (on/off). Any way to specify two images?

3. I'm not using my TVs volume, but external speakers. Is there a way to change how the volume-slider is working or will I have to disable it and add my own?

**Comment by kalkih** [comment]
Hey, 

1. Check out the [shortcuts option](https://github.com/kalkih/mini-media-player#shortcuts-object), You could hide the source and use a shortcut list instead, where you call desired scripts.

2. No not possible, you can however unhide `power_state` and that way the power icon will change with on/off state (accent color) when on.
```yaml
hide:
  power_state: false
```

3. I suggest checking out the [universal media player component](https://www.home-assistant.io/components/universal/), should be able to solve **#3** at least.

**Comment by IDmedia** [comment]
Thanks :)
