### ISSUE TITLE
Additional padding for Sonos buttons

### ISSUE THREAD

**Issue by darkkatarsis** [kalkih/mini-media-player#143]
I noticed that when in settings we have a **group** set to false and **speaker_group** is enabled then progress bar is too close button container

<img width="489" alt="Screenshot 2019-07-09 at 00 28 55" src="https://user-images.githubusercontent.com/24244919/60846781-d2080d00-a1e0-11e9-9e11-6b828489cae7.png">

**Comment by kalkih** [comment]
@darkkatarsis Did you mean when you set `group: true`?
I could only reproduce when `group` was set to `true`.

**Comment by darkkatarsis** [comment]
Yes, sorry for the typo

**Comment by kalkih** [comment]
Okay, pushed a fix to dev, will be fixed with the next release 👍🏼

**Comment by kalkih** [comment]
Hey, this is now fixed with the latest release [v1.3.0](https://github.com/kalkih/mini-media-player/releases/tag/v1.3.0).
Thanks for the report!
