### ISSUE TITLE
In HACS the type is incorrect. Should be 'js' instead of 'module'

### ISSUE THREAD

**Issue by njwh1976** [kalkih/mini-media-player#145]
Great card, I've just changed from custom updater to HACS and the card wouldn't load. Found out that in the instructions in the store the type to put in the Lovelace config is stated as 'module', this should be 'js'. After changing it works great again!

**Comment by kalkih** [comment]
Hey, that shouldn't really matter unless you're on a really old browser (issue listed under the [error section](https://github.com/kalkih/mini-graph-card#getting-errors)).
What browser/device are you running?
