### ISSUE TITLE
Using images for shortcut buttons?

### ISSUE THREAD

**Issue by mkono87** [kalkih/mini-media-player#146]
Do you think it could be possible to be able to use jpg/png images instead of mdi icons? Even if they had to be the same size as an icon I think it would be nice to be able to use them for radio station shortcuts and using their logo.

**Comment by kalkih** [comment]
Hey, could probably make this possible in the future.
Would require the images to be hosted locally in the `/www` folder (similar to how you do with picture-elements or other lovelace cards) or somewhere else on the web with an absolute url.

**Comment by mkono87** [comment]
> Hey, could probably make this possible in the future.
> Would require the images to be hosted locally in the `/www` folder (similar to how you do with picture-elements or other lovelace cards) or somewhere else on the web with an absolute url.

Yeah I used local images with the button-card but I think it would look much better with this card for sure.

**Comment by kalkih** [comment]
Now available in the latest release, see the [shortcut](https://github.com/kalkih/mini-media-player#shortcut-item-object) `image` option.
