### ISSUE TITLE
Feature request: hide icon and name.

### ISSUE THREAD

**Issue by bramkragten** [kalkih/mini-media-player#15]
Hi, 

for my receiver I would like to hide the icon and name to make more place for the volume slider:

![image](https://user-images.githubusercontent.com/5662298/46736241-d4acf480-cc98-11e8-9332-e27bd931e306.png)

The mute button could then take the place of the icon... Would this be something you would be willing to add to the card?

Thanks!

**Comment by bramkragten** [comment]
Cool thanks!

**Comment by kalkih** [comment]
Added in [v0.8.4](https://github.com/kalkih/mini-media-player/releases/tag/v0.8.4)

**Comment by bramkragten** [comment]
Thats quick! Thanks!
