### ISSUE TITLE
Feature request: Configurable icon for speaker group

### ISSUE THREAD

**Issue by ronschaeffer** [kalkih/mini-media-player#150]
Once again, thanks for the fantastic card.

This is a feature request to make the speaker group icon configurable. A possible setting format is at the end of this snippet:

```
      speaker_group:
        entities:
          - entity_id: media_player.dining_room_2
            name: Dining Room
          - entity_id: media_player.kitchen
            name: Kitchen
            volume_offset: 15
        platform: sonos
        sync_volume: true
        icon: mdi:google-circles-communities

**Comment by kalkih** [comment]
Great suggestion, will be available in the next release and will function like your example!

**Comment by ronschaeffer** [comment]
Perfect. Thanks. Let me know if you need a tester.

**Comment by kalkih** [comment]
Hey, this is now possible with the latest release [v1.3.0](https://github.com/kalkih/mini-media-player/releases/tag/v1.3.0).
There's a new option `icon` for the `speaker_group` option object.
