### ISSUE TITLE
Getting blanc card

### ISSUE THREAD

**Issue by stefancvetkovic** [kalkih/mini-media-player#153]
I iunstalled from HACS mini-media-player, and I added manually mini-media-player-bundle into my www folder and then both files such as custom_component and add-on added to lovelace-ui.
and then when I put just ```

- type: custom:mini-media-player
   entity: media_player.chromecast_monoprice
````

it shows me a blanc screen?
do I need to setup a notify: into my config file?

**Comment by kalkih** [comment]
Hey, you won't need to setup any notify service, unless you want to use the tts feature.

If you installed it using HACS, there's no need to download anything manually, just make sure you paste the resource reference for the card/plugin (you'll get the correct one from HACS) in your `ui-lovelace.yaml` or in the raw config editor GUI (depending on if you are using lovelace in storage mode or not)

**Comment by stefancvetkovic** [comment]
Thanks. I everything tried, manually install as well as via HACS.
Now my configuration is via HACS, added to my lovelace resources 
Do I need this section in my config:
```notify:
  - name: ga_broadcast
    platform: rest
    resource: http://[xxx.x.x.xxx]:5000/broadcast_message```
I am trying to connect my media_player.chromecast which is working by itself.

**Comment by kalkih** [comment]
No, that's not trivial for the card to work, that's just if you use the tts feature of the card and want to use google assistant to broadcast the tts message.

What does you resource section look like in your config?

**Comment by kalkih** [comment]
Closing this, feel free to reopen if you still need help.
