### ISSUE TITLE
Volume Slider Snaps Back

### ISSUE THREAD

**Issue by apop880** [kalkih/mini-media-player#154]
When holding and dragging the volume slider, it tends to snap partway back after I let go rather than stopping at the final destination.

**Comment by kalkih** [comment]
Hello,
Yes, this can happen when used with certain media player platforms that doesn't update their reported volume fast enough.
The volume slider is based on the value set by the backend (component), so when we the slider is changed and the backend still reports the old volume, it can snap back for a moment until the backend sends the new updated volume.

What's the device you are seeing this behaviour on?

**Comment by apop880** [comment]
I'm seeing it on an Onkyo AVR that has Chromecast built-in (so using its Chromecast media_player entity and not the Onkyo component entity). It doesn't appear to be an issue on other Chromecast devices.

**Comment by 3ative** [comment]
Related to this?
https://github.com/custom-components/alexa_media_player/issues/477

**Comment by 3ative** [comment]
I have found with v2.3.6 this no longer happens
