### ISSUE TITLE
Feature request: medium-media-player

### ISSUE THREAD

**Issue by rdehuyss** [kalkih/mini-media-player#156]
Hi,

First of all: thanks for this excellent card which we use daily.

Some minor annoyance that we have is that the mini-media-player is sometimes too mini :-). We use it on a wall mounted tablet and we often press the wrong button. The only buttons we really use are play, pause and the volume. 
Would there be a way to have the play/pause buttons a little bit bigger? So they can be easily controlled by finger?

Thanks again,
Ronald

**Comment by kalkih** [comment]
Hello, thanks!

Yes, I see your point.
We could possibly add some sort of scaling option for the UI in the future, would require some work though as most of the UI is based on set pixel values.

Another alternative would be to use [button-cards](https://github.com/custom-cards/button-card) for play/pause and +/-.

**Comment by trankillity** [comment]
I've just come up against something similar, but slightly different in this vein.

I'm trying to use mini-media-player as a conditionally-displayed "background" for another card. I've got it working fine, however when the artwork is in "cover" mode, the height is fixed. And "full-cover" is too tall for my liking.

Would be fantastic if there was an optional "height" parameter that we could specify to get MMP to display how we prefer it.

**Comment by kalkih** [comment]
@trankillity 
Adding a static height is a bit problematic since the card scales differently depending on config, on/off state, horizontal space available, expanded menus etc.

A good solution if you really want a static height would be to use [card-mod](https://github.com/thomasloven/lovelace-card-mod), with which you should be able to achieve it easily.
Just add the desired height to the `ha-card` element.

```yaml
# card-mod example, should work?
...
type: custom:mini-media-player
style: |
  ha-card {
    height: 200px;
  }
```

**Comment by kalkih** [comment]
Example of what a scaling option would/could look like:

Scaled 150%
![hyperion_8123_lovelace_2](https://user-images.githubusercontent.com/457678/65529048-b82fb980-def5-11e9-9666-4178a29286c8.png)

Regular
![hyperion_8123_lovelace_2 copy](https://user-images.githubusercontent.com/457678/65529059-bfef5e00-def5-11e9-89d9-3a3a3fdbeaf5.png)

**Comment by rdehuyss** [comment]
Exactly what I want!

How did you do that? Using card-mod or?

**Comment by kalkih** [comment]
That was just to test the idea of a scalable option, achieved by applying/changing some styles through Google Chrome dev-tools.
But yes, should be achievable with card-mod, but would require quite a bit of CSS, especially in more complex card configs.

I like the idea, should def add a some sort of scaling option in the future.

**Comment by rdehuyss** [comment]
:tada:  :+1: 

Glad you consider this feature request... thanks again!

**Comment by xydix** [comment]
+1 👏👍

**Comment by kalkih** [comment]
> Maybe give us the option to set height of the card? Like, I want 50 pixels high. Like the lovelace-gap-card.

This card is 40px/row, same as the core entity row dimensions which I try to follow as much as possible..
Plus 16px card padding (when not using the group option) which also seems to be the standard in Lovelace.

But you can customize the height/paddings manually by utilizing [card-mod](https://github.com/thomasloven/lovelace-card-mod).

**Comment by kalkih** [comment]
UI scaling is now supported in the latest release and there's two ways you can set it.

* In the card config with the new `scale` option.
* With the theme variable `mini-media-player-scale`.

The parameter is basically the multiplier, e.g. `0.5` will scale the UI to half of the original size, `1.5` will scale it to 150% of the original size.

The card option has priority and will override the theme variable `mini-media-player-scale` if it's set.

Let me know if you notice anything strange when scaling the card, thanks!
