### ISSUE TITLE
Collaboration with Spotify playlist card?

### ISSUE THREAD

**Issue by jaburges** [kalkih/mini-media-player#157]
Hi there 
[feature request]

I have no idea where to even start, but have been using this card for EVER! so thank you :)
I wondered if you would be able to take the code from the spotify custom card but use your media_player controls? (as I'm a sonos user and your card rocks for controlling them)

https://github.com/custom-cards/spotify-card

Hope that is of some use

**Comment by iantrich** [comment]
You can already do this with service calls via https://github.com/fondberg/spotcast

**Comment by jaburges** [comment]
That uses cast not sonos devices though.

**Comment by kalkih** [comment]
Hello, thanks for the request.
I think the cards complement each other well and both have their unique place in a setup. I don't really see the need of merging them, at least not at this time.
Thanks!
