### ISSUE TITLE
Having trouble getting the plugin to work [HACS]

### ISSUE THREAD

**Issue by MaxVonk** [kalkih/mini-media-player#158]
Hello,

HA newbie using non yaml-mode, using raw editor to do my layout.

Getting the:
```javascript
Custom element doesn't exist: mini-media-player.
```

My config:

```javascript
resourses:
  - url: /community_plugin/mini-media-player/mini-media-player.js
    type: module
````

And the manual card:
```javascript
      - entitiy: media_player.hylla
        type: 'custom:mini-media-player'
```

I've checked the permissions of the the js in /www/community/mini-media-player and everything looks good.
Surfing to http//server:8123community_plugin/mini-media-player/mini-media-player.js shows the file, but the formating look like crap:

![image](https://user-images.githubusercontent.com/19408901/62422465-80ee1a80-b6b3-11e9-9af0-43bfddf7ed8a.png)

Any more ideas what to try out?
My setup (Hassbian):
![image](https://user-images.githubusercontent.com/19408901/62422470-a2e79d00-b6b3-11e9-83a1-71b88c3c935d.png)

**Comment by kalkih** [comment]
Hey,

`resources` seems to be misspelled in your config, everything else looks good!

**Comment by MaxVonk** [comment]
That did the trick, getting so stuck looking at everything else beside my spelling.
Thanks!
