### ISSUE TITLE
Song info doesnt update as it should

### ISSUE THREAD

**Issue by codycato** [kalkih/mini-media-player#159]
Only shows the previous song title and artwork when I skip the next song.

**Comment by kalkih** [comment]
Hey,
This is most likely not related to mini-media-player, it's most likely the component/device that's not updating the media info fast enough.
I know the Spotify component is updating quite slow for example.

Does it show the correct song information again after a few additional seconds?

**Comment by codycato** [comment]
No it doesnt, and when I skip to the next song the previously playing song and artwork shows up. Not the current

**Comment by kalkih** [comment]
Strange, what media device is this and does it happen on the default media card as well?

**Comment by kalkih** [comment]
@codycato Still having this issue?

**Comment by kalkih** [comment]
Closing, feel free to reopen if you still have the issue.
