### ISSUE TITLE
Multiple media players

### ISSUE THREAD

**Issue by srueg** [kalkih/mini-media-player#160]
Is it possible to control multiple media players from one card? I.e. select which player should be controlled in a drop down?

**Comment by iantrich** [comment]
no, but you could fashion this with some conditional cards on an input_select

**Comment by srueg** [comment]
Wow that was quick. Thank you!
Would this be something worth for a feature request?

**Comment by iantrich** [comment]
That's not my call. And now that I think of it, this would be a better option: https://github.com/thomasloven/lovelace-state-switch

**Comment by srueg** [comment]
Cool thank you, I'll give it a try 😃

**Comment by kalkih** [comment]
Hello, thanks for the suggestion.
Yeah I think conditional cards / state switch combined with an input select is the way to go here.
The beauty of lovelace, it's so customizable!
