### ISSUE TITLE
more than 5 shortcut columns

### ISSUE THREAD

**Issue by da-anda** [kalkih/mini-media-player#163]
I'm having some BOSE Soundtouch speakers that have 6 numbered preset buttons. It would be nice if you would allow more than 4 (4 according to docs, 5 actually according to the components CSS) columns for shortcut buttons. I hacked my way around in the compressed JS and added the CSS definition for 6 columns and it's looking good IMO (also in portrait mode on Smartphones). So would you consider adding more column options?
Thanks.

edit: I can also PR the change if you are fine with such a change

**Comment by kalkih** [comment]
Absolutely, if you could submit a PR with the change that would be great!

**Comment by kalkih** [comment]
Added support for up to 6 columns in latest release.

**Comment by da-anda** [comment]
thanks. (and dang, wanted to wait with the PR until Hacktoberfest started :) )

**Comment by kalkih** [comment]
Oh haha, but feel free to take on any of the other open issues/feature requests 😉😉
