### ISSUE TITLE
services for Shortcuts not working correctly due to always added `entity_id` data

### ISSUE THREAD

**Issue by da-anda** [kalkih/mini-media-player#164]
Some services are strict about the params/data they receive and thus can't be triggered by the current service calling implementation of the player object, since that one is always adding the `entity_id` as service parameter/data. Would it be possible to remove it by default? Simplest solution might be to distinguish between external (shortcut buttons) and internal service calls and only add it to internally triggered calls.

Noticed the issue when I tried to add a party mode button for my Soundtouch speakers (play everywhere -> https://www.home-assistant.io/components/soundtouch/#service-soundtouch_play_everywhere). This service f.e. doesn't like the `entity_id` as service param.

Thanks.

**Comment by kalkih** [comment]
Great catch!
Yes, we should change it to skip the internal callService wrapper.

**Comment by kalkih** [comment]
https://github.com/kalkih/mini-media-player/blob/cd36cfc9e8b9e651dcdd441bdd292d70f272ac3f/src/model.js#L311-L317

That should do the trick!

**Comment by da-anda** [comment]
it did, thank you
