### ISSUE TITLE
Volume knob text not visible

### ISSUE THREAD

**Issue by Merwenus** [kalkih/mini-media-player#166]
https://i.imgur.com/gg6iEAN.png

Text is lower then it should. CSS says transform should be -30 instead of -17
.pin.expand > .slider-knob > .slider-knob-inner::after

**Comment by kalkih** [comment]
Yes, I've noticed that as well in certain configs.

The volume slider is a seperate component and I can't really override the style of it easily, which is unfortunate.

**Comment by kalkih** [comment]
Should now be fixed in the latest release.
