### ISSUE TITLE
Play/Pause button, replace with Play/Stop

### ISSUE THREAD

**Issue by cweakland** [kalkih/mini-media-player#167]
Would it be possible to replace the play/pause button with play/stop. Using Musiccast speakers and XMradio, the pause button has no effect. If I replace mute with stop, then I can stop the music from plying.

Perhaps we could add a card option for 'replace_pause' and have one of the options be 'stop'?

**Comment by lamirand-g** [comment]
+1 for this one.

You could even offer a hidden option to display or not the stop button next to play/pause.
I could look at it if you accept PR.

**Comment by kalkih** [comment]
PRs are very welcome.

**Comment by Mofeywalker** [comment]
Hey, I added a boolean option "replace_pause" which replaces the pause button when media is playing with a stop button and also the onclick action with "media_stop"
Example config:
```yaml
    type: custom:mini-media-player
    entity: media_player.kuche
    replace_pause: true
```

Screenshot:
<img width="469" alt="player" src="https://user-images.githubusercontent.com/596549/66682528-a8de9900-ec75-11e9-8413-5fb115a80771.png">

**Comment by lamirand-g** [comment]
@Mofeywalker Great job! I was thinking to have option to get both pause and stop button. I'll try to work on it this weekend

**Comment by lamirand-g** [comment]
I have worked on the option to display stop button. PR #177

![image](https://user-images.githubusercontent.com/4324887/66697872-bded1380-ecd9-11e9-86e2-ddd386654072.png)

**Comment by kalkih** [comment]
Now available in the latest release, thanks @guillaumelamirand!
