### ISSUE TITLE
Two sets of controls

### ISSUE THREAD

**Issue by joberbr** [kalkih/mini-media-player#169]
Hello,
Ever since the latest update, I am getting 2 sets of media controls and volume.

![image](https://user-images.githubusercontent.com/40904517/64056593-3bedc480-cb49-11e9-8c8f-429bb0c71178.png)

**Comment by kalkih** [comment]
Hey, very strange.
What HA version and browser are you running?

**Comment by joberbr** [comment]
I am running v 0.98.0 and latest version of Chrome.

**Comment by davidlamd89** [comment]
I have the same problem. Any solution?

**Comment by kalkih** [comment]
Haven't been able to reproduce the issue yet.
Would any of you mind sending me your configs where you are seeing this?

**Comment by kalkih** [comment]
Fixed in the latest release [v1.3.1](https://github.com/kalkih/mini-media-player/releases/tag/v1.3.1).
