### ISSUE TITLE
JSON and comment says 0.85 but 0.84 embedded in file

### ISSUE THREAD

**Issue by DavidFW1960** [kalkih/mini-media-player#17]
JSON and comment says 0.85 but 0.84 embedded in file

I'm going to download it and edit the js file to 0.85 here.

**Comment by kalkih** [comment]
Thanks, I missed updating that, too late now since the release is out already, but it doesn't really matter, the comment in `mini-media-player.js` doesn't really do anything other than displaying the current version number.

**Comment by DavidFW1960** [comment]
Yeah but it causes issues with the custom card update tracker....

**Comment by kalkih** [comment]
No, that comment doesn't have anything to do with the updater, I could as well remove it, it doesn't serve any purpose more than letting you know what version of the file you are viewing.
The updater is based on data provided in the `tracker.json`

**Comment by kalkih** [comment]
Ok, that's odd maybe custom updater got stuck while updating or failed to update the version number. The restart of HA probably solved this.

Yes, exactly, custom updater checks the `ui-lovelace.js` for current version number, it's the `?ver=` part of the card url.
