### ISSUE TITLE
Error in join snapcast speaker

### ISSUE THREAD

**Issue by elle2** [kalkih/mini-media-player#170]
In Home Assistant 0.98.1, I'm using a multiroom audio system with mopidy+snapcast.
This solution plays quite well using the mini-media player to control mpd server and also the single snapcast clients/speakers.
I've seen that the last version of mini media player enables the grouping of snapcast speakers, but when I try to join a snapcast player to the master I receive this error:  
Unable to find service media_player/snapcast_join
Moreover there is no error using the snapcast.join or snapcast.unjoin service via developer interface into HA UI.

**Comment by kalkih** [comment]
Hello,
The card should use `snapcast/join` & `snapcast/unjoin` in the latest version, so I suspect your browser hasn't loaded the latest version.

Try clearing cache / hard refresh, or if you installed the card through HACS, check the quote below.

> You didn't possibly install the card from HACS?
> 
> If so, please double check the resource reference as it seems to have changed recently.
> 
> For me it's now
> 
> ```yaml
>  - url: /community_plugin/mini-graph-card/mini-graph-card-bundle.js
>    type: module
> ```
> 
> And before:
> 
> ```yaml
>  - url: /community_plugin/mini-graph-card/mini-graph-card.js
>    type: module
> ```
> 
> You can see the correct one by navigating to the card in the HACS store

**Comment by elle2** [comment]
@kalkih  Thank you.

**Comment by raph2i** [comment]
hey guys!
it seems like the unjoin server wont be triggered.
i'm using home assistant 0.98.3 and hacs.

`2019-09-09 21:54:02 ERROR (MainThread) [frontend.js.latest.201908280] https://some.domain.org/community_plugin/mini-media-player/mini-media-player-bundle.js:1:0 NotSupportedError: Operation is not supported`
