### ISSUE TITLE
Error in unjoin snapcast speaker

### ISSUE THREAD

**Issue by raph2i** [kalkih/mini-media-player#171]
#170 

hey guys!
it seems like the unjoin service wont be triggered.
i'm using home assistant 0.98.3 and hacs.

ha.log:
2019-09-09 21:54:02 ERROR (MainThread) [frontend.js.latest.201908280] https://some.domain.org/community_plugin/mini-media-player/mini-media-player-bundle.js:1:0 NotSupportedError: Operation is not supported

**Comment by kalkih** [comment]
Hey,
Did you try this:
> You didn't possibly install the card from HACS?
> 
> If so, please double check the resource reference as it seems to have changed recently.
> 
> For me it's now
> 
> ```yaml
>  - url: /community_plugin/mini-graph-card/mini-graph-card-bundle.js
>    type: module
> ```
> 
> And before:
> 
> ```yaml
>  - url: /community_plugin/mini-graph-card/mini-graph-card.js
>    type: module
> ```
> 
> You can see the correct one by navigating to the card in the HACS store

Does join work, not just unjoin?

**Comment by raph2i** [comment]
wow this response was quick :)

I've read the hacs issue...

this is how i've added it via lovelace raw editor:
`resources:
  - url: /community_plugin/mini-media-player/mini-media-player-bundle.js
    type: module`

the error happens with and without trailing `?v=1.3.0`

snapcast join works flawlessly!

this is how my card config looks like:

`entity: media_player.snapcast_client_mastermac
hide:
  icon: true
  power: true
speaker_group:
  entities:
    - entity_id: media_player.snapcast_client_mastermac
    - entity_id: media_player.snapcast_client_somemac0
    - entity_id: media_player.snapcast_client_somemac1
  expanded: true
  platform: snapcast
  show_group_count: true
  sync_volume: true
type: 'custom:mini-media-player'`

p.s.: group count also wont work, is this intended, cause i am -not- using the snapcast group?

**Comment by kalkih** [comment]
Alright, could you please navigate to http://yourhaIP:port/developer-tools/state and check what attributes a snapcast entity expose, you might have to press it and then navigate to the top of the page to see all attributes.
Would be even more useful if this entity was part of a group.

**Comment by kalkih** [comment]
@elle2 Sorry for tagging you but quick question, does the snapcast group management work well for you?

**Comment by raph2i** [comment]
here is the master:
```
{
  "volume_level": 0.35,
  "is_volume_muted": false,
  "source": "Mopidy",
  "source_list": [
    "SpotifyConnect",
    "Mopidy",
    "Nichts",
    "TTS"
  ],
  "friendly_name": "Docker",
  "supported_features": 2060
}
```


here is one client:

```
{
  "volume_level": 0.34,
  "is_volume_muted": false,
  "source": "Mopidy",
  "source_list": [
    "SpotifyConnect",
    "Mopidy",
    "Nichts",
    "TTS"
  ],
  "friendly_name": "android",
  "supported_features": 2060
}
```

**Comment by kalkih** [comment]
Okay, that's why unjoin doesn't work, it has to know the current group configuration and there's no attribute exposing it.

@lyghtnox Isn't the group exposed as an attribute?

**Comment by raph2i** [comment]
here is the api output from a client, if it helps:

```
{
    "attributes": {
        "is_volume_muted": false,
        "source": "Mopidy",
        "source_list": [
            "SpotifyConnect",
            "Mopidy",
            "Nichts",
            "TTS"
        ],
        "supported_features": 2060,
        "volume_level": 0.41
    },
    "context": {
        "id": "9dbda2d3d86d401196970dfd4df90f51",
        "parent_id": null,
        "user_id": null
    },
    "entity_id": "media_player.snapcast_client_xxxxxxxxxxxxx,
    "last_changed": "2019-09-09T19:24:25.558862+00:00",
    "last_updated": "2019-09-09T19:28:15.766059+00:00",
    "state": "on"
}
```

**Comment by lyghtnox** [comment]
Indeed the snapcast component doesn't provide a group attribute. 
However, you don't need the group name to unjoin, do you?

**Comment by kalkih** [comment]
Not the actual group name, but the group composition is very important.
It's used widely throughout this cards group management implementation.
Mainly to keep track of which entities are currently grouped and how they are grouped, but also to determine who's the master, group count etc.

In this case: The `unjoin` service will probably never even get called since the card doesn't know the entity isn't a part of a group and will instead call `join` again.

Here's how the group attribute works in the Sonos implementation, which the group management of this card was originally built around.

- The group is a list/array.
- The group contains the entity id's of all of its members.
- The group looks the same on master and client/slave.
- The initial entry is the master.

I think it's important to have this information handled by the component so outside operations are  reflected in HA & frontend as well as persistent information between page refreshes/devices.

**Comment by kalkih** [comment]
Thanks @lyghtnox, that would be great!

If it's hard to get the master speaker to be the initial entry in the exposed group list/array an additional exposed attribute would work as well, like `is_master`, or something.

Would be great if the group attribute was named `[platform]_group` similar to sonos [sonos_group](https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/sonos/media_player.py#L95).

**Comment by lyghtnox** [comment]
There is no master/slave system in snapcast. There is a group entity for each player and if two players are in the same group they are synchronized. 

There is no hierarchy between players inside the group, every player can change the source, add new clients, remove clients etc.

**Comment by kalkih** [comment]
Alright, that's cool and good to know!

**Comment by fietstasss** [comment]
Is there any intention to get this grouping working?
