### ISSUE TITLE
Harman Kardon Citation speaker support

### ISSUE THREAD

**Issue by bboerendans** [kalkih/mini-media-player#172]
Is it possible to get this working with Harman Kardon citation speakers? Those speakers have 
Goolge Cast support.

**Comment by kalkih** [comment]
As long as they are supported in Home Assistant, (which i don't know if they are?) they should work with this card.

Best guess would be either the [Cast component](https://www.home-assistant.io/components/cast/) or the [Harman Kardon AVR component](https://www.home-assistant.io/components/harman_kardon_avr/).
