### ISSUE TITLE
Feature Request: Add tap_action to the Main Card

### ISSUE THREAD

**Issue by stmrocket** [kalkih/mini-media-player#174]
First, this card is exactly what I was looking for in a media player.  It has been working well since I set it up.

Would it be possible to add tap_action (and ideally hold_action) parameters to the media player card itself?  This would allow for triggering an action instead of the more-info pop-up.  

Some background: I have been using pop-up card to show a custom card instead of the default more-info card on several minimalist players to save room but still give access to source and transport controls when needed.  This card has now been deprecated and the replacement requires a service call to trigger the pop-up.

**Comment by darkkatarsis** [comment]
Yes, it would be great!

**Comment by kalkih** [comment]
If anyone wanna help implement this feature:
I've implemented this in my other card and the implementation can be found [handleClick.js](https://github.com/kalkih/mini-graph-card/blob/dev/src/handleClick.js), we should be able pretty much copy paste it into this project.

**Comment by crazytok** [comment]
+1 on this! I would really like to use this feature for redirection to another more advanced Music tab!

**Comment by stmrocket** [comment]
Looking over the code, this looks like it should be simple to bring over.  I'll work on it.

**Comment by kalkih** [comment]
Let me know if you need assistance 👍

**Comment by crazytok** [comment]
You guys are awesome!

**Comment by darkkatarsis** [comment]
And how about this functionality?

**Comment by kalkih** [comment]
Now available in the latest release, thanks @darkkatarsis.

**Comment by darkkatarsis** [comment]
@kalkih Will it be very complicated to add hold action support?
