### ISSUE TITLE
No GUI or Code error

### ISSUE THREAD

**Issue by ravet007** [kalkih/mini-media-player#175]
Hi,
I have tried and tried but can't get the media to work. I am trying this for the soundtouch from Bose. 
I'm so confused. Please help.
My steps:
1. Installed MiniMediaPlayer from HACS. 
2. Added the following to Config.Yaml  - url: /community_plugin/mini-media-player/mini-media-player-bundle.js
    type: module
3. Tried to create a Manual card, Horizontal stack, Media player with the following code:
type: custom:mini-media-player
entity: media_player.kitchen_speakers
and a few other mentioned in the repository, with and without the dash. I get the following errors - No GUI editor available or Cannot read property 'setConfig' of undefined.
No preview is available. I cleared cache, refreshed, restarted. Nothing. 

I have no idea what entity means - An entity_id from an entity within the media_player domain. What is this? I tried media_player.soundtouch

Please help me find a solution. Thank you. I checked the issue 126, 100 but could not resolve my issue.

**Comment by kalkih** [comment]
Are you using Lovelace is storage or yaml mode (do you use the GUI editor)?

Entity would be the same as in any other card, the entity you want the card to handle.
If you don't know your entity id's check http://[your-ha-ip]:[port]/developer-tools/state

**Comment by ravet007** [comment]
Hi
I’m using the config GUI
The entity does not show up. Even under configuration, state > the mini-media does not show up. Others do.

**Comment by ravet007** [comment]
Screenshots of the states page
![4B81E6C8-00AD-44CE-95FC-0F59FD0F8701](https://user-images.githubusercontent.com/56083240/66433331-c4f7f580-ea3d-11e9-844a-2ea5b08c8cc4.png)
![Uploading FF43974B-6571-43BC-999D-7D529E272B55.png…]()
![Uploading FB314EE9-411F-4261-AC4A-C3E587706355.png…]()

**Comment by kalkih** [comment]
Mini media player shouldn't show up there, entities you would use in the mini-media-player configuration should though.
All entities starting with `media_player` (inside the `media_player` domain) are compatible, and this is what you should put in the `entity` card option.

```yaml
- type: custom:mini-media-player
  entity: media_player.kitchen_speakers # replace with your own entity
```

**Comment by ravet007** [comment]
Why can’t I find media player entity’s?
Sorry I’m a noob.

**Comment by ravet007** [comment]
I tried your code. 
Error : no gui for custom:mini-media-player

**Comment by ravet007** [comment]
Figured it out, added this in Config Yaml
# Bose Soundtouch
media_player:
  - platform: soundtouch
    host: [ip address]
    port: 8090
    name: Bose Hall

Then added this for Bose and Presets in the Config UI manual card:

artwork: full-cover-fit
entity: media_player.bose_hall
group: true
hide:
  source: false
icon: 'mdi:speaker-wireless'
name: Bose Hall
scroll_info: true
shortcuts:
  buttons:
    - icon: 'mdi:numeric-1-box'
      id: 1
      name: Classic FM
      type: playlist
    - icon: 'mdi:numeric-2-box'
      id: 2
      name: KUSC
      type: playlist
    - icon: 'mdi:numeric-3-box'
      id: 3
      name: Rock 92
      type: playlist
    - icon: 'mdi:numeric-4-box'
      id: 4
      name: Smooth London
      type: playlist
    - icon: 'mdi:numeric-5-box'
      id: 5
      name: WIXX
      type: playlist
    - icon: 'mdi:numeric-6-box'
      id: 6
      name: 100 Hitz
      type: playlist
type: 'custom:mini-media-player'

**Comment by ravet007** [comment]
Next question; How do I add this to my HOME app on IOS?

**Comment by kalkih** [comment]
What do you mean by HOME app, Apple HomeKit?
If so, not possible (at least with this project), this project is for Home Assistant.

**Comment by ravet007** [comment]
Yes Apple homekit, I know but Homekit integration is now part of HA. I thought maybe this would go into Homekit as well. But it didn't. 
Thank you for the help,  really appreciate it.

**Comment by kalkih** [comment]
Alright, check out [this page](https://www.home-assistant.io/integrations/homekit/).
This project is simply a frontend addon for HA, so it doesn't really have anything to do with backend integrations etc.

Glad you got it working and I hope you enjoy the card, cheers!
