### ISSUE TITLE
Uncaught SyntaxError: Missing } in template expression

### ISSUE THREAD

**Issue by RodBr** [kalkih/mini-media-player#18]
On the move to 0.8.6 I'm now getting this error:
custom_ui/mini-media-player.js?v=0.8.6:110:43 Uncaught SyntaxError: Missing } in template expression

**Comment by jaburges** [comment]
same here

**Comment by mokshmridul** [comment]
Same here as well. 

Running HA . 80

**Comment by JamesMcCarthy79** [comment]
I get the same error

**Comment by Styx85** [comment]
Same here.
Running HA on ArchLinux . 80

**Comment by bramkragten** [comment]
See https://github.com/kalkih/mini-media-player/pull/19
