### ISSUE TITLE
Sonos Grouping Issues

### ISSUE THREAD

**Issue by dacorn** [kalkih/mini-media-player#180]
Hi, I have 8 sonos rooms, I created a group of only 4 of the 8, when I select two for example, music turns on and plays as expected but it adds ALL rooms to the group. I can watch it in the Sonos app and it does indeed group all 8 even when I have only chosen two.

**Comment by kalkih** [comment]
Hello,
This is really hard for me to debug since I don't own any Sonos devices.
I checked the Sonos component and there's been no recent changes made to the component, so I'm not sure what this could be.

Did it work properly for you before?

Could you post your card config and double check to make sure all entity names are spelled correctly?

**Comment by dacorn** [comment]
Hi,

Thanks for getting back to me, no this is the first time I have used the mini media player. My Sonos works fine with each standalone player with no issue. ITs just when I try to use the multiform feature you have built. 

entities:
  - entity: media_player.connect_1
    hide:
      icon: true
      power: true
      shuffle: false
      source: false
    name: Multi Room
    speaker_group:
      entities:
        - entity: media_player.connect_1
          name: Sonos
        - entity: media_player.naim_living_room
          name: Living Room
        - entity: media_player.outdoor_kitchen
          name: Outdoor Kitchen
        - entity: media_player.pool
          name: Pool
      platform: sonos
      show_group_count: true
    type: 'custom:mini-media-player'
type: entities


This is my code for this card. Entities are correct as they work fine as individual players.

Cheers,
Dave

**Comment by kalkih** [comment]
Alright, I see what the issue is now!
You're listing the speaker group entities incorrectly, `entity` should be `entity_id` inside the speaker_group entities option.
See [speaker-entity-object](https://github.com/kalkih/mini-media-player#speaker-entity-object)
