### ISSUE TITLE
Feature request: Sonos speech_enhance and night_sound

### ISSUE THREAD

**Issue by gieljnssns** [kalkih/mini-media-player#181]
I recently bought a Sonos Playbase, there are 2 extra attributes ```speech_enhance``` and ```night_sound```.
Can you make these an option like ```shuffle```?

```
volume_level: 0.1
is_volume_muted: false
media_content_type: music
media_artist: TV
source: TV
source_list: 70s Rock Anthems,80s Rock Anthems,Arrow Classic Rock,Complete Chaos,Desertsession Radio,Discover Weekly,Doom/Stoner/Sludge Metal,Dreamy & Distorted,Dunk!Festival,Fuzz FM,Gitannekesfoor :Radio:,Hand of Doom Radio,Het betere genre,Hotmixradio Metal,KXLU,MetalRock.FM,Noor - Fien,Pure Rock Radio,Radio Caprice Stoner Metal,Radio Uylenspiegel,Real Punk Radio,Release Radar,Rock Classics,Studio Brussel,The Greatest Switch - De beste dance classics!,The Psychedelic Entity,This is: Belgium,Undiscovered Rock Radio,Voodoo Rhythm Records & Co.,Wacken Radio,WFNGR696.com The FINGER,Willy,Zware metalen,’80s Hard Rock
shuffle: false
sonos_group: media_player.living_2
night_sound: false
speech_enhance: false
friendly_name: Living
supported_features: 64063
```

**Comment by kalkih** [comment]
Hello, thanks for the suggestion.
I'm very hesitant when it comes to adding platform specific features and trying to stay away from it.

You can utlize card shortcuts to set these options by either calling scripts or the services directly, see the [docs](https://github.com/kalkih/mini-media-player#shortcut-item-object) and the [card with media shortcuts](https://github.com/kalkih/mini-media-player#card-with-media-shortcuts) example for shortcuts usage.
