### ISSUE TITLE
Feature request: add LMS to Speaker group object

### ISSUE THREAD

**Issue by Iv711** [kalkih/mini-media-player#182]
Hello!
Logitech media server has good support for multi-room players. But unfortunately in HA it is now extremely inconvenient to manage their synchronization. In fact, you can only turn it on and off, but synchronization is turned on only in the LMS web interface itself. Is it possible to add support similar to sonos?

**Comment by kalkih** [comment]
Hey,
I looked at the squeezebox HA component source and it wouldn't work, there are features missing that would have to be implemented in the component before I could add support for it in this card.

**Comment by kalkih** [comment]
What would be required,
Service calls for `join/unjoin` and an attribute that expose the current group composition.
The Sonos component is a great example.

**Comment by Iv711** [comment]
> What would be required,
> Service calls for `join/unjoin` and an attribute that expose the current group composition.
> The Sonos component is a great example.

Today, friends shared automation that includes synchronization:
`  - service:  media_player.squeezebox_call_method
    data_template:
      entity_id: media_player.raspiplayer
      command: sync
      parameters: ["ab:cd:ef:12:34:56"]
  - service:  media_player.squeezebox_call_method
    data_template:
      entity_id: media_player.raspiplayer
      command: sync
      parameters: ["74:da:38:41:f8:1d"]
  - service:  media_player.squeezebox_call_method
    data_template:
      entity_id: media_player.raspiplayer
      command: sync
      parameters: ["f2:b4:29:58:f2:df"]  `

And automation disabling synchronization:
`  - service:  media_player.squeezebox_call_method
    data_template:
      entity_id: media_player.sqq
      command: sync
      parameters: ["-"]
  - service:  media_player.squeezebox_call_method
    data_template:
      entity_id: media_player.orange
      command: sync
      parameters: ["-"]
  - service:  media_player.squeezebox_call_method
    data_template:
      entity_id: media_player.lede
      command: sync
      parameters: ["-"]`

Can this help in this situation?

**Comment by kalkih** [comment]
Possibly, but those examples doesn't provide me with much information, what is the function of the parameters? looks like a MAC address, how does "multiroom/sync" work in LMS? Is there a master device and then slaves or is the server the master and the devices/speakers slaves? Is there a way to get the "speaker group" / sync composition of an entity?

I don't own any squeezebox devices and am not familiar with the API.
Would be great if someone with experience of LMS/HA and also want this functionality could submit a PR.

**Comment by Iv711** [comment]
Yes, this is the MAC address.
Technically, there is 1 - LMS server, and clients connect to it. In HA we add only the server at the address, clients appear there automatically. But apparently information on poppy addresses is not transmitted to HA
![Screenshot_1](https://user-images.githubusercontent.com/34803844/67625773-031d5380-f84b-11e9-97be-c23c810d4564.png)
The server itself provides the following information on connected devices:
![Screenshot_2](https://user-images.githubusercontent.com/34803844/67625777-17615080-f84b-11e9-8b2d-83e0f0d08ee3.png)

**Comment by Iv711** [comment]
This is what the CLI API looks like.
[cli-api_7.6.zip](https://github.com/kalkih/mini-media-player/files/3775265/cli-api_7.6.zip)
the truth is there are commands to control via telnet, but they work fine if you transfer them in json format. Example:
`$playlist = 'http://192.168.1.103/playlist.m3u';
callMethod('PlayerBedroom.Play',array('playlist' => $playlist));`
There is also a REST API, but on it, I have not yet found the necessary information

**Comment by kalkih** [comment]
Alright, in my opinion this should be made more abstract by implementing additional service calls in the HA LMS component, one call for join and one for unjoin, similar to how most other multiroom components does it. This would not only benefit this project but also the general HA user when interacting with LMS.

See the [Sonos source](https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/sonos/media_player.py) for a great example.

There would also need to be a way to get the current group composition through the entity's attributes, the Sonos component has this implemented as well and is a great example.

When that is done I would be happy to add support for it in this card.
