### ISSUE TITLE
Changing source with a shortcut doesn't update source dropdown.

### ISSUE THREAD

**Issue by michaelarnauts** [kalkih/mini-media-player#184]
When using a shortcut to change the source, the source dropdown isn't updated.

I'm using this snippet:

```json
  - entity: media_player.receiver
    group: true
    icon: 'mdi:audio-video'
    max_volume: 50
    power_color: true
    shortcuts:
      buttons:
        - icon: 'mdi:television'
          id: TV
          type: source
        - icon: 'mdi:google-chrome'
          id: Chromecast
          type: source
        - icon: 'mdi:nintendo-switch'
          id: Nintendo Switch
          type: source
      columns: 4
    show_progress: true
    show_source: small
    type: 'custom:mini-media-player'
```

From the perspective of the `media_player.receiver`, I can only change the source, I can't see the current source. Therefore, it isn't reflected in the interface when changing on the device itself. When changing the source from the dropdown, the last selected value is shown, so when using a shortcut, it should be possible to also update this.

**Comment by kalkih** [comment]
Sure, I'll make sure the dropdown stays in sync with the source reported by the component.

**Comment by kalkih** [comment]
Should be fixed in the latest release, thanks!
