### ISSUE TITLE
Volume tear drop cut in half over slider

### ISSUE THREAD

**Issue by Merwenus** [kalkih/mini-media-player#185]
Volume effect is cut half.
Tested in Firefox and Chrome.
Tested version 1.4.2 and 1.3.1
HA 101.3

The tear drop is a bit higher and visually cut in half.
https://i.imgur.com/3me33bF.png

No idea if it is HA or MMM problem, maybe someone can fix it.

**Comment by kalkih** [comment]
Definitely an issue with this card and not HA.
It's a matter of some CSS and maybe adding an additional container element to make sure we don't allow overflow of cover artwork (especially with card border-radius) and other stuff but still allow the volume pin to overflow.

**Comment by kalkih** [comment]
Should be fixed in the latest release, might still occur if the mmp card is nested inside another card that doesn't allow overflow but I can't do anything about that.
