### ISSUE TITLE
option to set the background-opacity 

### ISSUE THREAD

**Issue by basnijholt** [kalkih/mini-media-player#189]
Just like one can set `mini-media-player-artwork-opacity`, it would be great to have a `mini-media-player-background-opacity`.

Probably very similar to https://github.com/kalkih/mini-media-player/commit/6b03b777f43b61a09d32869c1b3b637a42ad797e.

**Comment by kalkih** [comment]
Now available in the latest release: `mini-media-player-background-opacity`
