### ISSUE TITLE
Volume Slider dot should have `cursor: grab` or similar

### ISSUE THREAD

**Issue by ProLoser** [kalkih/mini-media-player#194]
Hovering the mouse over the volume slider does not change to a pointer, so it's not immediately clear when using a mouse that you can click on the slider bar or click and hold the knob.

**Comment by kalkih** [comment]
True and this actually seem to be the case for all sliders in HA.
The slider component used in this card is from HA [ha-slider](https://github.com/home-assistant/home-assistant-polymer/blob/42e60beb0d1046b70827e13620bcdffc5866cace/src/components/ha-slider.js), which in case is extending [paper-slider](https://www.webcomponents.org/element/@polymer/paper-slider/elements/paper-slider).

Maybe this should be addressed directly in the HA frontend?
