### ISSUE TITLE
Hide controls for specific source

### ISSUE THREAD

**Issue by kibs** [kalkih/mini-media-player#199]
This is some kind of edge case, nice to have feature.

We have a Sonos playbar under our TV, It would be nice to hide controls like Play, Prev, Next when source is TV, is that something that is even remotely possible?

**Comment by kalkih** [comment]
Hello, I guess you solved itsince you closed this.
Otherwise checkout [config-template-card](https://github.com/iantrich/config-template-card), I think this would be a perfect use case for it.

**Comment by kibs** [comment]
hey, just thought the issue was way to specific for my usecase, thanks for pointing me to template card, looks awesome!
