### ISSUE TITLE
Error after install

### ISSUE THREAD

**Issue by magnusoverli** [kalkih/mini-media-player#2]
Hi!

I have installed this card and I cannot get it to work. The card displays the following error:
```
i.setConfig is not a function. (In 'i.setConfig(e)', 'i.setConfig' is undefined
```

The log is now throwing this error:

```
https://xxxxxxxxx.duckdns.org:8123/local/mini-media-player.js:5:40 TypeError: this.createShadowRoot is not a function. (In 'this.createShadowRoot()', 'this.createShadowRoot' is undefined)
```

**Comment by kalkih** [comment]
Hey,
This is most likely a browser compatibility issue and I think this should be solved with the latest release [v0.5](https://github.com/kalkih/mini-media-player/releases/tag/v0.5).
Please try updating, and make sure to change the version number in your `ui-lovelace.yaml`
```yaml
resources:
  - url: /local/mini-media-player.js?ver=0.5
```

**Comment by magnusoverli** [comment]
New error in log:
```
https://xxxxxxxxx.duckdns.org:8123/local/mini-media-player/mini-media-player.js?ver=0.5:2:0 SyntaxError: Unexpected token '{'. import call expects exactly one argument.
```

**Comment by kalkih** [comment]
What browser are you using?

Make sure you have `javascript_version: latest` set in your `configuration.yaml` under `frontend:`.

**Comment by kalkih** [comment]
I think I've figured out the issue now!
The resource type in your `ui-lovelace.yaml` should be set to **module** and not **js**, like below.

```yaml
resources:
  - url: /local/mini-media-player.js?ver=0.5
    type: module
```

I hope this will resolve your issue.

**Comment by magnusoverli** [comment]
That solved it! Thanks for quick response and good feedback!
