### ISSUE TITLE
tap_action not working

### ISSUE THREAD

**Issue by stmrocket** [kalkih/mini-media-player#200]
I am attempting to set up a tap_action on my media players to call a script, but even with the action set to call-service suing the code below, the more-info popup appears when the player is clicked.  Am I doing something wrong?  I have verified that the script works when attached to other elements that use a tap_action.

```
- type: custom:mini-media-player
   entity: media_player.office_stereo
   name: Office
   icon: mdi:speaker
   group: true
   artwork: none
   volume_stateless: true
   hide:
     source: true
     controls: true
     info: true
   tap_action: 
     action: call-service
     service: script.popup_media_office
     service_data:
       deviceID: 
         - this 
```

**Comment by kalkih** [comment]
Hello,
I'm not able to reproduce this, scripts and scripts with service data seem to work fine for me.

If the more-info popup appears that most likely means that your browser is still loading an older version of the card from cache.
If you installed the card manually, try clearing cache.
If you installed the card through HACS, see [this issue](https://github.com/kalkih/mini-graph-card/issues/169).

**Comment by stmrocket** [comment]
Thank you!  The linked issue was my problem.  Everything is now working as expected.
