### ISSUE TITLE
Background color for shortcuts list

### ISSUE THREAD

**Issue by Krocko** [kalkih/mini-media-player#201]
Is it possible to change the background color for the shortcuts list?
And would it be possible to expand the list to the top?
For me it is transparent and cut off.

![IMG_4670 2](https://user-images.githubusercontent.com/29394115/70865221-4054b680-1f5b-11ea-93bf-6bbfadf6e213.png)

**Comment by kalkih** [comment]
Hello, thanks for making me aware of this.
That's definitely a bug, I'll look into it.
I can probably make the list expand towards the top if there's more space above the card than below.

**Comment by Krocko** [comment]
Thank you very much.

**Comment by kalkih** [comment]
I'll try to do a minor release tomorrow with the issue addressed.

**Comment by kalkih** [comment]
Fixed in the latest release, thanks!
