### ISSUE TITLE
Card Type not found.  Bundle vs no bundle.  HACs

### ISSUE THREAD

**Issue by hanerd** [kalkih/mini-media-player#206]
Having a frustrating issue...

I've installed the card via HACs which has installed the bundle js to:
`community_plugin/mini-media-player/mini-media-player-bundle.js`

However, when I load the page, the inspector is giving me a 404 because it's looking for the non-bundle version even though my lovelace resources indicate the bundle version.

```  
  <snip>
  - url: /community_plugin/simple-thermostat/simple-thermostat.js
    type: module
  - url: https://cdn.jsdelivr.net/npm/rgb-light-card
    type: js
  - url: /community_plugin/mini-media-player/mini-media-player-bundle.js
    type: module
```
![image](https://user-images.githubusercontent.com/49296333/71110967-5b5f3a80-2196-11ea-811e-aaab9aef13da.png)

I've cleared cache and tried on different machines.  Any idea why everything would be trying to reference the older, unbundled JS version?

**Comment by hanerd** [comment]
I do have this "worked around" by symlinking mini-media-player-bundle.js to mini-media-player.js, but I feel like that's not a good long term solution as I'm inevitably going to forget and have to find this, at that point, closed github issue.  :-p

**Comment by kalkih** [comment]
Hello,

Strange, the file should really be loaded from the resource url specified in the resource section of the configuration file.

Makes no sense the browser would load it from `/mini-media-player.js` if `/mini-media-player-bundle.js` is specified. Are you sure you're setting the resources in the correct location.
If using lovelace in `yaml mode` it would be in your `configuration.yaml` file, and if using lovelace in `storage mode` you would need to specify the resources though the raw UI editor from within the Home Assistant GUI.

Haha, nice solution 😉 But as you said, shouldn't be required.

**Comment by hanerd** [comment]
Yeah, that's what I'm really confused on.  

Re: configuration.  Shouldn't it be in `ui-lovelace.yaml` and not `configuration.yaml`?  I have all other custom cards under `resources:` in `ui-lovelace.yaml`

![image](https://user-images.githubusercontent.com/49296333/71120419-615f1680-21aa-11ea-82f6-ed91e51f96f7.png)

**Comment by kalkih** [comment]
Sorry for the confusion, I mean't to write `ui-lovelace.yaml`.
Are you using lovelace in yaml mode?

**Comment by hanerd** [comment]
Yes.  I never switched to `./storage` . Old habits and all that.

I do wonder if something internally is holding onto the old url that wasn't bundled, but I have no idea where to even begin looking in the inner workings to dig into it.

**Comment by kalkih** [comment]
Okay, weird.
I'm not sure then, you don't have multiple resource sections or something in your file?

You could try removing one of the other resources and see if that card still shows up in the UI I guess (which it shouldn't).

**Comment by kalkih** [comment]
@hanerd Did you figure it out?

**Comment by kalkih** [comment]
Feel free to reopen if you still have the issue
