### ISSUE TITLE
Reduce padding back to 2px when progress bar is disabled and group:true is specified

### ISSUE THREAD

**Issue by scstraus** [kalkih/mini-media-player#210]
Hi, this is just to follow up from our discussion [here](https://community.home-assistant.io/t/lovelace-mini-media-player/68459/1333?u=scstraus) so you have the satisfaction of closing something when it's done ;-).

**Comment by kalkih** [comment]
Now fixed in the latest release, thanks!

**Comment by scstraus** [comment]
No, thank you,  everything is beautiful again!

![image](https://user-images.githubusercontent.com/7644023/72023955-7d6b4a80-3274-11ea-8bae-438e0427b3f7.png)

**Comment by kalkih** [comment]
Great, nice setup! 👍
