### ISSUE TITLE
Custom element doesn't exist: mini-media-player.

### ISSUE THREAD

**Issue by bookandrelease** [kalkih/mini-media-player#211]
Hello,

I've tried all the solutions I've found so far, to no avail. I keep getting this error. I don't know what else to try!

I have this in the raw config editor:

```resources:
  - type: module
    url: /community_plugin/mini-media-player/mini-media-player-bundle.js
  - type: module
    url: /community_plugin/button-card/button-card.js```

I have this in my config.yaml
`
frontend: 
   javascript_version: latest`

I have this in my ui-lovelace.yaml and also tried module instead of js for type:
` 
resources:
  - url: /local/mini-media-player-bundle.js?v=1.5.1
    type: js`

This is in my raw config editor:
`
 entities:
  - entity: media_player.bedroom
    group: true
    hide:
      power: true
      volume: true
    info: short
    source: icon
    type: 'custom:mini-media-player'
  - controls: true
    entity: media_player.my_room_speaker
    group: true
    hide: null
    type: 'custom:mini-media-player'
type: entities
`

Any help is greatly appreciated! Thanks in advance.

Edit: Apparently I can't figure out how to format correctly on this website. Please bear with me. Although my issue doesn't make any note about syntax. 

Edit 2: I was unfamiliar with HACS before this, but I just added it. If anybody is able to point me in a direction to add this that way too that would be fine. I can't find it in the integrations list in HACS.

**Comment by kalkih** [comment]
Hello,

Check [this](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code-and-syntax-highlighting) out for formatting, basically 3 backticks before the code block and three after.

How did you install the card, through HACS or by downloading it manually?
Are you using the HA user interface to add cards e.t.c. or are you using [yaml mode](https://www.home-assistant.io/lovelace/yaml-mode/)?

**Comment by bookandrelease** [comment]
> Hello,
> 
> Check [this](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code-and-syntax-highlighting) out for formatting, basically 3 backticks before the code block and three after.
> 
> How did you install the card, through HACS or by downloading it manually?
> Are you using the HA user interface to add cards e.t.c. or are you using [yaml mode](https://www.home-assistant.io/lovelace/yaml-mode/)?

Thank you!

I don't know how to install through HACS. I added stuff using raw config editor and editing config.yaml.

**Comment by kalkih** [comment]
Okay, so where did you put the `mini-media-player-bundle.js` file from [this step](https://github.com/kalkih/mini-media-player#simple-install)?
I recommend putting it directly in the `www` folder inside your `config` folder, so `config/www/[file goes here]`.

The config folder is where you have your `configuration.yaml`, it doesn't necessary have to be named `config`, I'm just using it for reference.

If you put the file there (`config/www`), the reference in your raw config editor should look like this.
```yaml
resources:
  - url: /local/mini-media-player-bundle.js?v=1.5.1
    type: module
```

You can double check and make sure the file is in the correct place by manually navigating to it's url in your browser. `http://[HA-IP]:[PORT]/local/mini-media-player-bundle.js`, a long line of code should show up.

And you can ignore/forget the `ui-lovelace.yaml` file if you're using the UI editor, it doesn't do anything.

**Comment by bookandrelease** [comment]
I did have it in my `config/www`, so I'm not sure what was going on. However I was able to configure HACS so I added it through there. 

Thank you!

**Comment by kalkih** [comment]
Great! 👍
