### ISSUE TITLE
Allow removing current player from speaker_group 

### ISSUE THREAD

**Issue by jjlawren** [kalkih/mini-media-player#213]
I'm unsure if this applies to all groupable players, but I'm using Sonos speakers. The current functionality doesn't allow to remove the 'master' from a `speaker_group`, yet this is possible via the `sonos.unjoin` service. Would it be possible to remove this restriction?

**Comment by kalkih** [comment]
Hello,
I opted to restrict this since I am unsure if all current and future supported platforms can handle removing the master from an existing group, this would require the component/platform to automatically reassign a new master e.t.c.

Right now you can only "ungroup" if you wish to leave with the master right?

This is something we possibly could change, what happens when you do a service call and unjoin with the master? Will a new master be assigned and the playback continue?

**Comment by jjlawren** [comment]
I can only comment for Sonos. The master is removed from the group and stops playing. The remaining speakers automatically choose a new master and playback continues on those uninterrupted.

**Comment by kalkih** [comment]
Alright, thanks for the info!

**Comment by kalkih** [comment]
In the next release there will be a "leave" button which you can use if you wish to leave the group with the master.

![Screenshot 2020-01-14 at 20 02 30](https://user-images.githubusercontent.com/457678/72373985-b179bc00-3709-11ea-8f63-fdb4e46ca2dd.png)

**Comment by jjlawren** [comment]
@kalkih do you have a plan to publish a new release soon?

**Comment by kalkih** [comment]
Sure, thanks for reminding me, will do a new release tonight.

**Comment by kalkih** [comment]
New release out! Thanks!

**Comment by jjlawren** [comment]
@kalkih I've upgraded but the button does not show for my grouped Sonos speakers. I've tested on multiple apps/browsers to ensure it wasn't a cache issue.

**Comment by kalkih** [comment]
Are you running HACS?
I've had several (10+) users reporting issues with updating card through HACS at the moment, HACS will show that the latest version is installed but that is not always true.
Probably related to https://github.com/hacs/integration/issues/944.
Please try restarting HA, installing the card manually.

**Comment by jjlawren** [comment]
Yep, that was it. Luckily, just choosing the HACS 'reinstall' option fixed it without needing to restart or manually intervene.

Sorry for the false alarm, new feature works great!

**Comment by kalkih** [comment]
Awesome, Thanks for the feedback!
