### ISSUE TITLE
Conditional shortcuts

### ISSUE THREAD

**Issue by jjlawren** [kalkih/mini-media-player#214]
It would be nice to have conditionally displayed shortcuts that are hidden if they're not applicable.

This could also provide a more complete solution to https://github.com/kalkih/mini-media-player/issues/81.

**Comment by kalkih** [comment]
Shortcuts are not a focus in this project, you could try to achieve this with [config-template-card](https://github.com/iantrich/config-template-card). Otherwise I really recommend the custom button card for more advanced use-cases.
Thanks!

**Comment by jjlawren** [comment]
Fair enough, I'll play with those and see if I can get them to do what I'm imagining. Thanks!
