### ISSUE TITLE
Playstation 4 is in "standby" when turned off, which is regarded as active

### ISSUE THREAD

**Issue by fleXible** [kalkih/mini-media-player#218]
Hi,

when my Playstation 4 is turned off, it goes into the state "standby" which is regarded as "idle" by the mini-player and therefor the power-status indicates it is on.

Btw. home-assistant also wrongly regards STATE_STANDBY as "on" in general, which leads to the toggle-feature being broken, because it always tries to turn it off from standby. But turn_off for Playstation maps to standby.

Could you add standby to be regarded as off?

Just read about, #208 and setting `idle_view` seems to fix the indicator issue:
```
idle_view:
    when_standby: true
```
Maybe the docs could mention to set this for Playstation 4?

**Comment by kalkih** [comment]
Hello,
Glad you figured it out.
Yes `standby` is a bit awkward in HA and can mean different things depending on platform and component. That's why I opted for the optional idle view for `standby` and same for `idle`.

Yes, we could probably change the option description to describe the option better.
Feel free to create a PR too the readme if you come up with a better description.

Thanks!

**Comment by fleXible** [comment]
Hi,
I will have a look into it and see what I can come up with. But still there remains the broken standby-toggle function, though I think this has to be fixed in HA.

**Comment by rcavezzale** [comment]
Hi,
I have the same issue, when try to turn on the PS4 with the "power" button from mini media player not work.
for the moment I use ps4-waker like a switch in HA.
I hope that this issue will be solved as soon as possible

**Comment by kalkih** [comment]
Hello,
IMHO that's more of an issue with the playstation component than the card itself.
The card simply calls `media_player.toggle`, the component is responsible to handle the request correctly.
You could try creating a [universal media player](https://www.home-assistant.io/integrations/universal/) and override the default handling of the power/state.

**Comment by fleXible** [comment]
You are right, the root cause is the usage of a newly introduced state [STATE_STANDBY](https://github.com/home-assistant/home-assistant/blob/9e7185c676a19906248d46d8ea3ffb65fa23a3f9/homeassistant/components/ps4/media_player.py#L225) instead of the usual STATE_OFF, when the device is off.

I'll open an issue with home assistant, thanks.
