### ISSUE TITLE
Shuffle

### ISSUE THREAD

**Issue by gieljnssns** [kalkih/mini-media-player#22]
Is it possible to show a shuffle button?

**Comment by kalkih** [comment]
Great idea, I will add this as an optional feature in a future release.

However it would only work for players that has shuffle supported in the backend ([supported](https://github.com/home-assistant/home-assistant/search?q=SUPPORT_SHUFFLE_SET&unscoped_q=SUPPORT_SHUFFLE_SET)).

**Comment by kalkih** [comment]
`show_shuffle` now available in [v0.8.9](https://github.com/kalkih/mini-media-player/releases/tag/v0.8.9)

- Added: `show_shuffle` option, to display a shuffle button

  <img src="https://user-images.githubusercontent.com/457678/47924787-ddba6b80-debc-11e8-9398-602fc80cc230.png" width="500" alt="v0.8.9 example 1" />
