### ISSUE TITLE
Is there a way to see what show is playing inside an app?

### ISSUE THREAD

**Issue by MysticNynja** [kalkih/mini-media-player#220]
So I have this card: 
type: horizontal-stack
cards:
  - entity: media_player.living_room
    type: 'custom:mini-media-player'
    info: scroll
    artwork: full-cover-fit
    source: full
    hide:
      mute: true
      icon: true
      power_state: false

Is there a way to get what is playing from Netflix and show the artwork?

So if I'm playing Thor: Ragnarok then it should say that with the image on the background instead of just Netflix

I am using a Roku stick and don't see the info as attribute

**Comment by kalkih** [comment]
Unfortunately nothing I can do about it, the HA component has to expose this information in order for the card to display it. I would recommend opening an issue request / feature request in the Home Assistant repo.

Thanks!

**Comment by MysticNynja** [comment]
Thanks!  That's what I thought, just was hoping it was a simple thing I was missing.  I'll try to get a request into HA
