### ISSUE TITLE
Shortcut image doesn't work

### ISSUE THREAD

**Issue by TheRealLouCipher** [kalkih/mini-media-player#223]
Can't get image for shortcut buttons to work. Tried different image sizes with no luck, even 24x24 and 48x48. What am I doing wrong? This is my config:

````
shortcuts:
  columns: 4
  buttons:
    - image: /local/images/rixfm.jpg
      type: playlist
      id: http://fm01-ice.stream.khz.se/fm01_mp3

**Comment by kalkih** [comment]
Should work, double check the image url and make sure it matches the file on disk.
Update the card if you haven't.
If installed with HACS, try reinstalling the card in HACS, HACS won't update card correctly sometimes.

**Comment by TheRealLouCipher** [comment]
Path is correct, reinstalled card, tried different images, images that I use for other cards but it doesn't work. Any other ideas?

**Comment by kalkih** [comment]
Strange, no idea, unless you got an old version of the card I'm not sure why it wouldn't work.

I just tried and works for me and here's a post from another user using it https://community.home-assistant.io/t/lovelace-mini-media-player/68459/1398?u=kalkih.

**Comment by TheRealLouCipher** [comment]
Found the error! I had an old resource url mini-media-player.js instead of mini-media-player-bundle.js. Now It works. Appreciate the help!
