### ISSUE TITLE
Can't update to 1.6.0 - Download was not complete [No content to download]

### ISSUE THREAD

**Issue by Tuumke** [kalkih/mini-media-player#224]
I try to update to 1.6.0, but i keep getting the error below..

2020-02-12 11:39:43 ERROR (MainThread) [hacs.repository.plugin.kalkih.mini-media-player] Download was not complete [No content to download]

I saw that it create a /config/www/community/mini-media-player as user root:root when all other folders are dockers:users

I used a work arround to get HA running as dockers:users. Could remove and install 1.5.2 (after trying a few times to press install, after some time i got the bar to change from install to update.
But error is still the same. Also tried with all files as root:root.. didnt take.,

**Comment by kalkih** [comment]
Hello!

This is an issue with HACS or with GitHub CDN, seems to affect many cards.
Try again in a bit or continue the discussion here https://github.com/hacs/integration/issues/963

Thanks!
