### ISSUE TITLE
Support template processing for background images

### ISSUE THREAD

**Issue by jambuu** [kalkih/mini-media-player#225]
This project is awesome!

I am using lots of internet radios for which I would like to display a coverart. This would be possible if `background` would support template processing:

```
background: >
   {% if is_state("input_select.radio_station", "Klassik Radio - Main") %} 
    '/local/klassik_radio.png' 
   {% else %} 
      ....
   {% endif %}
```
Thanks!

**Comment by kalkih** [comment]
Hello,
Thank you!

Templating is not something I plan to natively support in this card, but thanks to the flexibility of Lovelace you can achieve this with the help of [config-template-card](https://github.com/iantrich/config-template-card).
See this issue for an example: https://github.com/kalkih/mini-media-player/issues/222#issuecomment-585424070.

Thanks!
