### ISSUE TITLE
Sonos: Leave group does not work

### ISSUE THREAD

**Issue by deluxestyle** [kalkih/mini-media-player#226]
If I create a group of some Sonos Speaker only the master can ungroup it again. A single Sonos Player can not leave the group.
It shows following error message:

> must contain at least one of entity_id, area_id.

**Comment by kalkih** [comment]
Strange, I'm pretty sure this used to work? When did you start having this issue or has it always been like that?

**Comment by deluxestyle** [comment]
yes I'm as well quite sure that this already worked.
therefore I'm not sure since when, but I guess somehow since the update of hass.io to 0.105.

**Comment by deluxestyle** [comment]
sorry. I guess it was a cache issue. I installied v 1.5.1 and reinstalled then 1.6.0 again. And now it's working. somehow it was cached

**Comment by kalkih** [comment]
Alright, that's good! 👍
