### ISSUE TITLE
tap_action open url in new tab or window

### ISSUE THREAD

**Issue by monte-monte** [kalkih/mini-media-player#227]
I maybe missing something, but is there any way to open URL not in current tab?
I want to open Volumio page by clicking on a player, but I highly prefer not to lose my opened HA page.

Thanks!

**Comment by kalkih** [comment]
I understand, I don't think it's possible at this moment, I would probably have to add another option parameter for this.

**Comment by zaneclaes** [comment]
I'm using HASS Browser Mod for this, which enables services like `browser_mod.navigate`.
