### ISSUE TITLE
Grouped cards arrow doesn't appear

### ISSUE THREAD

**Issue by sverleysen** [kalkih/mini-media-player#234]
When I'm using the grouped cards the arrow to expand/collapse the members of the group isn't visible on the screen.
The Multiroom player is a google home speaker group.

I have used the same yaml you provided in the wiki, but no success. 
![image](https://user-images.githubusercontent.com/6018080/75455752-000dad80-597a-11ea-9657-a1e85aa03938.png)
![image](https://user-images.githubusercontent.com/6018080/75455793-08fe7f00-597a-11ea-9f94-3caf1f15bda3.png)

```
- type: entities
  entities:
    - type: custom:mini-media-player
      entity: media_player.home_group
      group: true
      source: icon
      info: short
      hide:
        volume: true
        power: true
    - type: custom:mini-media-player
      entity: media_player.kitchen_display
      group: true
      hide:
        controls: true
    - type: custom:mini-media-player
      entity: media_player.bedroom_speaker
      group: true
      hide:
        controls: true
    - type: custom:mini-media-player
      entity: media_player.bathroom_speaker
      group: true
      hide:
        controls: true


Am i doing something wrong? Or is this a bug?

**Comment by kalkih** [comment]
That's not a collapse/expand arrow, there's no such feature in this card, that's the source menu for the upper most card.
