### ISSUE TITLE
Sonos One does not react to power button click

### ISSUE THREAD

**Issue by raoulteeuwen** [kalkih/mini-media-player#242]
I have both a Google Home Mini as well as a Sonos One. The Google Home Mini responds to clicking the power button, the Sonos does not. The card config is identical. I did try "toggle_power: false" for the Sonos to see whether that would change anything. Any idea?

**Comment by kalkih** [comment]
I believe Sonos doesn't support power off, they are considered as standby or idle in HA if I'm not wrong.
I would recommend just hiding the power button as it doesn't do anything.
