### ISSUE TITLE
FEATURE REQUEST: Ability to template media art

### ISSUE THREAD

**Issue by glassbase** [kalkih/mini-media-player#247]
Just an idea...

But for those media_players that do not provide entity_picture - like androidtv, etc... would be cool if we could template media art. Example - Netflix app being used, make media art a Netflix logo, etc.

**Comment by kalkih** [comment]
Hello,
You can template the background option with [config-template-card](https://github.com/iantrich/config-template-card).

**Comment by glassbase** [comment]
Thanks. Will give it a go

**Comment by glassbase** [comment]
Not having any luck using that card... it appears to only allow templating of icon and name.
Reference issue: https://github.com/iantrich/config-template-card/issues/26

**Comment by glassbase** [comment]
Please re-open for future feature request. Dev at config-template-card said I couldn’t use his card for what i was trying to accomplish
Thanks.

**Comment by kalkih** [comment]
Answered in the other issue
