### ISSUE TITLE
Broken on iOS 11

### ISSUE THREAD

**Issue by quthla** [kalkih/mini-media-player#25]
https://github.com/kalkih/mini-media-player/commit/8b43ec28e63525cf2634fb63a264bbe715fbb69a

This commit broke it. Just showing custom element doesn't exist. Most likely spread operator not supported on iOS Safari (yet).

**Comment by quthla** [comment]
Reverted use of spread operator and now even master is working fine again so my assumption was right.

**Comment by kalkih** [comment]
Alright, I've only been able to test with iOS 12 which worked fine.
Will probably end up reverting back to object assign for now then 😉

**Comment by kalkih** [comment]
@quthla Or if you want to create a PR to the dev branch with the changes you made 😉

**Comment by quthla** [comment]
I saw you "fixe" the formatting of my PR. The signs my editor replaced are C2 A0, which is unicode non breaking space. My editor made these regular spaces. You probably got these spaces in there by accident I guess? Maybe they should be replaced.

**Comment by quthla** [comment]
They're still there I think.

https://github.com/kalkih/mini-media-player/pull/27/commits/14e8659eb3ff1512fa170f8d417f6b4e1a2c78ad

Look at line 300 upwards

**Comment by quthla** [comment]
Or no you're right. They're gone now
