### ISSUE TITLE
websocket thumbnail API deprecated

### ISSUE THREAD

**Issue by manonstreet** [kalkih/mini-media-player#252]
After upgrading Home Assistant to version .107, I now receive the following error in my HA logs:

```
Logger: homeassistant.components.media_player
Source: components/media_player/__init__.py:904
Integration: Media player (documentation, issues)
First occurred: 10:48:48 AM (27 occurrences)
Last logged: 6:04:44 PM

The websocket command media_player_thumbnail is deprecated. Use /api/media_player_proxy instead.
Connection lost. Reconnecting…
```

This is due to the following change:
https://github.com/home-assistant/core/pull/32471

I believe the fetchThumbnail() routine in model.js will need to be updated to use the proxy.

**Comment by kalkih** [comment]
Duplicate #244, #251
