### ISSUE TITLE
Background of Button shortcut

### ISSUE THREAD

**Issue by mendevi** [kalkih/mini-media-player#257]
I'm not sure if you can already do this or not, lol I've tried to change the theming with no luck.

I want to make my button shortcuts have no background, shadow or any defining feature.
 
Except for the icon or text.
I want it to look like the icon for the card, title or power state, simply an icon or text.

Any help would be greatly appreciated and apologizes if this is already a feature that I can't figure out.

**Comment by mendevi** [comment]
Reason for this is so I can build a TV remote, well sort of.
I just want to completely hide the blank button shortcuts.

Having issues uploading a screenshot, but imagine you have a column of 3

blank            |    Up-arrow   |        blank
left-arrow     |        enter      |        right-arrow
blank            | down-arrow  |        blank

and so on with other scripts and buttons

**Comment by kalkih** [comment]
Hello,
See the [theme variables](https://github.com/kalkih/mini-media-player#theme-variables) specifically `mini-media-player-button-color`, you'll still have a slight shadow though.
For more customizeable and more advanced buttons I really recommend checking out the custom button card. Combine a mini-media-player with the option `group: true` and a couple of buttons cards in stacks.

**Comment by mendevi** [comment]
I was thinking of doing just that, but I was digging through your repository and saw the theming options. Just wanted to see if it was possible.
Thank you for the input and quick response.
Wicked nice card
