### ISSUE TITLE
Shuffle playlist possible?

### ISSUE THREAD

**Issue by TheRealLouCipher** [kalkih/mini-media-player#258]
Is it possible to shuffle a playlist? Currently using media shortcut buttons. Config below

````
            shortcuts:
              columns: 2
              buttons:
                - image: /local/images/discoverweekly.jpg
                  type: playlist
                  id: spotify:user:spotify:playlist:37i9dQZEVXcC7bpx7AsNmU
                - image: /local/images/relax.jpg
                  type: playlist
                  id: spotify:user:spotify:playlist:37i9dQZF1DX4Q2SnB3glnP

**Comment by kalkih** [comment]
Hello,
Unfortunately not.
[media_player.play_media
](https://bitbucket.org/jrydenheim/nkt-azeban/pull-requests/82/restore-lost-mixin-code) (which the card utilize) does not support this.
Best solution would be to change the shortcut type to a script or service and call the spotcast service which I believe has support for this.

**Comment by TheRealLouCipher** [comment]
Ok, I understand. I'll look into your suggestions. Thanks for the help.
