### ISSUE TITLE
toggle_power boolean doesn't change function

### ISSUE THREAD

**Issue by Bladeacus** [kalkih/mini-media-player#259]
I have a device that requires media.player_turn_on and media.player_turn_off service calls from Home assistant.  

Media.player_toggle doesn't work so in my lovelace entity button for mini media player I have set  toggle_power to false.

Still seems to be sending a toggle command as my AV device only ever turns on, regardless of whether toggle_power is set to true or false.

Config:
type: 'custom:mini-media-player'
entity: media_player.bedroom_receiver
toggle_power: false

**Comment by kalkih** [comment]
Hello,
The code handling power is very simple.
https://github.com/kalkih/mini-media-player/blob/1cadce3307d49a920e3cc81f2f87c42e8fbd7ba6/src/model.js#L207-L214

What states does your receiver report? I wonder if that could be the issue.

I'll have a look and see if I can replicate it during the weekend.

**Comment by Bladeacus** [comment]
> 
> 
> Hello,
> The code handling power is very simple.
> 
> https://github.com/kalkih/mini-media-player/blob/1cadce3307d49a920e3cc81f2f87c42e8fbd7ba6/src/model.js#L207-L214
> 
> What states does your receiver report? I wonder if that could be the issue.
> 
> I'll have a look and see if I can replicate it during the weekend.

Hi, apologies - you are correct. Seems my entity had a power sensor parameter that was linked to a non exist sensor. Thanks for your response!
