### ISSUE TITLE
Mute and volume icons

### ISSUE THREAD

**Issue by Devqon** [kalkih/mini-media-player#26]
Hi! Awesome card!

Could you replace the volume-up icon? I have a receiver which doesn't support a `set volume` action, so I use the buttons. However, in combination with the `mute` button, it isn't clear which is what because it uses the same icon as the `volume-up` button:
![image](https://user-images.githubusercontent.com/9316480/48131731-635d6300-e291-11e8-8bce-c371661b00f3.png)

Options:
- Use icons `volume-minus` and `volume-plus` for volume buttons (buttons only I guess, not the slider icons)
- Use icon `volume-low` for volume down

**Comment by kalkih** [comment]
Sure, great suggestion.
I think switching to `volume-up` and `volume-down` would be fine.
Will change in next update.

**Comment by Devqon** [comment]
Or maybe a third options, to be consistent with the HA frontend:
![image](https://user-images.githubusercontent.com/9316480/48149575-bb5d8f00-e2bc-11e8-9983-874daf09e21c.png)

**Comment by kalkih** [comment]
I don't really like the default behaviour tbh.
I rather have the mute button display the mute state, instead of disabling the volume buttons while muted.

**Comment by kalkih** [comment]
New icons are now in release [v0.9.2](https://github.com/kalkih/mini-media-player/releases/tag/v0.9.2).
