### ISSUE TITLE
Source images with slider card

### ISSUE THREAD

**Issue by dannymertens** [kalkih/mini-media-player#260]
Hi,

I would like to create a slider card to choose the source, is this possible?

Something like this;

https://community.home-assistant.io/t/lovelace-swiper-card/72447/292?u=dmertens

I can add the sources in a slider card but at the moment I can't find how to enlarge the images and remove the button style

https://dmertens.stackstorage.com/s/FnRMfjkUdGc3lLB

**Comment by kalkih** [comment]
There are better card alternatives if you want to achieve this:
https://www.home-assistant.io/lovelace/picture-entity/
or
https://www.home-assistant.io/lovelace/picture/
or
https://github.com/custom-cards/button-card
