### ISSUE TITLE
SOLVED! Custom element doesn't exist: mini-media-player.

### ISSUE THREAD

**Issue by davanda** [kalkih/mini-media-player#261]
Hello, 
I installed both through HACS and manually but I always have this error:
 "Custom element doesn't exist: mini-media-player."

ui-lovelace.yaml:
(file is under www folder)

resources:
  - url: /local/mini-media-player-bundle.js?v=1.6.0
    type: module

-----

    - type: custom:mini-media-player
      entity: media_player.tv_sala

Where am I wrong?
Thanks

**Comment by CristianTapia** [comment]
Try adding the .js file to: configuration -> lovelace control panel -> resources 
url: /hacsfiles/mini-media-player/mini-media-player-bundle.js

**Comment by davanda** [comment]
Hi, 
The reference is already there, I tried to put it as suggested, without success..

..
- url: /local/community/mini-media-player/mini-media-player-bundle.js
  type: module 
..

Any help? Thank you

**Comment by davanda** [comment]
Solved. 
I deleted everything and I installed via CLI. 
I restarted and now it works.

... if it can serve someone!!
