### ISSUE TITLE
Card not found works / doesn't work

### ISSUE THREAD

**Issue by jbeck22** [kalkih/mini-media-player#263]
So this works, in that it list 2 different Echo devices and what each is playing. It does NOT group them and allow me to play to multiple outputs like the documentation shows.
`type: entities
entities:
  - type: 'custom:mini-media-player'
    entity: media_player.multiroom_player
    group: true
    source: icon
    info: short
  - type: custom:mini-media-player
    name: Dinning Room Echo Dot
    entity: media_player.master_bathroom_echo_dot_old
    group: true
    source: icon
    info: short
    hide:
      controls: true
  - type: custom:mini-media-player
    entity: media_player.kitchen_show
    group: true
    hide:
      controls: true`

![Screen Shot 2020-03-30 at 6 29 33 PM](https://user-images.githubusercontent.com/4844115/77968061-67d65180-72b4-11ea-9e10-bedcac43ced4.png)
![Screen Shot 2020-03-30 at 6 29 43 PM](https://user-images.githubusercontent.com/4844115/77968072-6e64c900-72b4-11ea-8975-b8200679b858.png)

Can anyone help me sort this out?

**Comment by kalkih** [comment]
> It does NOT group them and allow me to play to multiple outputs like the documentation shows.

Where does it say that?

**Comment by jbeck22** [comment]
![Screen Shot 2020-03-31 at 8 47 12 AM](https://user-images.githubusercontent.com/4844115/78027944-38632b80-732c-11ea-9fde-53000cd74e7c.png)

Isn't that what the above screenshot shows?  Maybe I'm interpreting this wrong?

**Comment by kalkih** [comment]
The above image is from a forked-daapd setup, but the example is to showcase the `group` option, as described in the text above the image.

The card does however have a multiroom / speaker group management feature [speaker-group-management](https://github.com/kalkih/mini-media-player#speaker-group-management) but echo is not a supported platform.

**Comment by jbeck22** [comment]
That makes more sense.  Thanks for clarifying
