### ISSUE TITLE
Power button for Yamaha amp zone 2 will not turn off

### ISSUE THREAD

**Issue by tomlut** [kalkih/mini-media-player#264]
I can turn on and off zone 1 no problem but can only turn on zone 2. 

Zone 2 will not turn off using the mini media player power button. I have to bring up the more info pop-up for the device and turn it off there. 

No errors in the log.

```
entities:
  - entity: media_player.lounge_av_rx
    group: true
    icon: 'mdi:audio-video'
    min_volume: 20
    name: Lounge Amp
    style: |
      ha-card {
        border: solid 2px var(--primary-color);
      }
    type: 'custom:mini-media-player'
  - entity: media_player.lounge_av_rx_zone_2
    group: true
    icon: 'mdi:audio-video'
    min_volume: 20
    name: Dining Zone
    style: |
      ha-card {
        border: solid 2px var(--primary-color);
      }
    type: 'custom:mini-media-player'
  - entity: media_player.cinema_av_rx
    group: true
    icon: 'mdi:audio-video'
    min_volume: 20
    name: Cinema Amp
    style: |
      ha-card {
        border: solid 2px var(--primary-color);
      }
    type: 'custom:mini-media-player'
show_header_toggle: false
state_color: true
style: |
  ha-card {
    border: solid 2px var(--primary-color);
  }
title: Amplifiers
type: entities
```

![Screenshot_2020-03-31 Home Assistant](https://user-images.githubusercontent.com/10679300/78055217-a7786880-739c-11ea-8a22-8562ab807f5e.png)

**Comment by kalkih** [comment]
How does that work, are they set up as two individual media players or do you use a universal media player or something?

What state does zone2 report when it doesn't turn off?, could you the card option `toggle_power: false`?

**Comment by tomlut** [comment]
They are discovered as two seperate media players even though they exist in the same physical device.

> What state does zone2 report when it doesn't turn off?
'on'

> could you the card option toggle_power: false?
How would I control the power then?

**Comment by kalkih** [comment]
Good, strange though, could possibly be that zone2 doesn't support the media_player.toggle service.

**Comment by tomlut** [comment]
Possibly. I'll have a play with the service when it's not 2am, like it is now. 

It might mean the Yamaha component needs a fix.
