### ISSUE TITLE
Feature request airfoil support 

### ISSUE THREAD

**Issue by mattgraham84** [kalkih/mini-media-player#266]
Would it be possible to add airfoil running on a Mac  to compatible speaker groups ? 
Links below 
[Airfoil website ](https://rogueamoeba.com/airfoil/mac/) 

[Scripting](https://rogueamoeba.com/support/knowledgebase/?showArticle=AirfoilAppleScript)

**Comment by kalkih** [comment]
No, not unless the integration is added to Home Assistant, this card is simply a frontend.
