### ISSUE TITLE
TTS to Speaker Group

### ISSUE THREAD

**Issue by Royal2000H** [kalkih/mini-media-player#268]
Hello,

The current implementation of tts allows you to not list the entity which grabs the current entity or it allows you to list any number of entities including groups. But this is static.

Separately, the media card also lets you manage speaker groups (such as sonos). If I am currently managing a speaker group with a few speakers selected, would it be possible for the card to pass on the entities of the selected speakers to tts? Thereby sending tts to all the speakers currently playing the media.

Peripherally related - The text on the cards is light colored when cover art is on, including the placeholder text for tts. But when you click into the tts textbox, the text you are typing is black which is impossible to see on dark backgrounds. Can the css for this be fixed please?

**Comment by kalkih** [comment]
Sure, I'll make this optional, not sure if it should be enabled by default or not...

The tts text color should be fixed with #271
