### ISSUE TITLE
Entered TTS text not visible in card

### ISSUE THREAD

**Issue by kersten-lohmeyer** [kalkih/mini-media-player#270]
Hi,

the entered TTS text is almost not visible. See attachment. Or am I missing something?

Regards
![hassio_card](https://user-images.githubusercontent.com/61520094/78469362-b6567680-7720-11ea-8b3d-a0bff5bfe066.png)

**Comment by kersten-lohmeyer** [comment]
Also the placeholder string is translated into German, but the "button" (SEND) text is not.

**Comment by kalkih** [comment]
Alright, probably broke with a recent HA update, will fix!
Regarding the text translation: There's no translation suitable for the send button in HA, that's why it's "hard coded".
