### ISSUE TITLE
Artwork displays screen contents and refreshes every 5-10 seconds

### ISSUE THREAD

**Issue by darkknightjs24** [kalkih/mini-media-player#277]
I have the androidtv integration set up with my NVidia Shield. I have been using your custom card with this integration for over one month now and everything was working as usual.

However, today (after the new home assistant update), the artwork displayed on the card is literally what is displayed on my TV screen. For example, if a movie is playing, the movie's cover art is not what is displayed, but what is actually happening in the movie at the time the card refreshes. This updates every 5-10 seconds.

**Comment by kalkih** [comment]
Interesting, how is the default lovelace media card displaying the artwork?

**Comment by darkknightjs24** [comment]
Sorry about that - I only use your card for my media players and not the default one but it seems the default lovelace media card also displays the same behavior. So I suppose the issue lies with the androidtv integration itself then because none of my other media_player entities have this issue.

**Comment by darkknightjs24** [comment]
I have posted my issue on the home assistant core and from the replies it seems this a new feature. I will close this issue.
