### ISSUE TITLE
Failed to load the Add on since yesterday 

### ISSUE THREAD

**Issue by Geraldf** [kalkih/mini-media-player#279]
Hi, since yesterday the add-on failed to load. Lookin into the browser, I can see the following error message.
`Failed to load module script: The server responded with a non-JavaScript MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.`

I guess HASS got updated, and this is breaking something.

**Comment by kalkih** [comment]
Interesting, are you on HA 1.107.0?
