### ISSUE TITLE
Stop icon from changing to the source action

### ISSUE THREAD

**Issue by iptvcld** [kalkih/mini-media-player#281]
When Netflix is played, the icon changes as well. Option to not change the default MDI.

**Comment by kalkih** [comment]
Please elaborate, what icon?

**Comment by iptvcld** [comment]
This is the icon that shows where the MDI icon is. When the tv is off, it shows whatever MDI icon I have set. And when I turn on the tv and put on let's say Netflix, it changes that icon to the input that's playing on tv

**Comment by kalkih** [comment]
I think the option `artwork: none` should do what you want.

**Comment by iptvcld** [comment]
thanks that worked!
