### ISSUE TITLE
Problem with my sonos aftter upgrading to version 0.108.x

### ISSUE THREAD

**Issue by 03397** [kalkih/mini-media-player#285]
After the upgrade to home assistant version 0.108.x I started getting random messages about my sonos entity, related with the recorder.

I do not know if the mini media player is causing these errors but as far as I know in version 0.108.x Sonos entities playing radio streams used to cram the radio name, the artist and the song name into two attributes.

I have opened a ticket to the home assistant git but I am not sure what is causing this.
Event is not JSON serializable: <Event state_changed[L]: entity_id=media_player.sonos_one, old_state=<state media_player.sonos_one=paused; source_list=['89.0 KISS FM | (Adult Hits)', 'Anastacia Greatest hits', 'Angela Classics', 'Angela Favourite', 'Kanali 98.6 (Greek Music)', 'Klik FM 105.5 (Adult Hits)', 'Love fm Cyprus', 'Nicolas Christmas', 'Nicolas Classics', 'Nicolas Greek', 'Nicolas Kenny G', 'Nicolas Laika', 'Super FM 104.8 | (European Music)', 'Super Sport FM 104.0 (Sports Talk & News)'], volume_level=0.35, is_volume_muted=False, media_content_id=x-sonosapi-stream:s73578?sid=254&flags=8224&sn=0, media_content_type=music, media_title=Klik FM, source=Klik FM 105.5 (Adult Hits), shuffle=False, sonos_group=['media_player.sonos_one'], friendly_name=Sonos One, entity_picture=/api/media_player_proxy/media_player.sonos_one?token=9d8f9d145f91289e85980c1d132435e4b898033b4ac68f62ff41e2036c102c90&cache=f7b4267caf71048e, supported_features=64063 @ 2020-04-14T15:04:04.528963+03:00>, new_state=<state media_player.sonos_one=paused; source_list=['89.0 KISS FM | (Adult Hits)', 'Anastacia Greatest hits', 'Angela Classics', 'Angela Favourite', 'Kanali 98.6 (Greek Music)', 'Klik FM 105.5 (Adult Hits)', 'Love fm Cyprus', 'Nicolas Christmas', 'Nicolas Classics', 'Nicolas Greek', 'Nicolas Kenny G', 'Nicolas Laika', 'Super FM 104.8 | (European Music)', 'Super Sport FM 104.0 (Sports Talk & News)'], volume_level=0.35, is_volume_muted=False, media_content_id=x-sonosapi-stream:s73578?sid=254&flags=8224&sn=0, media_content_type=music, media_title=<built-in method title of str object at 0xb6761960>, source=Klik FM 105.5 (Adult Hits), shuffle=False, sonos_group=['media_player.sonos_one'], friendly_name=Sonos One, supported_features=64063 @ 2020-04-14T15:04:04.528963+03:00>>
5:33:03 PM – recorder (WARNING) - message first occurred at 5:32:48 PM and shows up 2 times
State is not JSON serializable: <state media_player.sonos_one=paused; source_list=['89.0 KISS FM | (Adult Hits)', 'Anastacia Greatest hits', 'Angela Classics', 'Angela Favourite', 'Kanali 98.6 (Greek Music)', 'Klik FM 105.5 (Adult Hits)', 'Love fm Cyprus', 'Nicolas Christmas', 'Nicolas Classics', 'Nicolas Greek', 'Nicolas Kenny G', 'Nicolas Laika', 'Super FM 104.8 | (European Music)', 'Super Sport FM 104.0 (Sports Talk & News)'], volume_level=0.35, is_volume_muted=False, media_content_id=x-sonosapi-stream:s73578?sid=254&flags=8224&sn=0, media_content_type=music, media_title=<built-in method title of str object at 0xb6761960>, source=Klik FM 105.5 (Adult Hits), shuffle=False, sonos_group=['media_player.sonos_one'], friendly_name=Sonos One, supported_features=64063 @ 2020-04-14T15:04:04.528963+03:00>

**Comment by kalkih** [comment]
Hello, this is unrelated to this card, it's a backend issue so the home assistant repo is the right place to continue this 👍
