### ISSUE TITLE
Media_player_thumbnail is deprecated

### ISSUE THREAD

**Issue by Aiace88** [kalkih/mini-media-player#286]
hello, for some time when I use the mini media player in the logs it fills up with:

**[homeassistant.components.media_player] The websocket command media_player_thumbnail is deprecated. Use /api/media_player_proxy instead.**

I'm not sure if it's a problem to report here, in the negative I apologize for posting.
can you help me?
thank you

**Comment by kalkih** [comment]
Hello!
This has been addressed in the latest release of this card, update the card and you should no longer get these messages, unless the error originates from another integration.
See https://github.com/kalkih/mini-media-player/pull/253
