### ISSUE TITLE
Support for Kodi

### ISSUE THREAD

**Issue by Shogun1978** [kalkih/mini-media-player#287]
As I tried to trigger actions in Kodi with the mini-media-player - which btw worked great - I would like to see a tighter integration with Kodi. What I actually did is to configure buttons which call a service a switch to a favorite channel. The same I did for the logitech media server (squeezebox). Would be e.g. great to see for Kodi what is actually playing.

**Comment by kalkih** [comment]
Hello,
I'm trying to not implement platform specific features into this card as it would lead to the card getting huge and bloated with logic that only is relevant to a small percentage of users.

If Kodi doesn't expose media information (what's playing) or other standard media player features I suggest opening a feature request in the official HA repo, as long as it's implemented using the media player standard it would then show up in the card.
