### ISSUE TITLE
Custom element doesn't exist when using Fire Tablet

### ISSUE THREAD

**Issue by ccmacaluso** [kalkih/mini-media-player#29]
Using FullyKiosk on a Fire Tablet with latest Fire OS causes the error "Custom element doesn't exist: mini-media-player. This is due to an outdated Android WebView (version 59 instead of version 70) on Fire OS. Every other custom card I use in Lovelace appears to load without an issue, so I wonder if there is some way to "correct" this one to avoid this error. Unfortunately I am forced to use a dashboard without this card on my tablets until this is corrected.

**Comment by kalkih** [comment]
Yes, I'm aware of this, the latest version you should be able to run is [v0.4.1](https://github.com/kalkih/mini-media-player/releases/tag/v0.4.1).

However, if you could try this [code](https://gist.githubusercontent.com/kalkih/36952ef452a3a8b6fb0587f9376f4dbe/raw/030b982170bc76cfe18f9ad4ad970a6f24026792/mini-media-player-bundle.js). This is the latest version compiled through babel, which could potentially resolve the compatibility issues.

* Save the raw code as `mini-media-player-bundle.js` (click  [this](https://gist.githubusercontent.com/kalkih/36952ef452a3a8b6fb0587f9376f4dbe/raw/030b982170bc76cfe18f9ad4ad970a6f24026792/mini-media-player-bundle.js)  -> press ctrl+s -> save)
* Put the file inside your `config/www` directory
* Add a reference in your `ui-lovelace.yaml` (replace existing mini-media-player reference if you already got one)
  ```yams
  resources:
    - url: /local/mini-media-player-bundle.js?v=0.9.3-beta
      type: js
  ```

Let me know the results 😄

**Comment by ccmacaluso** [comment]
Thanks for your reply. I followed the directions using your latest version and the same error, unfortunately, still appears in Fully Kiosk on the Fire Tablet. I am going to try rolling back to v0.4.1 to see if that gets rid of the error and then maybe we can talk about why this incompatible with the older WebView version. I also found a problem with a second custom card, not just yours, so this isn't the only one with a problem. That second card with an issue is the surveillance card.

**Comment by ccmacaluso** [comment]
So even v0.4.1 didn't resolve the error. I appreciate your help trying to resolve this, though!

**Comment by ccmacaluso** [comment]
I was able to resolve the problem but it's pretty strange. I noticed that the two cards causing errors on the Fire tablets were the only two using type: module instead of type: js in ui-lovelace.yaml. I changed the mini-media-player-bundle.js reference to type: js and everything works as expected now. 

I am going to issue a bug report on the HomeAssistant repository for the Lovelace front end. 

Also, I did find a small visual bug on mini media player but I will close this bug report and open up a different ticket to report it.

**Comment by kalkih** [comment]
Awesome!
Which bundle version did you use when you got it working?
The one I linked in above?
The reason you had to change to `type: js` is probably because ES modules isn't supported in the web view version running on your tablet so it's most likely not a bug in HA.

**Comment by ccmacaluso** [comment]
I used the latest version and it worked.
