### ISSUE TITLE
[FR] Google home speaker groups

### ISSUE THREAD

**Issue by xPhantomNL** [kalkih/mini-media-player#292]
Within the Google Home app it is possible to setup multiroom audio (speaker groups) with Google Home / Google Nest devices. It would be great if this card / add-on's built in speaker group management would also be able to support the Google platform.

**Comment by marcovanree** [comment]
+1 for google home :)

**Comment by mbrihed** [comment]
+1
Would even like to have it for Alexa devices.

**Comment by kalkih** [comment]
Hello,
Yes indeed this would be very nice, am a big user of GH speaker groups myself.
Unfortunately this isn't possible, the necessary services isn't exposed publicly, afaik there's no way of managing speaker groups outside of the GH app.
If this changes in the future I would be more than happy to look at implementing this.
Thanks!

**Comment by 1ntroduc3** [comment]
This would make a perfect addition yes! Is this a possibility?

**Comment by sycx2** [comment]
There is a new function in the Google Home app. Guess we have to wait if they expose the API. It seems to behave like sonos grouping where you can select and deselect devices.

**Comment by craigmcgowan** [comment]
I would absolutely love this function. It would make the card complete for me.
