### ISSUE TITLE
Play icon not changing into pause when playing

### ISSUE THREAD

**Issue by pabsi** [kalkih/mini-media-player#293]
First things first: Thank you for this incredible custom card!! I love it and actually use it for 3 different type of media devices. Beautiful and so flexible! :clap: 

The problem I am having on one of them (my TV) is that when playing media, the "play" icon/button does not change into a "pause" or "play/pause" icon/button.

If I open the device for in the "more-info" mode or popup, I do see this icon (play/pause one).

the functionality, however, is correct: when playing, even the icon being "play", if I press/click it it pauses the stream. So I guess it's just the icon what's wrong.

EDIT: with kodi, it changes correctly. It seems to be my TV while playing content via Netflix or an app only... :thinking: 

Best regards,

**Comment by kalkih** [comment]
Hello, sorry for the late reply.
Thank you, glad you find it useful 🎉 

Yes, you are right in your observation, some media platforms/sources doesn't support play/pause state, as a result there's no way for the card to know what state to display, not much I can do about it unfortunately, a bug report in the core HA repository about the media player component would be the way to proceed with this imo.

Thanks!
