### ISSUE TITLE
Airplay metadata in media-player

### ISSUE THREAD

**Issue by GlebOlden** [kalkih/mini-media-player#294]
Hello! I have a mini-media-player installed to manage multiple music zones in the house. I stream music from my iPhone to shairport-sync. Shairport gets a file with metadata (Album Name, Artist Name, Cover Art) . However, the Home Assistant mini-media-player interface does not display this data. Is it possible to display it in the player somehow?

Description of Shairport-sync metadata: [https://github.com/mikebrady/shairport-sync-metadata-reader](https://github.com/mikebrady/shairport-sync-metadata-reader)

Example of my interface:
![IMG_5543](https://user-images.githubusercontent.com/44943930/80507263-59e12280-897f-11ea-8321-b2e68412a4a2.PNG)

**Comment by kalkih** [comment]
Hello,
Nothing I can do from the card unfortunately.
This would have to be implemented in the backend component in HA, what media player component are you using? I would suggest creating a feature request in the core HA repository for this.

**Comment by GlebOlden** [comment]
At the moment I have implemented this solution:
[https://community.home-assistant.io/t/simple-multiroom-with-home-assistant/193788](https://community.home-assistant.io/t/simple-multiroom-with-home-assistant/193788)
