### ISSUE TITLE
Bluesound Join service

### ISSUE THREAD

**Issue by km2000us** [kalkih/mini-media-player#296]
Hi

I am unable to get my bluesound units to be joined using the group speaker settings.  The error that keeps flashing on the bottom of my homeassistant screen says:

"Failed to call service media_player/bluesound_JOIN. Unable to find service media_player/bluesound_JOIN"

Is this because the actual name of the service is bluesound.JOIN (ie. a period rather than an underscore)?

**Comment by kalkih** [comment]
Hello,
Yes, I can see that the bluesound component now implements those services under its own domain, will fix.
