### ISSUE TITLE
Icons in Home Assistant 0.110

### ISSUE THREAD

**Issue by bramkragten** [kalkih/mini-media-player#297]
In Home Assistant 0.110 the way icons are loaded is changed. This means the `paper-icon-button` that is used in this element will no longer show the correct icon. You can use `ha-icon-button` that uses `mwc-icon-button` underneath as a replacement.

**Comment by kalkih** [comment]
Thanks for the heads up @bramkragten 👍🏼

**Comment by nikiyao** [comment]
Came in here to say this

**Comment by nikiyao** [comment]
Is there something I need to do on my end? because I updated and I'm still not seeing the icons on my buttons

**Comment by kalkih** [comment]
Try reloading resources, clearing cache e.t.c.
