### ISSUE TITLE
Next Track arrow is partially hidden when card is shrunken in width.

### ISSUE THREAD

**Issue by ccmacaluso** [kalkih/mini-media-player#30]
If I shrink my browser width down small enough, I can completely hide the right Next Track arrow. 

![image](https://user-images.githubusercontent.com/25406438/48381275-d22b2980-e6a0-11e8-8ffb-cbae9ece4170.png)

![image](https://user-images.githubusercontent.com/25406438/48381290-e2430900-e6a0-11e8-9b8e-94f4e12a3145.png)

![image](https://user-images.githubusercontent.com/25406438/48381256-c17ab380-e6a0-11e8-97e1-367467b68b1d.png)

**Comment by kalkih** [comment]
Yes, this is mostly a problem when there's two or more narrow columns, since the media queries only trigger based on the browsers full width and not the column width (which would have been better).

I'll make some improvement to resolve this.

**Comment by kalkih** [comment]
Should be better with these changes, will be included in the next version.

<img width="218" alt="screenshot 2018-11-13 at 22 25 05" src="https://user-images.githubusercontent.com/457678/48444488-5b6f5880-e794-11e8-921a-8ac00af0b306.png">

Thanks!

**Comment by ccmacaluso** [comment]
Thank you!
