### ISSUE TITLE
Feature Request - Use of "input_select"

### ISSUE THREAD

**Issue by mbrihed** [kalkih/mini-media-player#300]
Hi!
Thanks for a great plug-in!!
I would like to propose a new feature request. I use this in combination from using an input_select that contains radio stations from TuneIn. I have Bose SoundTouch, Alexa and Google cast speakers.

Today I have to create separate cards, one for the player, one for the input_select where I can choose the radio station and one that choose the speaker. When selection a speaker or a channel it has a node-red flow that does the magic in the back-ground.
It would be great to be able to use the "shortcuts - list" feature to add a "input_select" drop-down list to be able to select the radio station.

Second, It would be super nice to have a feature that hides all speakers apart from a maybe a main speaker and then shows the player/players that are active with the artwork.

**Comment by kalkih** [comment]
Hello!
Can't you achieve the same thing with the current shortcut list feature?
If you don't want to modify your automation flow I would suggest the following:
You should be able to create shortcuts that calls the service to set the input_select options see [services](https://www.home-assistant.io/integrations/input_select/#services).



> Second, It would be super nice to have a feature that hides all speakers apart from a maybe a main speaker and then shows the player/players that are active with the artwork.

This is outside of the scope of the card, the card does only have control of itself, check out conditional cards, they should work fine for this.

**Comment by mbrihed** [comment]
Thanks a million for the response. I have been trying your recommendation and since I am quite new to HA I guess I cant get my head around how to get it working:

cards:
  - type: 'custom:mini-media-player'
    entity: media_player.basement_dot
    style: |
      :host {
        --paper-item-icon-color: white;
        }
      ha-card {
        font-variant: small-caps;
      }
    name: Basement Alexa
    tts: true
    icon: 'mdi:speaker'
    hide:
      source: true
    shortcuts:
      label: TuneIn Radio
      columns: 2
      list:
        - name: null
          type: service
          id: input_select.select_option
          data:
            entity_id: input_select.alexa_tunein_station


What it shows me is the drop-down with the label "TuneIn". There is however nothing in the drop-down.

**Comment by kalkih** [comment]
Try setting name to something else than null.
Please post the code inside a code block it's hard to tell if indentation is a problem otherwise.
