### ISSUE TITLE
Card not found in Lovelace UI after installation

### ISSUE THREAD

**Issue by boardwarp** [kalkih/mini-media-player#303]
After following the installation steps I can't seem to find the mini player card in the LovelaceUI card picker. This is my first time installing a custom module, but after having trouble I tried the slider-entity-row plugin which seemed to work fine. When I check Config > Lovelace > Resources the mini-media-player resource is there, so it definitely seems like the installation was successful.

If I try adding the card config via the code editor, it looks like this:

![image](https://user-images.githubusercontent.com/10472218/82338977-dae88280-9a30-11ea-932c-c6eb9000706f.png)

Any ideas where I'm going wrong?

**Comment by jes1417** [comment]
It won't show up in the picker, and you need to remove the -bundle from type.

**Comment by boardwarp** [comment]
I had also tried it without the -bundle, but the issue was also the dash and indentation. Removed those and it worked, thanks for the fast response :)
