### ISSUE TITLE
Use whole artwork. 

### ISSUE THREAD

**Issue by gieljnssns** [kalkih/mini-media-player#31]
Can you make an option to adjust the card size to the artwork?

**Comment by kalkih** [comment]
Could be a great addition, possibly adding this in the future.
Thanks for the suggestion.

**Comment by kalkih** [comment]
Here's some progress on this:

<img width="514" alt="screenshot 2018-11-15 at 21 03 23" src="https://user-images.githubusercontent.com/457678/48579280-4cb3ad80-e91c-11e8-8ebf-db7b20115389.png">

**Comment by gieljnssns** [comment]
Nice job 🤘🏻

**Comment by kalkih** [comment]
Now available in [v0.9.3](https://github.com/kalkih/mini-media-player/releases/tag/v0.9.3), with configuration `artwork: full-cover`.
