### ISSUE TITLE
Now abruptly clears the image then loads the new one when cover art is changed

### ISSUE THREAD

**Issue by i00** [kalkih/mini-media-player#321]
When the art used to change there used to be no "gap"; now when the art updates it flicks to grey while the new art loads and then appears sometime later.

**Comment by kalkih** [comment]
Strange, not sure if this broke with HA 0.110.0, no related code has been touched in a while.

**Comment by i00** [comment]
I am not 100% sure if it did or not TBH ... I didn't think it did ... but I haven't used your control for live media updating for a while.

**Comment by Devqon** [comment]
I have the same issue, there is no cover for about 1 second in between

**Comment by stjones-dev** [comment]
This is the same issue I see with Fire TV and this media_player. Static covers are fine with Sonos for example, but changes cause the cover to disappear often more than it appears in the case of a changing live tv cover.

**Comment by stjones-dev** [comment]
Will a new release be coming soon?

**Comment by kalkih** [comment]
New release now available.
