### ISSUE TITLE
Always-on option

### ISSUE THREAD

**Issue by Kedryn** [kalkih/mini-media-player#322]
For those, like me, that don't have a way to know if a device is on or off, it will be usefull to have an "always on" mini media player, that does not hide controls when you press the power button.

**Comment by kalkih** [comment]
Hello, you should be able to achieve that by creating a [universal media player](https://www.home-assistant.io/integrations/universal/)  and "overriding" the state attribute to always be always on, then use that newly created entity in the card.

Should also be possible when/if this gets merged https://github.com/kalkih/mini-media-player/pull/248/ Where you then should be able to override the state in the card directly.
