### ISSUE TITLE
Control multiple speakers

### ISSUE THREAD

**Issue by Ulrar** [kalkih/mini-media-player#327]
Hi,

Is there a way to show multiple speakers (multiple media player entities) in the same card, instead of having to use a stack in card to list them independently ?
The issue with stacking multiple card is that the artwork only shows up on the first one, which looks pretty bad. It would be great to be able to have all the speakers in the same card and have the artwork span over the whole thing.

For context I'm using forked-daapd with multiple chromecast speakers playing the same feed.

Thanks

**Comment by kalkih** [comment]
Hello,

Controlling multiple entities is a path I don't want to take with this card.

Good thing lovelace is so customizeable, I think you could achieve this with the help of [config-template-card](https://github.com/iantrich/config-template-card) and a picture-element. use config-template-card to template the background.
I'm sure there are easier/better ways of solving it but that's the first idea that popped into my head.
