### ISSUE TITLE
Artwork option like in the lovelace-media player card

### ISSUE THREAD

**Issue by nibblerrick** [kalkih/mini-media-player#333]
Hi,

thanks for your card, I'm using it quite some time now and really enjoy it. However I am wondering if it may be possible to have an option for the artwork like in the default card. I hope I haven't overseen this featurerequest in the issues. With full-cover the card becomes somewhat large, with no cover the artwork is a bit tiny. With cover it looks like this and is very cropped:
![chrome_2020-06-11_09-27-55](https://user-images.githubusercontent.com/20553366/84358136-fe819180-abc6-11ea-802c-65a5240a0609.png)
The original lovelacecard (which lacks many features... :-) ) the artworkstyle looks like this:
![chrome_2020-06-11_09-28-07](https://user-images.githubusercontent.com/20553366/84358922-2a514700-abc8-11ea-9334-3ca873cba367.png)
I think that's a nice way to show the full cover as large as possible without being too big.
What do you think?
If this has been considered in the past and won't happen feel free to close the isse.

Thanks

  Nico

**Comment by kalkih** [comment]
Hello,
Indeed, the default card is looking great with the fresh update, great work @zsarnett!

@SBado has already started working on adding this kind of artwork option to the card with some great progress, see here https://github.com/kalkih/mini-media-player/pull/331.

Hope you are ok with us borrowing the design @zsarnett, otherwise let me know.

**Comment by nibblerrick** [comment]
I looked through the issues but have missed to look at the PRs. Looks very good, as it is of course exactly that I thought of. Thanks @SBado!
Should this issue be closed therefore now or remain open till that PR is merged for informational purpose?

**Comment by kalkih** [comment]
Let's keep it open until the PR is complete and merged 🙂

Have a great day.

**Comment by nibblerrick** [comment]
Thanks, same to you!

**Comment by nibblerrick** [comment]
Thanks, looks very good!
