### ISSUE TITLE
Arrow on Source only is too low

### ISSUE THREAD

**Issue by marcmontecalvo** [kalkih/mini-media-player#334]
I'm running on Home Assistant 0.111.0 and Mini Media Player v1.9.1 (installed using HACS)

With a very basic card only showing the source name and the little arrow the arrow is too low:

![image](https://user-images.githubusercontent.com/6583561/84393703-e5c6ab00-abc9-11ea-84cd-b6f938ed20d2.png)

When you click the arrow it jumps up much higher on the control:
![image](https://user-images.githubusercontent.com/6583561/84393781-04c53d00-abca-11ea-9afb-8582b6b38d12.png)

```
entity: media_player.living_room_roku
hide:
  controls: true
  name: true
  icon: true
  info: true
  power: true
  volume: true
type: 'custom:mini-media-player'
```

**Comment by kalkih** [comment]
Hello, this has been fixed with https://github.com/kalkih/mini-media-player/pull/332, will be included in the next release.
