### ISSUE TITLE
HASS - No Plugins / Resources (RPi env)

### ISSUE THREAD

**Issue by ZXant** [kalkih/mini-media-player#335]
After trying to manually install MMP into HASS (vs-0.110.4) running on RPi4, later found that most approaches were outdated, and the new method seems Configuration> Lovelace Dashboards (Advanced)> Resources

![image](https://user-images.githubusercontent.com/53246705/84433148-d95b4600-abfb-11ea-8f9c-d9cd1d20940e.png)

But still, can't see MMP been installed.

Also, HACS doesn't show ANY Plugins, but only Integrations.

Is this another limitation of plain Home Assistant in comparison to HASS.io?

Xant

**Comment by kalkih** [comment]
Hello,
The instructions are not really outdated, but rather missing all together for adding the card through the Home Assistant UI, adding the card in yaml mode is still done as instructed.

Please, feel free to create a PR with additional installation instructions if you feel like it, I'm sure that could be helpful for many (https://github.com/kalkih/mini-media-player/issues/128).

What do you mean you can't see MMP as installed? If the resource was added correctly you should be good to go. You should be able to set up a card by selecting the "blank card" alternative when adding a lovelace card.

As for HACS, I believe plugins are listed under "Frontend" nowadays.

**Comment by ZXant** [comment]
Kalkik

Thank you for your prompt and personal reply.

Im indeed new to HA (and learning in the process), but reasonably Tech skills and an RPi advocate. Think there is a compound mix of information (some dated) for some, like myself, that just started.

1) HACS
Installed Hacs (twice), but NO plugins showed-up. Indeed troublesome, as actually MMD shows in an animated Gif in Hacs GitHub, as Plugin.... but no Plugin can be found... in ANY Tab

2) HACS Tabs
Turned, after days of frustration, Plugins is now called Lovelace... after MANY instructions I went through. Still, NO MMD can be found... even at Hacs Frontend Tab as "Lovelace"

3) Manual
After MANY outdated instructions (MMD GitHub included, and fighting with HA config yaml file), finally found-out that the proper way is to turn-On Advanced feature and Configuration Resources.

Ok... now NO error messages, and MMD "might" be already installed as a Resource. But WHERE? Can not find anywhere....

It's understandable that all confusion lead by dated info, and large "mix of hands" as an OpenSource. Later, when (finally) working, I will be please to wright a proper PR, highlighting ALL difficulties and troublesome.

Best,
Xant
