### ISSUE TITLE
Nest Hub: Custom element doesn't exist

### ISSUE THREAD

**Issue by jeanbart82** [kalkih/mini-media-player#340]
While this component is working on a phone or in a browser, I get a Custom element doesn't exist if I am casting on a Nest Hub.

Resources is set to /mini-media-player/mini-media-player-bundle.js?v=1.9.1 
Type is JavaScript Module

installed with HACS.

using version of Hassio 0.111.1

What can I do?

**Comment by jeanbart82** [comment]
reinstall worked for me

**Comment by jeanbart82** [comment]
closed to early. it seemed to be fixed as I noticed some errors in HACS, bur still it's not working on the Nest hub

**Comment by kalkih** [comment]
Try changing the type to `js`, or try clearing cache, not sure how this is done in Home Assistant Cast though, I've never tried it.

**Comment by Snarky73** [comment]
install w/o HACS 
configuration.yaml
  lovelace:
  mode: yaml
  resources:  
      - url: /local/mini-media-player-bundle.js?v=1.9.1
      type: module
and error "Custom element doesn't exist: mini-media-player."
