### ISSUE TITLE
Width not fixed

### ISSUE THREAD

**Issue by stjones-dev** [kalkih/mini-media-player#342]

**Comment by stjones-dev** [comment]
With a Samsung TV above a Sonos using these media players the layouts are different widths. I'll add a picture when I figure out how. Maybe there are settings I missed?

**Comment by stjones-dev** [comment]
Only apparent when group: true on the sonos

**Comment by kalkih** [comment]
Need your card configuration and a screenshot of the issue

**Comment by stjones-dev** [comment]
artwork: coverentity: media_player.samsung_tv_remoteinfo: shortvolume_stateless: truetype: 'custom:mini-media-player'hide:  progress: trueartwork: coverentity: media_player.kitchengroup: trueinfo: shortspeaker_group:  entities:    - entity_id: media_player.salon      name: Sonos Livingroom    - entity_id: media_player.kitchen      name: Sonos Kitchen    - entity_id: media_player.bedroom      name: Sonos Bedroom  platform: sonos  show_group_count: truevolume_stateless: truetype: 'custom:mini-media-player'hide:  progress: trueartwork: coverentity: media_player.samsung_tv_remoteinfo: shortvolume_stateless: truetype: 'custom:mini-media-player'hide:  progress: trueartwork: coverentity: media_player.kitchengroup: falseinfo: shortspeaker_group:  entities:    - entity_id: media_player.salon      name: Sonos Livingroom    - entity_id: media_player.kitchen      name: Sonos Kitchen    - entity_id: media_player.bedroom      name: Sonos Bedroom  platform: sonos  show_group_count: truevolume_stateless: truetype: 'custom:mini-media-player'hide:  progress: trueChanging group: to false cures it.Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Karl Kihlström <notifications@github.com> Date: 20/06/2020  14:16  (GMT+01:00) To: kalkih/mini-media-player <mini-media-player@noreply.github.com> Cc: stjones-dev <stjones@pt.lu>, Author <author@noreply.github.com> Subject: Re: [kalkih/mini-media-player] Width not fixed (#342) 
Need your card configuration and a screenshot of the issue

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/kalkih/mini-media-player/issues/342#issuecomment-646987259",
"url": "https://github.com/kalkih/mini-media-player/issues/342#issuecomment-646987259",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by stjones-dev** [comment]
I cant get this app to work so will describe...

I have a group set up for Sonos with  3 speakers.

If you set group: true the media player is wider than if you set group:  false. 

When false it's the same width as the TV media player.

**Comment by stjones-dev** [comment]
![Screenshot_20200620-124537_WallPanel](https://user-images.githubusercontent.com/64638804/85203350-7198af80-b30d-11ea-9216-65ec81be39ab.jpg)
![Screenshot_20200620-153558_Chrome](https://user-images.githubusercontent.com/64638804/85203355-7d847180-b30d-11ea-84f5-99ed2c75ca95.jpg)

**Comment by stjones-dev** [comment]
`artwork: cover
entity: media_player.samsung_tv_remote
info: short
volume_stateless: true
type: 'custom:mini-media-player'
hide:
  progress: true


artwork: cover
entity: media_player.kitchen
group: true
info: short
speaker_group:
  entities:
    - entity_id: media_player.salon
      name: Sonos Livingroom
    - entity_id: media_player.kitchen
      name: Sonos Kitchen
    - entity_id: media_player.bedroom
      name: Sonos Bedroom
  platform: sonos
  show_group_count: true
volume_stateless: true
type: 'custom:mini-media-player'
hide:
  progress: true

`

**Comment by stjones-dev** [comment]
I maybe misread the docs for the group parameter? If the behaviour is correct then there is no issue.

I just expected when true that the two players would be aligned.

**Comment by kalkih** [comment]
Yes, this is intentional, it's meant to be used when nesting inside other cards that already have card paddings, to avoid double card paddings, e.g. vertical-stack-in-card, entities card.
