### ISSUE TITLE
What are exact requirements for multiroom support?

### ISSUE THREAD

**Issue by nagyrobi** [kalkih/mini-media-player#343]
Hello,

I work on the integration of [Linkplay](https://github.com/nagyrobi/media_player.linkplay)-enabled audio devices. It's a fork of an older custom component.
It supports multiroom by usage of 2 services `media_player.linkplay_connect_multiroom` and `media_player.linkplay_remove_slaves` and not join/unjoin.
I tried renaming these to join and unjoin, but platform has to be set to `media_player` for the card to recognize them. But anyways, I was still unable to make it work because it's not clear enough for me what are the exact service calls with what parameters that have to be fulfilled in order for the card to be able to handle them.

Can you please advise? HA documentation is completely missing this, I looked at sonos and bluesound and some other components but they are very vague. I don't have nor sonos nor other equipment to test and learn the way they work, all I know how Linkplay needs to operate.
Thanks.

**Comment by nagyrobi** [comment]
what I've discovered so far. Sharing for others: 
- `join` and `unjoin` services have to on global platform. (eg. not `media_player.linkplay_join` but `linkplay.join`) and accept parameters [like this](https://github.com/ppanagiotis/pymusiccast/blob/master/custom_components/musiccast_yamaha/services.yaml)
- media player entities have to have a `master` boolean attribute and a `platform_group` (eg. `linkplay_group`) attribute containing a list with the entity ids present in the multiroom setup, including the masters and the slaves too. This should be the same list for all members in the multiroom, but only one has to have `master` set to `True`
Please feel free to comment if anything important is still needed.

**Comment by kalkih** [comment]
Hello, sorry for the late response.

Yes, you are correct in your findings, there doesn't seem to be any real standard/correct way of implementing speaker grouping / multiroom in Home Assistant yet, but many of the platforms with support has more or less adopted the same implementation, with some exceptions.

The `unjoin` & `join` services should preferably accept a single or an array/list of entity id's

The `master` attribute that's exposed by some platform isn't utlized by this card, but yeah, could be a good idea to include that as well.

Here's an old quote from me (still accurate though).

> In order to function without any modifications to this card the group attribute should look something like this (this is also how the Sonos component does it):
>
> * The group is a list/array.
> * The group contains the entity id's of all of its members.
> * The group looks the same on master and client/slave.
> * The initial entry in the list is the master.
> * The attribute is exposed as[platform]_group (soundtouch_group in this case).

The quote is from [here](https://github.com/kalkih/mini-media-player/issues/155), the discussions there could possibly be of interest for you.
