### ISSUE TITLE
Did anything changes concering the call/naming convention  trough the join/unjoin services for yamaha music_cast?

### ISSUE THREAD

**Issue by jodur** [kalkih/mini-media-player#347]
Did anything changes concering the call/naming convention  trough the join/unjoin services for yamaha music_cast?
I used @hcoohb  modified version for yamaha musiccast and it worked without problems.
After updating to the latest version with HACS, the service calls shows an error.
I still can call the services trough the home-assistant developer tools.

example:

media_player.yamaha_musiccast_join
Service data:
entity_id: media_player.keuken_main
master: media_player.woonkamer_main

_Originally posted by @jodur in https://github.com/kalkih/mini-media-player/pull/102#issuecomment-644223152_

**Comment by kalkih** [comment]
Hello.

Possibly, what services do yamaha_musiccast use? the default is now to call `join/unjoin` on the platform domain and not on the `media_player` domain, but this changed a while ago, almost one year ago https://github.com/kalkih/mini-media-player/pull/161. So would have to add an exception if it works another way.

Can you link the component you're using, it's still not in core HA right?

**Comment by jodur** [comment]
Never realized that the domain has changed and miniplayer uses the new domains. I installed the patch from hacoob almost directly after he released it and never looked back at it. It became a problem after update to the lastest  miniplayer who now is usings the new domain. After installing you component trough hacs and modifing to "musiccast_yamaha" everthing is working again. Thnx!

**Comment by kalkih** [comment]
Perfect 👍
