### ISSUE TITLE
Center sources picker chevron

### ISSUE THREAD

**Issue by agneevX** [kalkih/mini-media-player#350]
Can the chevron be centered (with the text) and only inverted when the drop down is clicked?

Right now, it flops all over the place when clicked...

<img width="207" alt="image" src="https://user-images.githubusercontent.com/19761269/86778274-d119ed80-c077-11ea-864a-8de9e5298795.png">

<img width="207" alt="image" src="https://user-images.githubusercontent.com/19761269/86778379-ec84f880-c077-11ea-9eab-990f71dc1917.png">

**Comment by kalkih** [comment]
This issue has been resolved and will be available in the next release.
#325, #334, #341, https://github.com/kalkih/mini-media-player/pull/332,
