### ISSUE TITLE
Group view broken

### ISSUE THREAD

**Issue by nessor** [kalkih/mini-media-player#351]
Hey guys,

it seems that the group view does not work properly anymore? 

![image](https://user-images.githubusercontent.com/3463261/86888291-37475480-c0fa-11ea-8bc4-b67ab4d846bb.png)

Home Assistant docker v0.112.3
Mini media player v1.9.1 installed via HACS

Actually this should look something like this (as in the Readme)

![image](https://user-images.githubusercontent.com/3463261/86888384-5c3bc780-c0fa-11ea-92bd-e92a1dea1c30.png)

**Comment by kalkih** [comment]
What's the issue? What results are you expecting vs what you get?
Everything looks as it should to me, except that one entity isn't displayed, Are you sure you have a media player named `media_player.multiroom_player`?
