### ISSUE TITLE
Ability to use shortcut list for Sonos Source List

### ISSUE THREAD

**Issue by sw764206** [kalkih/mini-media-player#355]
Hi, 
I am trying to use this card to create a similar spotify playlist "list" that reads from the Sonos Source list. Eample Here> ([https://github.com/custom-cards/spotify-card](url). I cant use that spotify card as it doesnt work with Sonos like this card does. 

Is there a way to set up a shortcut list like this that populates automatically (like the built in source list) rather than specifying the URLs to the playlists which I would have to update everytime?

**Comment by entropie** [comment]
+1

**Comment by kalkih** [comment]
No, this is not possible.
Best bet would be to use something like https://github.com/iantrich/config-template-card.
Not sure how you would go about getting the playlists to populate though, unless they are exposed by the media player in which case it should be easy.
