### ISSUE TITLE
force update of radio icon/graphic

### ISSUE THREAD

**Issue by jdenver13** [kalkih/mini-media-player#357]
Is there a way to force a refresh when changing radio stations. Im using Logitech music server. The artist and track update every time a new track is played but the station id doesn't update the icon/graphic.

**Comment by kalkih** [comment]
I'm not entirely sure what icon/graph you are referring to, but it sounds like a component issue (not related to this card).
Does it work as expected in the default media card or if you check the entity attributes in the developer tools?

**Comment by jdenver13** [comment]
<img width="578" alt="Screenshot 2020-07-22 at 7 27 37 am" src="https://user-images.githubusercontent.com/39801897/88142222-06cce380-cbed-11ea-8fdb-0dc3635bdb55.png">
I do apologise if this is the wrong place, I was referring to the background still showing a old 'LBC' radio station instead of the current station selected 'Magic Soul'

**Comment by kalkih** [comment]
No worries. 
The picture you sent is not of this card, please open an issue in [home-assistant/core](https://github.com/home-assistant/core) instead.
