### ISSUE TITLE
Second row in shortcuts buttons?

### ISSUE THREAD

**Issue by robs23** [kalkih/mini-media-player#358]
How can I make second row in shortcuts buttons? I can see in the example that it's possible, but there's no clue what the syntax does it

**Comment by kalkih** [comment]
Hello, just add more shortcuts and they will automatically wrap to the next line.

Use the [`columns`](https://github.com/kalkih/mini-media-player#shortcuts-object) option to adjust how many buttons each row should consist of before wrapping to the next row.

**Comment by robs23** [comment]
Ok, but what if I want to do irregular column count? Eg. 

- 1st row - 3 columns
- 2nd row -1 column
- 3rd row - 2 columns

I can't duplicate 'columns' expression as it's a bug. If I just say 3 columns and create 6 buttons, I'll get 2 rows of 3 buttons
