### ISSUE TITLE
artwork: full-cover aspect ratio (fit-width?)

### ISSUE THREAD

**Issue by wbilger** [kalkih/mini-media-player#36]
Thanks for the awesome card, the new full-cover option is awesome.
Small, non-critical thing. Would it be possible to add an option to fit the width of the image in the width of the column? Some pictures it shows just part, I'm guessing fitting height. I would not want to have a shorter card, like it does with media-control card, but would want the image shown at top of card. Not super important, just an idea. Thanks.

**Comment by wbilger** [comment]
Instead of cropping/stretching the image, show the 'full' image, so zoom, which could result in letterbox like black line at bottom. If you look at the media-control card, you will see the full image, and it results in a shorter card if the image is say 16x9 resolution. But would be great to see the full picture in your card (sometimes it stretches it, and you can't see much of image), but then keep the square dimension of the card by filling with transparency.
I attached a full-cover.png as it shows up now on my chromecast remote using your card.
To best show what I mean, I attached a full-cover-zoom.png, showing it showing the full picture using media-control card, just to show you what I mean about image. Picture it without the crap on it from the card, but your controls at the bottom where they normally are, over the transparent area. Hopefully that explains it a little better.
Again, not a huge deal, but looks funny with zoomed picture, would be nice to show whole picture and keep square card, so if it's an easy change, would be awesome. Thanks.
![full-cover](https://user-images.githubusercontent.com/2906038/49158789-02093c80-f2f1-11e8-98b4-631d6c759699.png)
![full-cover-zoom](https://user-images.githubusercontent.com/2906038/49158795-05042d00-f2f1-11e8-8e3c-517378a23ec9.png)

**Comment by kalkih** [comment]
Thank you for the clarification.
I see what you mean now and it should be an easy change, but yes, we would end up with black/background coloured bars if the artwork isn't a perfect square.
I'm not sure I would make this the default behaviour but possibly another option parameter, `full-cover-fit` maybe?

I'll look into this later, thanks!

**Comment by wbilger** [comment]
Absolutely, not default, but an option to have it fit would be awesome.
Thanks.

**Comment by kalkih** [comment]
@wbilger 
Here is what it could look like,

First picture is with the card background set to black when the artwork doesn't cover the full square, leaving us with black border kinda like a TV would.

Second picture is with the default card background applied as background.

I kinda like the behaviour of the official media-control card though, resizing the card based on the artwork height, possibly implementing that behaviour in the future.

But for now, what do you think? First one looks better imo.

<img width="487" alt="screenshot 2018-11-28 at 19 39 49" src="https://user-images.githubusercontent.com/457678/49174139-d5cbdb00-f345-11e8-8fb6-2b90fdaa729d.png">
<img width="491" alt="screenshot 2018-11-28 at 19 40 25" src="https://user-images.githubusercontent.com/457678/49174140-d5cbdb00-f345-11e8-8f64-682e01fb20c6.png">

**Comment by wbilger** [comment]
Awesome. I agree, first one looks really good, either would work.
Hopefully you can leave it as an option in the future to resize like the media-control card, as speaking for me, I use your card a lot, and I have certain places like remotes where I want to keep the size the same alwyas or it messes where other buttons are, and also use it other places where resizing would be great as well. 
Great work!

**Comment by kalkih** [comment]
Great,
I got a new release ready soon (today or tomorrow probably), I will include this as `full-cover-fit` for the `artwork` option.

Thanks for your feedback!

**Comment by wbilger** [comment]
Awesome, much appreciated!

**Comment by kalkih** [comment]
Just released [v0.9.5](https://github.com/kalkih/mini-media-player/releases/tag/v0.9.5) with `full-cover-fit` included.
