### ISSUE TITLE
Can we make the icon changeable?

### ISSUE THREAD

**Issue by i00** [kalkih/mini-media-player#361]
This may seem strange; but I would like the icons to have settings allowing me to override them...
I particularly want this for the power button :).

Thanks

**Comment by agneevX** [comment]
Did you read the docs? It's already [there](https://github.com/kalkih/mini-media-player#card-options).

**Comment by kalkih** [comment]
> Did you read the docs? It's already [there](https://github.com/kalkih/mini-media-player#card-options).

The entity icon is configurable yes, but not the button icons.

We unfortunately can't add options for everything (I mean we could but it would make the card bloated and a nightmare to maintain and develop). You are always welcome to fork the card and change it to whatever you like to put your personal spin on it.

Sorry.
