### ISSUE TITLE
UI changes to accomodate 'button' style layouts

### ISSUE THREAD

**Issue by kineticscreen** [kalkih/mini-media-player#368]
Howdy,

Trying to implement a nice 'button' style version of this player, but there doesn't seem to be a way of getting it to look good in both playing and idle states.
I have it looking nice in the playing state:

![Playing](https://user-images.githubusercontent.com/39250334/89249142-cd688f00-d654-11ea-93ec-3d9ea2af32a3.jpg)
![Standby](https://user-images.githubusercontent.com/39250334/89249132-c6418100-d654-11ea-90c8-1294bf0558f7.jpg)

```
entity: media_player.office_speaker
artwork: material
type: 'custom:mini-media-player'
hide:
  mute: true
  icon: true
  power: true
source: icon
info: scroll
```

But when it goes to off, all the things I turned off to make it work make it collapse down to nothing:
![Off](https://user-images.githubusercontent.com/39250334/89249129-c3df2700-d654-11ea-92f4-28ac4ac38b9f.jpg)

One solution would be to have the **when_idle:** options be able to have different **hide:** values, essentially they icon and other items could be made visible again when the interface isn't cluttered up by the now playing information.

This style of player also shows up the 'compact player' being lumped in with the hiding of the volume or controls. Ideally for this style of player, I'd like to be able to hide the volume control, but still have it stay as a full height player. Currently trying to hide the volume in this kind of small state looks like this:

![image](https://user-images.githubusercontent.com/39250334/89249332-48ca4080-d655-11ea-9af9-b22bd3d36eb0.png)

**Comment by kalkih** [comment]
Hello.

As this is a rather specific design request I would recommend the usage of card-mod, in order to customize & style the card to fit this use-case.

Another option would be to create a universal media player and have the entity state always fall back to "on", which should result in the "off" view never being visible.
Alternatively wait for this https://github.com/kalkih/mini-media-player/pull/248 PR to be merged, which would eliminate the need of creating a universal media player.

**Comment by kineticscreen** [comment]
FYI for anyone that might find this thread, the easiest way of solving this problem was to create two condition cards, for 'off' and 'not off'.
So when off, the above custom:mini-media-player card is hidden, and instead a standard Lovelace button card is shown:

![image](https://user-images.githubusercontent.com/39250334/89487313-74316480-d7e8-11ea-8da1-22099873073b.png)


```
     - type: conditional
        conditions:
          - entity: media_player.office_speaker
            state: 'off'
        card:
          type: button
          tap_action:
            action: more-info
          hold_action:
            action: toggle
          show_icon: true
          show_name: true
          show_state: true
          entity: media_player.office_speaker
          name: Office
      - type: conditional
        conditions:
          - entity: media_player.office_speaker
            state_not: 'off'
        card:
          artwork: material
          entity: media_player.office_speaker
          hide:
            mute: true
            power: true
            icon: true
          idle_view:
            when_idle: false
          info: scroll
          source: icon
          type: 'custom:mini-media-player'
          name: Office
```
