### ISSUE TITLE
Feature Request: Display appname instead of media info

### ISSUE THREAD

**Issue by cicero22** [kalkih/mini-media-player#38]
For my Nvidia Shield TV players, I use this custom component: https://community.home-assistant.io/t/native-support-for-android-tv-android-devices/82792 

It adds the Shields as media_players, but unfortunately they do not have any media_info attributes while playing. They do expose the app_id and appname of the currently active Android app though. The standard lovelace cards (media-control and entities) show the appname, but I prefer this fantastic custom card... 

Is it possible to display the appname when a player does not provide media_info?

Thanks,
Tim

**Comment by kalkih** [comment]
Sure, will try to add this in the next release 👍

**Comment by kalkih** [comment]
Available now in the latest release [v0.9.6](https://github.com/kalkih/mini-media-player/releases/tag/v0.9.6).

Thanks!
