### ISSUE TITLE
Cover Artwork doesn't work for SkyQ on 1.10.0 or 1.10.1

### ISSUE THREAD

**Issue by B-Hartley** [kalkih/mini-media-player#385]
Hi,

I'm using the mini-media-player with trhe SkyQ integration.
https://github.com/RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer/releases/tag/v2.3.0

Artwork seems to work fine up to mini-media-player 1.9.1 but doesn't work on 1.10.0 or 1.10.1
If I click on the media-player entity, I can see the thumbnail of the artwork, but it doesn't show as "cover"

Any thoughts on how I can investigate ?

arch | x86_64
chassis | embedded
dev | false
docker | true
docker_version | 19.03.8
hassio | true
host_os | HassOS 4.11
installation_type | Home Assistant OS
os_name | Linux
os_version | 5.4.50
python_version | 3.8.3
supervisor | 229
timezone | Europe/London
version | 0.113.3
virtualenv | false

**Comment by kalkih** [comment]
Hello,
What's your card config?
What browser are you using?
What do you mean you can see the thumbnail, the thumbnail and cover artwork are mutually exclusive through the artwork option.

**Comment by kalkih** [comment]
Do you have other media players, and if so, do they work as expected?

**Comment by B-Hartley** [comment]
I’ll check. But rolling the mini media player back makes it work again.

**Comment by B-Hartley** [comment]
Card config is:
```

          - entity: media_player.lounge_skytv
            type: 'custom:mini-media-player'
            artwork: cover
            max_volume: 70
            info: short
            hide:
              power: true
              play_pause: true
```

Using the Home assistant app, or using Chrome.

If I click on the icon on the left of the card, it open the entity details pop up (not sure if that is what it’s called).
That has a circular thumbnail on it, that works even when the cover artwork isn’t working.

Does any of this make sense?

**Comment by kalkih** [comment]
Alright, thanks for the info, I'm not able to reproduce it but I've only ben able to try on other media player platforms since I don't own a SkyQ device.

Something is probably going wrong when fetching the artwork, I changed the way artwork is fetched and presented recently to hide flicker/glitching while the artwork is loading and to be able to smoothly transition between artwork when switching media.

Would be great if you could check the console log inside of the browsers developer tools.
Switch track a few times and see if any errors show up in the console.

Thanks!

**Comment by B-Hartley** [comment]
Hi,
This is from the Chrome Console.
Not sure if this means it is a SkyQ integraton issue, or a mini media player issue?
Let me know if you need more logs.

```
remote:1 Access to fetch at 'https://images.metadata.sky.com/pd-image/896fc6f6-0f2b-416b-b625-66d83db7f114/16-9' from origin 'https://whiteacres.duckdns.org' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
mini-media-player-bundle.js?v=20:1 GET https://images.metadata.sky.com/pd-image/896fc6f6-0f2b-416b-b625-66d83db7f114/16-9 net::ERR_FAILED
(anonymous) @ mini-media-player-bundle.js?v=20:1

```

**Comment by B-Hartley** [comment]
This seems to be ok when running in Chrome on my macbook, but running in the home assistant app 0.114.2 the cover art is not dispaying.

There was this message in Chrome not sure if it is relevant ?

A cookie associated with a cross-site resource at http://sky.com/ was set without the `SameSite` attribute. It has been blocked, as Chrome now only delivers cookies with cross-site requests if they are set with `SameSite=None` and `Secure`.

**Comment by kalkih** [comment]
Hey, are you sure the new version was loaded on your phone? The old version where it didn't work might still have been loaded from cache perhaps?

**Comment by B-Hartley** [comment]
I'm still seeing this issue.
Works ok on chrome on Mac.
But on Latest Home Assistant ios beta app, the cover art does not work.

Still works on 1.9.1, but not on anything after that ?
