### ISSUE TITLE
shortcuts label_template

### ISSUE THREAD

**Issue by fabriba** [kalkih/mini-media-player#389]
Hello!
more of a feature request than an issue:
I use "shortcuts" to change radio station.

I'd like the label in that shortcut to be non-static (
ie: instead of simply "
```label: Radio```

I'd like to use something like

``` label: sensor.radio_station```

**Comment by kalkih** [comment]
Hello,
[config-template-card](https://github.com/iantrich/config-template-card) is a perfect fit for this use case.
Check it out.
