### ISSUE TITLE
Default HA Theme has no volume level background color

### ISSUE THREAD

**Issue by Merwenus** [kalkih/mini-media-player#394]
My guess that the color ID/name changed a few version before in HA, and the volume bar on the **right side** has the same color as the background. Changed themes and it works and visible there, only the **default theme** has it wrong.
![6591](https://user-images.githubusercontent.com/13202008/90477937-93a38800-e12c-11ea-8c35-0f704884deee.png)

**Comment by kalkih** [comment]
Are you on the latest version of the card?
Should have been fixed with yesterdays release, but will double check when I get home tonight.

**Comment by Merwenus** [comment]
Yeah, thanks for your reply, it turned out I had to clear **CACHE**. Now it works, thank you.

Media player version Installed: v1.10.2
Last updated: 16 hours ago
Home Assistant 0.114.2

**Comment by kalkih** [comment]
Great 🎉
