### ISSUE TITLE
Prevent breaking existing multiroom groups

### ISSUE THREAD

**Issue by nagyrobi** [kalkih/mini-media-player#397]
I have 3 multiroom-capable players (linkplay).
I connect 2 of them, one master, the other is slave - all OK.
On the third player I still see both checkboxes of the first 2 players available to join them into a group.

This should be prohibited (checkboxes disabled) so that the user shouldn't be allowed to join speakers to a new group, while these are already joined to another group. Currently this causes failures and breaks the first group functionality and things become erratic.

**Comment by kalkih** [comment]
This is the intended behaviour and I personally think this is the right way to go about it.
It would be annoying if you couldn't create a new group form the third card without first going to the "current master card" and ungrouping speakers, would be both frustrating and confusing.
