### ISSUE TITLE
Artwork in grouped view: minor layout issues

### ISSUE THREAD

**Issue by cicero200272** [kalkih/mini-media-player#4]
If I combine several players with "artwork: cover" in another card using "group: true", the player name is not properly aligned with icon and power button. 

![image](https://user-images.githubusercontent.com/15817602/45866944-7f10b680-bd82-11e8-99ed-88fb5fe8da44.png)

If a player is active, the layout is just fine:

![image](https://user-images.githubusercontent.com/15817602/45866994-9f407580-bd82-11e8-9bec-ec8e8efecb92.png)

          - type: entities
            show_header_toggle: false
            title: "Devices"
            entities:
              - type: custom:mini-media-player
                entity: media_player.mediacenter_wohnzimmer
                power_color: true
                artwork: cover
                group: true
              - type: custom:mini-media-player
                entity: media_player.google_home
                power_color: true
                artwork: cover
                group: true
                more_info: false
              - entity: binary_sensor.printer_online
                secondary_info: last-changed
              - entity: binary_sensor.tablet_online
                secondary_info: last-changed
              - sensor.phone

General question: the icon and text colors do not match my other cards, they are black instead of dark blue as my other icons/texts. I do not use a skin, only the standard layout. Do I need to apply a skin?

**Comment by kalkih** [comment]
@cicero200272 Thanks for posting this, I've now fixed the alignment issue. I've also updated the media info text color as well as the entities icon color when no theme is set.

The changes are made in the [dev](https://github.com/kalkih/mini-media-player/tree/dev) branch atm and will be pushed to master in the next release.

And no, you should not need to use a theme, although I make use of theme variables to decide coloring for different items in the UI, so the cards look will appear better/worse in different themes depending on their variable configuration.

**Comment by cicero200272** [comment]
Excellent, works fine now! Cheers!

**Comment by kalkih** [comment]
Fix is now available in latest release [v0.6](https://github.com/kalkih/mini-media-player/tree/v0.6)
