### ISSUE TITLE
Feature Request: progressContainer and entity__info__media should use Home Assistant variables

### ISSUE THREAD

**Issue by rhoriguchi** [kalkih/mini-media-player#40]
The progress bar is always orange and gray if disabled, would be nice if it would use the Home Assistant variables to look more consistent, the same with the media info.

**Comment by kalkih** [comment]
I think you are referring to the global color variables?
They are actually already used throughout the card.

The orange color is based on  the `accent-color` variable, you can modify this variable in your theme if you want another color.

The progress bar use almost the exact same colors as the default media-control card.
The default one doesn't use any variable for the container background.

media-control:
```css
--paper-progress-active-color: var(--accent-color);
--paper-progress-container-color: rgba(200, 200, 200, 0.5);
```
mini-media-player:
```css
--paper-progress-active-color: var(--accent-color);
--paper-progress-container-color: rgba(150,150,150,0.25);
```
The only difference is the slightly lighter grey for the progress container, which looks cleaner imo.
Also, the default media-control card doesn't change to grey when state equals paused, which I do in this card, this is a design decision intended to provide the user with a clearer overview.

The media info text does also use global color variables

Active:
```css
color: var(--secondary-text-color);
```

Inactive: 
```css
color: var(--primary-text-color);
opacity: 0.5;
```

Has cover: 
```css
color: var(--accent-color);
```

**Comment by rhoriguchi** [comment]
Thank you for the great comment

**Comment by kalkih** [comment]
Thanks, can I close this or do you have any suggestions for changes in mind?

**Comment by rhoriguchi** [comment]
You can close it, thank you for the help.
