### ISSUE TITLE
Custom element doesn't exist: mini-media-player. (after update to core 0.114.2)

### ISSUE THREAD

**Issue by luizlaurentino** [kalkih/mini-media-player#401]
Was working perfectly now is showing: 0.114.2
Custom element doesn't exist: mini-media-player
Other custom elements are still working fine.

![image](https://user-images.githubusercontent.com/17413441/90795026-f12e0500-e2e3-11ea-8149-7a84e0db1cb2.png)

**Comment by wikkixwikki** [comment]
Also getting this.
![image](https://user-images.githubusercontent.com/33661036/90813153-61d52180-e2e4-11ea-9d9f-09a182bd1503.png)

I had to add it via command line as it wasnt really working through the UI either. After the reboot that was the notification I got.

**Comment by luizlaurentino** [comment]
I’m no receiving this error notificatio, just the card one

Em qui., 20 de ago. de 2020 às 15:56, wikkixwikki <notifications@github.com>
escreveu:

**Comment by wikkixwikki** [comment]
I got it after restarting HA... IF you go check /config/configuration.yaml, do you have a resources section with the info i have above in it?

**Comment by luizlaurentino** [comment]
No, ive set the resource via GUI.

Em qui., 20 de ago. de 2020 às 15:59, wikkixwikki <notifications@github.com>
escreveu:

**Comment by wikkixwikki** [comment]
I couldnt find the resource section to be able to do so

**Comment by luizlaurentino** [comment]
Configuration -> lovelace dashboards -> resources

Em sex., 21 de ago. de 2020 às 00:51, wikkixwikki <notifications@github.com>
escreveu:
