### ISSUE TITLE
dlna_dmr

### ISSUE THREAD

**Issue by braam** [kalkih/mini-media-player#407]
Can you add support for the dlna_dmr integration?

**Comment by kalkih** [comment]
This card works with all media player integrations.
Features & functionality may differ between integrations depending on their implementations.

**Comment by kalkih** [comment]
Is there anything special that's not working as expected?

**Comment by braam** [comment]
Grouping for dlna_dmr is not working.. but it's the integration itself that
needs to support this I guess?

Op zo 30 aug. 2020 18:58 schreef Karl Kihlström <notifications@github.com>:

**Comment by kalkih** [comment]
Alright, you meant support for the speaker management feature specifically.
Yes the dlna_dmr integration would need to add the required service calls for me to add it.
