### ISSUE TITLE
Not all media controls work on google home speaker

### ISSUE THREAD

**Issue by dustins1983** [kalkih/mini-media-player#41]
When playing pandora on my google home speaker the pause button works, but forward, to play next track does not.

**Comment by kalkih** [comment]
Hello!

This card utilize the core [Media Player](https://www.home-assistant.io/components/media_player/) services provided by HA to interact with the backend media player component. Specifically [`media_next_track`](https://www.home-assistant.io/components/media_player/#media-control-services) and [`media_previous_track`](https://www.home-assistant.io/components/media_player/#media-control-services) for switching track.

Does it work through the default `media-control` card?
If it doesn't, I don't think I can do anything from my end to fix the issue.

It might be an issue with the [cast component](https://github.com/home-assistant/home-assistant/blob/7f0a50ce31befab10e8ba1892cc30b1334f22fc2/homeassistant/components/media_player/cast.py), or perhaps that Pandora doesn't support this on Google Home?

Pandora isn't available in my region so I can't try to replicate this unfortunately.

**Comment by kalkih** [comment]
Alright, you should probably open this issue in the Home Assistant repo, since I believe it's most likely related to the backend.

https://github.com/home-assistant/home-assistant
