### ISSUE TITLE
Feature request - Media selector same as default lovelace mediaplayer card

### ISSUE THREAD

**Issue by rdehuyss** [kalkih/mini-media-player#413]
I know, I know, I'm asking for a lot... but would it be possible to include the media selector the default mediaplayer card has since HA 0.115?

Thanks again for this wonderful card,
Ronald

**Comment by broyuken** [comment]
Very interested in this as well.

**Comment by jeffreybrits** [comment]
Wanted to request the same :)

**Comment by kalkih** [comment]
Hello!
Just updated HA, really neat feature!

You can press the card to bring up the more-info popup and you'll see the media browser feature right there.
Does that solve your request or did you have something else in mind?

**Comment by jeffreybrits** [comment]
Hi there,

In the standard media player card you have a button which brings you directly to the media browser.

![image](https://user-images.githubusercontent.com/55175145/93670811-6be26f80-fa9e-11ea-9f4c-22193c4d6a75.jpeg)


I think that is what everyone is referring to.

Cheers

**Comment by kalkih** [comment]
I looked into the official implementation of the media browser dialog and it's unfortunately not possible for a custom card to trigger the media browser.

However as described before, you can still access it but it'll require an additional click.
