### ISSUE TITLE
TIZEN Support

### ISSUE THREAD

**Issue by lambrosfl** [kalkih/mini-media-player#416]
Hello,
While the Mini-Media-Player works perfectly on Android/IOS apps as well as all main browsers, it seems that it does not support the Samsung TIZEN browser.
Is there a way to make it work on TIZEN as well?
Thank you
LL

**Comment by kalkih** [comment]
Hello,
Nothing I can do on my end, the platform integration has to be made for HA and that's outside of the scope of this card.
Perhaps this could be of interest? https://github.com/jaruba/ha-samsungtv-tizen
