### ISSUE TITLE
Since HA 0.115, checkboxes no longer appearing in speaker grouping view

### ISSUE THREAD

**Issue by nagyrobi** [kalkih/mini-media-player#418]
After updating Home Assistant to 0.115:
![kép](https://user-images.githubusercontent.com/1550668/93664762-9ec23e80-fa71-11ea-80d6-471063315702.png).

Also a strange behavior since v1.11.0 of Mini Media Player, previously the player's own checkbox was grayed out, now it's inconsistent. There are times when it shows, and there are time when it doesn't. Previous behavior was better IMHO.

**Comment by jvalst** [comment]
Same issue ;)

**Comment by kalkih** [comment]
Can't find the exact change in core HA that broke this, but I suspect the custom checkbox element i use in this card (`paper-checkbox`) is no longer imported directly when loading the HA frontend, solution would probably be to bundle the checkbox component with the card.

This will increase bundle size though which is unfortunate, especially when the element already exists in core HA.

**Comment by kalkih** [comment]
Will fix asap.

**Comment by jvalst** [comment]
Thanks a lot! The click still works on the group, so no very big deal. Just find yourself the answer which part broke it, and maybe replace this checkbox with that new one as well?

**Comment by nagyrobi** [comment]
And also, would it be possible to revert back to the previous behavior, when all the checkboxes were visible, and the ones unavailable were just grayed out?

The interface can be overseen better if all the checkboxes are present. I already have 4 multiroom-capable devices, and set up the speaker list the same for all, there you can see at a glance the exact options, if the current speakers's checkbox is missing, it's harder to oversee things as the lists look different for each speaker.

**Comment by ppanagiotis** [comment]
Same for yamaha speaker group

**Comment by nagyrobi** [comment]
> his will increase bundle size though which is unfortunate, especially when the element already exists in core HA.

You could use buttons instead. Button is pressed while a speaker is in, a released when a speaker is not. The same buttons that you use for shortcuts would do perfectly. Even with the possibility to arrange them in rows and columns.

**Comment by jvalst** [comment]
It worked again at my place, just to let you guys know ;)

**Comment by nagyrobi** [comment]
Yes, interesting. Since v0.115.4 of Home Assistant, checkboxes are back...

**Comment by kalkih** [comment]
Great news, was about to switch out the checkbox component but can probably hold off with that change for now then 👍🏼

**Comment by jjlawren** [comment]
Checkboxes are still missing on my 0.115.4 install.

**Comment by kalkih** [comment]
Thanks for the feedback, let me know if the issue reappear.

**Comment by hcoohb** [comment]
I seems that since 0.116 I have this problem again...
Anyone else ?

**Comment by jvalst** [comment]
> I seems that since 0.116 I have this problem again...
> Anyone else ?

Correct, same issue. The checkboxes are gone again.

**Comment by robertw** [comment]
Correct, same issue. The checkboxes are gone again.

**Comment by nagyrobi** [comment]
Problem returned indeed.

**Comment by gieljnssns** [comment]
The same problem …

**Comment by ppanagiotis** [comment]
Any update on this?

**Comment by Gulivertx** [comment]
I have the same trouble here but only on my android tablet, on my iPhone and computer browsers I don't have any problem....

**Comment by jvalst** [comment]
> I have the same trouble here but only on my android tablet, on my iPhone and computer browsers I don't have any problem....
> 
> On my Android tablet I use "Fully Kiosk Broswer"

I guess that has to do with some caching or something. On my Windows Chrome the checkboxes aren't shown either

**Comment by Gulivertx** [comment]
@jvalst thank's for your reply, unfortunately not a cache problem.

**Comment by bvansluis** [comment]
same problem here. Running 0.117.6 and checkboxes are also missing. Only when I first add a card with the control it work. But the second time I load the card the checkboxes are removed. See the attached repro steps in the video
![Missing-Checkbox](https://user-images.githubusercontent.com/46501529/99310683-a75da800-285b-11eb-8b10-8f53dde0cb62.gif)

**Comment by deluxestyle** [comment]
I have the same problem on HA 0.118.4 and mini media player v1.11.0

**Comment by nagyrobi** [comment]
Is this project abandoned?

**Comment by henrikbjorn** [comment]
```
mini-media-player-bundle.js:1 Uncaught (in promise) TypeError: Cannot read property 'selectedLanguage' of undefined
    at pc (mini-media-player-bundle.js:1)
    at HTMLElement.render (mini-media-player-bundle.js:1)
    at HTMLElement.update (mini-media-player-bundle.js:1)
    at HTMLElement.performUpdate (mini-media-player-bundle.js:1)
    at mini-media-player-bundle.js:1
    at Generator.next (<anonymous>)
    at La (mini-media-player-bundle.js:1)
    at f (mini-media-player-bundle.js:1)
```

Maybe this is related and breaks the loading of the custom checkboxes.

**Comment by mcguiresean** [comment]
Until kalkih makes a decision where they want to go with this, I have taken the liberty of forking the 'checkbox-element' branch as it didn't work for me without modifying the position of the input element in 'checkbox.js'. Release below for anyone that wants to try it out:

https://github.com/mcguiresean/mini-media-player/releases/tag/v1.11.0a

![image](https://user-images.githubusercontent.com/12557638/102986765-3ae46180-4509-11eb-8f87-ea26c63913b3.png)

**Comment by peewi96** [comment]
I can confirm this fixes the problem, thank you!

**Comment by nagyrobi** [comment]
Excellent! 

Thank you! This fixes it!

2020-12-23 11:29 időpontban mcguiresean ezt írta:

> Until kalkih makes a decision where they want to go with this, I have taken the liberty of forking the 'checkbox-element' branch as it didn't work for me without modifying the position of the input element in 'checkbox.js'. Release below for anyone that wants to try it out: 
> 
> https://github.com/mcguiresean/mini-media-player/releases/tag/v1.11.0a 
> 
> [1] 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [2], or unsubscribe [3].
 

Links:
------
[1]
https://user-images.githubusercontent.com/12557638/102986765-3ae46180-4509-11eb-8f87-ea26c63913b3.png
[2]
https://github.com/kalkih/mini-media-player/issues/418#issuecomment-750104101
[3]

**Comment by ppanagiotis** [comment]
> Until kalkih makes a decision where they want to go with this, I have taken the liberty of forking the 'checkbox-element' branch as it didn't work for me without modifying the position of the input element in 'checkbox.js'. Release below for anyone that wants to try it out:
> 
> https://github.com/mcguiresean/mini-media-player/releases/tag/v1.11.0a
> 
> ![image](https://user-images.githubusercontent.com/12557638/102986765-3ae46180-4509-11eb-8f87-ea26c63913b3.png)

Nice! Why don't you open a merge request?

**Comment by kalkih** [comment]
Thanks @mcguiresean, I did that initial work and added a custom checkbox component to circumvent the change in HA where some default component aren't imported in the base (hence not available in custom-cards), but I didn't really finish it (seems like I was pretty close though 😆 ), can't remember if there was anything else I still had left to do before merging it...

I do currently not have access to my HA instance so can't merge atm, but will do a release in a week or so.

@peewi96  @nagyrobi  Does it seem to work as expected with that change, do you notice any strange behaviour or issues?

Thanks!

**Comment by deluxestyle** [comment]
I tired it as well and it seems to work. 
The only thing which I found was the different style of the font. 
It seems the list with the checkbox has a different font or font-size

**Comment by nagyrobi** [comment]
@kalkih Yes it fixes it. The UI looks fine in:
- Android (multiple versions)
- Linux Firefox
- Windows Firefox

**Comment by bvansluis** [comment]
@mcguiresean, is it just a matter of replacing the js file with your version (/config/www/community/mini-media-player/mini-media-player-bundle.js)? I did that but it doesn't seems to work on my setup. Did a restart of HA.

**Comment by nagyrobi** [comment]
You need to also delete the .gz.

**Comment by ppanagiotis** [comment]
> @mcguiresean, is it just a matter of replacing the js file with your version (/config/www/community/mini-media-player/mini-media-player-bundle.js)? I did that but it doesn't seems to work on my setup. Did a restart of HA.

Same here. 

`Uncaught (in promise) TypeError: Cannot read property 'selectedLanguage' of undefined` :/
