### ISSUE TITLE
Multiroom checkboxes not only missing now, but also not unjoining anymore

### ISSUE THREAD

**Issue by nagyrobi** [kalkih/mini-media-player#428]
[This issue](https://github.com/kalkih/mini-media-player/issues/418) is becoming more severe.

Since around Home Assistant version ~0.116.2, one can only join a group with the (missing) checkbox link, it's not possible to unjoin anymore.

My 2 cents: if it's too difficult to deal with the checkbox, why not use [buttons](https://github.com/kalkih/mini-media-player/issues/418#issuecomment-696838912)? And[ show them all](https://github.com/kalkih/mini-media-player/issues/418#issuecomment-696057155)?

**Comment by cdrom1028** [comment]
I really miss the checkboxes. It made this card very G/F friendly!! I am not having any issues joining or un-joining. 

Home Assistant 0.118.5
HassOS 4.17
Mini Media Player v1.11.0
HACS 1.8.0

**Comment by robmikulec** [comment]
I am having the same issue checkboxes are there on update of resource or reboot.  They seem to disappear when the card is reloaded a second time whether in the same machine / browser or from a second machine / browser.

System Health

version: 2020.12.1
installation_type: Home Assistant OS
dev: false
hassio: true
docker: true
virtualenv: false
python_version: 3.8.6
os_name: Linux
os_version: 5.4.79-v8
arch: aarch64
timezone: America/New_York


GitHub API: ok
Github API Calls Remaining: 4954
Installed Version: 1.9.0
Stage: running
Available Repositories: 702
Installed Repositories: 7


logged_in: true
subscription_expiration: January 5, 2021, 7:00 PM
relayer_connected: true
remote_enabled: false
remote_connected: false
alexa_enabled: true
google_enabled: true
can_reach_cert_server: ok
can_reach_cloud_auth: ok
can_reach_cloud: ok


host_os: Home Assistant OS 5.9
update_channel: stable
supervisor_version: 2020.12.7
docker_version: 19.03.13
disk_total: 28.6 GB
disk_used: 5.8 GB
healthy: true
supported: true
board: rpi4-64
supervisor_api: ok
version_api: ok
installed_addons: ESPHome (1.15.3), Samba share (9.3.0), Terminal & SSH (8.10.0), Node-RED (7.2.11), Spotify Connect (0.8.2)


dashboards: 4
mode: auto-gen
resources: 2


api_endpoint_reachable: ok

**Comment by nagyrobi** [comment]
Try this fix: https://github.com/kalkih/mini-media-player/issues/418#issuecomment-750104101

**Comment by kalkih** [comment]
@nagyrobi  Is unjoin/join working now as well? if so I'll close this issue in favor for the other one.

**Comment by nagyrobi** [comment]
After some testing it happened to me once that exiting a speaker from the group did unjoin but didn't remove the checkbox.

**Comment by robmikulec** [comment]
I tried the fix and it is better. When you select it on one machine /
tablet, it does not show up on another.
