### ISSUE TITLE
Feature Request: play,pause,stop in compact view

### ISSUE THREAD

**Issue by Norien** [kalkih/mini-media-player#43]
I'd love to be able to switch out the mute button for a play/pause or even stop
https://i.imgur.com/YsaEIQH.png

thanks for taking the time this is awesome!

**Comment by kalkih** [comment]
Here's an example of how it could look.
<img width="507" alt="screenshot 2018-12-14 at 17 41 52" src="https://user-images.githubusercontent.com/457678/50015761-98af4c00-ffc7-11e8-931c-a6706e14ecb0.png">
<img width="508" alt="screenshot 2018-12-14 at 17 39 40" src="https://user-images.githubusercontent.com/457678/50015625-4bcb7580-ffc7-11e8-956c-5541abd4998d.png">

**Comment by Norien** [comment]
Maybe a mode to list buttons -
control:
- pause
- stop
- next

**Comment by kalkih** [comment]
So the ability to switch the mute button to either play&pause/stop/next?

**Comment by Norien** [comment]
I was thinking it would be nice to remove the logo, shift the text all the way right and then define what buttons I want on the left all together. 4 or 5 in any combo should fit nicely

**Comment by kalkih** [comment]
That's very specific and. probably won't happen, at least not at the moment, it would basically require a complete rework of how the card handles and computes the layout.

You can already hide the icon using the `hide_icon` option.

I will however add the option to have the mute button switched out for a play/pause button.

**Comment by kalkih** [comment]
New option `replace_mute` added in the latest release [v0.9.8](https://github.com/kalkih/mini-media-player/releases/tag/v0.9.8).

Available option parameters are `play`, `stop`, `next`.
