### ISSUE TITLE
Custom element doesn't exist: mini-media-player.

### ISSUE THREAD

**Issue by AntoxaSa** [kalkih/mini-media-player#437]
Custom element doesn't exist: mini-media-player.
entity: media_player.yandex_station_ff98f029b3bab4f30a965b06
shortcuts:
  attribute: sound_mode
  buttons:
    - icon: 'mdi:voice'
      id: Произнеси текст
      type: sound_mode
    - icon: 'mdi:google-assistant'
      id: Выполни команду
      type: sound_mode
    - icon: 'mdi:playlist-star'
      id: включи мою любимую музыку вперемешку
      type: command
    - icon: 'mdi:playlist-music'
      id: включи плейлист дня
      type: command
    - icon: 'mdi:heart'
      id: лайк
      type: command
    - icon: 'mdi:heart-off'
      id: снять лайк
      type: command
  columns: 6
tts:
  platform: yandex_station
type: 'custom:mini-media-player'
I installed a mini player via hacks.
The interface is set to manual control, I write it in configuration.yaml
resources:
url: /hacsfiles/mini-media-player/mini-media-player-bundle.js
type: module
I get the error:
Component error: resources - Integration 'resources' not found.
What am I doing wrong? what is the problem?

**Comment by wisdomdevil** [comment]
@AntoxaSa Hi man, i have same issue in manual mode. A resolution is put you directory path : 

```
url: /hacsfiles/mini-media-player/mini-media-player-bundle.js
type: module
```
in lovelace-ui.yaml , but you dont need to write "resource:" befor it, just url and type on top of the in lovelace-ui.yaml

**Comment by loic-moriame** [comment]
Since Home Assistant 0.117, you need to add manually ressources for Lovelace Dashboards (dashboard made from the admin panel, not in yaml files)

Go to Configuration > Lovelace Dashboards
![config general](https://user-images.githubusercontent.com/536434/99776924-dc932000-2b11-11eb-9871-2c93d897c739.png)

Then add a new ressource for mini-player: 
![config lovelace dashboard](https://user-images.githubusercontent.com/536434/99776932-def57a00-2b11-11eb-88db-9a721ce45f4c.png)

**Comment by ElMatthews** [comment]
Hallo,

Same  issue here. Installed the card through HACS but no luck. Always 'Custom element doesn't exist: mini-media-player'. All other custom cards seem to work.

I verified the Lovelace Dashboards and the entry is present and I have restarted multiple times.

Any tips?

**Comment by gentlemensmile** [comment]
Maybe the JS file is wrong

**Comment by esolutions4ev1** [comment]
This worked for me.  If this is a solution to the issue then possibly an update to the documentation is necessary when in YAML mode.

After a new install of HACS and install of 'mini-media-player' through the UI the player did not work when in 'YAML' mode.  I received the same error "Custom element doesn't exist: mini-media-player".  I manually added 'resources' but using the URL of "/local/community/mini-media-player/mini-media-player-bundle.js" as that is where HACS places it.  Restart HA and everything works.

**Comment by boulder240** [comment]
esolutions4ev1 is what worked for me as well.

**Comment by horriblenoises** [comment]
Leaving my solution here as google took me to this page.

Manual installed via wget. Added url to lovelace resources ui.
Listing url with version argument causes "element doesn't exist" error. Removing version info, resolves issue.

/local/mini-media-player-bundle.js ~~?v=1.12.1~~

**Comment by avviano** [comment]
I followed esolutions4ev1 procedure and it worked for me.

**Comment by popy2k14** [comment]
> This worked for me. If this is a solution to the issue then possibly an update to the documentation is necessary when in YAML mode.
> 
> After a new install of HACS and install of 'mini-media-player' through the UI the player did not work when in 'YAML' mode. I received the same error "Custom element doesn't exist: mini-media-player". I manually added 'resources' but using the URL of "/local/community/mini-media-player/mini-media-player-bundle.js" as that is where HACS places it. Restart HA and everything works.

thx, that also worked for me.
Also saw that the path was wrong but i dont worried about this.
But heck, yes, that was the issue.

thx a lot

**Comment by NightMean** [comment]
> This worked for me. If this is a solution to the issue then possibly an update to the documentation is necessary when in YAML mode.
> 
> After a new install of HACS and install of 'mini-media-player' through the UI the player did not work when in 'YAML' mode. I received the same error "Custom element doesn't exist: mini-media-player". I manually added 'resources' but using the URL of "/local/community/mini-media-player/mini-media-player-bundle.js" as that is where HACS places it. Restart HA and everything works.

Worked for me as well, thanks! 
The URL that HACS automatically used for me was:
`/hacsfiles/mini-media-player/mini-media-player-bundle.js?hacstag=1485208381165`

**Comment by Lesani** [comment]
same issue, same solution, just installed via hacs and had the /hacsfiles/ ressource in my ressource list.

maybe add an info to this to the readme @kalkih ?

**Comment by peterlouvel** [comment]
I had the same error after an update to HA.
Ended up fixing it by deleting it from the 'Frontend' in HACS and re-downloading via the Explorer & Download Repositories

**Comment by tclemos** [comment]
> This worked for me. If this is a solution to the issue then possibly an update to the documentation is necessary when in YAML mode.

> After a new install of HACS and install of 'mini-media-player' through the UI the player did not work when in 'YAML' mode. I received the same error "Custom element doesn't exist: mini-media-player". I manually added 'resources' but using the URL of "/local/community/mini-media-player/mini-media-player-bundle.js" as that is where HACS places it. Restart HA and everything works.

I just reinstalled the `mini-media-player` via `HACS`, followed these instructions and it worked.

**Comment by aldo1979** [comment]
Thanks @tclemos,  Ijust reinstalled the mini-media-player via HACS and it worked.
