### ISSUE TITLE
[Request] Monoprice Multizone Amplifier -> Supported Platforms for Speaker Group Objects

### ISSUE THREAD

**Issue by tcs2tx** [kalkih/mini-media-player#438]
Many thanks for the great work.  It would be great to add the Monoprice multizone amplifier to the supported platforms for Speaker Group Objects.  There is already an integration in HomeAssistant for the Monoprice 6 zone amplifier.  Thanks again.

**Comment by kalkih** [comment]
Hello and thank you!

I just had a look at the home assistant integration of Monoprice and it doesn't have any speaker group functionality available/implemented.
Feel free to open an issue in the core home assistant repository requesting this kind of functionality.

If/when it's added and made available support could be added in this card.
