### ISSUE TITLE
[Feature Request] Enable ability to configure card from card picker

### ISSUE THREAD

**Issue by TJohnson93** [kalkih/mini-media-player#439]
Just a user-friendly feature request to enable to the ability to configure this awesome card from the lovelace card picker? Apparently a few lines of code, not sure how realistic the "easiness" is.

https://www.reddit.com/r/homeassistant/comments/jovt1l/usedevelop_custom_cards_your_card_could_be_in_the/?utm_source=share&utm_medium=web2x&context=3

**Comment by TJohnson93** [comment]
I just went to perform a pull request in introduce the feature myself, however noticed the snip snippet is already in dev code. Will wait for merge into master.

**Comment by kalkih** [comment]
Yes, this will be available in the next release, will make a new one once I'm back from the holidays.
