### ISSUE TITLE
more_info: false no longer works

### ISSUE THREAD

**Issue by wbilger** [kalkih/mini-media-player#44]
Not sure when this stopped working, but maybe with the upgrade to hass .84.
Now with more_info: false specified, the more-info window still pops up.

**Comment by kalkih** [comment]
Hey,
I'm on HA 0.84.2 and wasn't able to reproduce this.
`more_info: false` works as expected, tried in Firefox, Chrome, Safari and Chrome (Android)
What browser are you having this issue in, and which version of HA do you run?
Thanks!

**Comment by wbilger** [comment]
Chrome. 
I tested a little more, and it is when they are in an entities card.

      - type: entities
        entities:
          - entity: input_select.kitchen_radio_station
            group: true
            icon: mdi:radio-tower
          - entity: media_player.kitchen_speaker
            type: custom:mini-media-player
            group: true
            icon: mdi:google-home
            scroll_info: true
            show_source: true
            hide_power: true
            hide_volume: true
            more_info: false
          - entity: media_player.kitchen_speaker
            type: custom:mini-media-player
            group: true
            artwork: none
            hide_controls: true
            hide_info: true
            power_color: true
            more_info: false

**Comment by kalkih** [comment]
Fix available in latest release ([v0.9.8](https://github.com/kalkih/mini-media-player/releases/tag/v0.9.8)).

Thank you.
