### ISSUE TITLE
Playlist shortcut

### ISSUE THREAD

**Issue by BenFR23** [kalkih/mini-media-player#441]
Hello, and thanks for your work. 

Could you update that part of the manual regardng Shortcuts  : 

id: spotify:user:XXX:playlist:37i9dQZF1DZ06evO2O09Hg
**where XXX is the user id...** 

yeah it's not obvious for everybody.

**Comment by kalkih** [comment]
Hello.
Feel free to submit a pull request if you have time, otherwise I'll get to it eventually.
