### ISSUE TITLE
Select Line In from a Script

### ISSUE THREAD

**Issue by flashransom** [kalkih/mini-media-player#444]
Is it possible to select the Line In as a source for a Sonos speaker via a script? I want to automate switching to Line In from a button.

**Comment by kalkih** [comment]
Hello, 
Sorry I can't help you, I don't own any Sonos devices and are not familiar with the features of the Home Assistant integration or limitations in it.
This question is probably better asked on the home assistant forum as it's not really related to this specific card but the Sonos intergration.

As long as it's possible to do through a script you can map that script to a button in this card.
