### ISSUE TITLE
[Feature Request] Add support for Nabu Casa TTS service?

### ISSUE THREAD

**Issue by lhassell** [kalkih/mini-media-player#450]
Is it possible to add the Nabu Casa TTS service as an option in the tts object?

**Comment by smarticu5** [comment]
I'd also be interested in this

**Comment by uchagani** [comment]
Have you tried setting the platform to `cloud`?  Nabu Casa service call is `tts.cloud_say` and the code suggests that setting the platform to `cloud` should work: `this.hass.callService('tts', `${config.platform}_say`, opts);`

**Comment by lhassell** [comment]
> Have you tried setting the platform to `cloud`? Nabu Casa service call is `tts.cloud_say` and the code suggests that setting the platform to `cloud` should work: `this.hass.callService('tts', `${config.platform}_say`, opts);`

That works! Thanks.

**Comment by kalkih** [comment]
Yes as @uchagani suggested, this card should technically support all TTS platforms, as they follow a standard interface which this card relies.

PR merged, documentation will be updated in the next release.
