### ISSUE TITLE
[Feature request] Control another speaker via volume control slider

### ISSUE THREAD

**Issue by redford-jones** [kalkih/mini-media-player#451]
I have my television hooked up to an Amazon Echo Studio and I'm looking at ways to change the volume control to change the volume of the Amazon Echo instead of the television. 
The echo is exposed as a media player entity, so supports the normal media_player.volume_up/down service calls.
Is this possible to incorporate? Or if not could someone point me at where the volume control service call is made in the code?

**Comment by kalkih** [comment]
Hello,
Creating a [universal media player](https://www.home-assistant.io/integrations/universal/) and using that new entity as the entity in the card would allow for this kind of behaviour.
