### ISSUE TITLE
Only in App: Custom element doesn't exist: mini-media-player. 

### ISSUE THREAD

**Issue by deec0n** [kalkih/mini-media-player#454]
Hi all,

first, thanks a lot for this great work, which perfectly fits my needs (together with [pymusiccast](https://github.com/ppanagiotis/pymusiccast)).

However, I have an issue that I don't quite understand. It is somewhat similar to #437, but I get it only in the App. Using a web browser, it works fine. 

Does anybody have a hint on what the issue could be here? Can I expect this to work in the app at all?
Thanks!

**Comment by kalkih** [comment]
Hello,
What device is it? And does it work in the web browser on that same device?

**Comment by MortenVinding** [comment]
Just spend way too much time figuring out how to get this working with HACS install.
Turns out you have to set the URL to /local/community/mini-media-player/mini-media-player-bundle.js?v=1.11.0 in resources!

It did not work initially in the app, I had to force close the app and open it again (on IOS that is).

**Comment by deec0n** [comment]
Hi,

it's an Android Phone (v11) and yes, it worked in the web browser on that device. It also worked straight away on my wife's iPhone/iPad.

However, due to general connectivity/authentication issues I had to reset the app, and now mini-media-player works fine on this device too. So I assume it was just the effect of an other issue with authentication/caching/connectivity (sorry, not very familiar yet with how HA works under the hood) and nothing mini-media-player specific. 

Thanks!
