### ISSUE TITLE
[Feature Request] Add cue-buttons

### ISSUE THREAD

**Issue by seanomat** [kalkih/mini-media-player#457]
Is there any chance you could incorporate the classic cue buttons to skip forward or backward a configurable amount of seconds?
Somehow most players nowadays seem to miss them.
When playing videos they are quite useful if you missed something or want to skip over the opening titles. Fiddling with the position-slider is just to unprecise with long movies. 

I tired to build them myself as a Home Assistant script, but media_player.media_seek only allows absolute positioning and the entity media_player-state does not update frequently enough.

**Comment by kalkih** [comment]
Yes you are correct, you can't really rely on just the `media_position` attribute.

You basically have to take current time - `media_position_updated_at` and add the difference to `media_position`, and you should end up with a fairly accurate actual "media position".
 
We do this for the progress and the seek feature already so all the logic is already in place, should just be to add the buttons and the option.

**Comment by seanomat** [comment]
This is the idea, that I was missing! I'll give that a try but still hope, it will become part of your awesome project.

**Comment by YodaDaCoda** [comment]
I may circle back and try to implement this one day.

I found this which may help:

```seek_position: " {{ ( as_timestamp(now()) - as_timestamp(state_attr(entity, 'media_position_updated_at')) + state_attr(entity, 'media_position') ) | float + interval }} "```

https://community.home-assistant.io/t/lovelace-mini-media-player/68459/1221
