### ISSUE TITLE
Power Button Hide not working

### ISSUE THREAD

**Issue by Sonusss** [kalkih/mini-media-player#462]
Hi,

Using the latest version (v1.11.0) hiding power button is not working 
Always visible in the card, just status is changing 
visible=power on 
hided=power off
even if my media-player integration  does not support power control

**Comment by kalkih** [comment]
Hey, what does your card configuration look like?

**Comment by Sonusss** [comment]
Hi,

Here is my config from UI lovelace editor:

  - type: 'custom:mini-media-player'
    entity: media_player.office
    icon: 'mdi:speaker'
    artwork: cover
    name: Office
    hide:
      volume: false
      source: true
      power_state: false
![Screenshot from 2020-12-30 19-07-42](https://user-images.githubusercontent.com/51654027/103372447-5daae300-4ad2-11eb-8242-6bcd924a86f0.png)

**Comment by Sonusss** [comment]
When changing power state setup to hide - true
![Screenshot from 2020-12-30 19-10-02](https://user-images.githubusercontent.com/51654027/103372593-af536d80-4ad2-11eb-814b-d1ebbe5966c5.png)

**Comment by kalkih** [comment]
Thanks, try
```yaml
hide:
  power: true
```

**Comment by Sonusss** [comment]
Yeah....
That's it !

**Comment by Sonusss** [comment]
However I'm still very interested in this feature request... ;-)
Customize Power Button Default Service #420
