### ISSUE TITLE
Update README.md with latest Simple Install methode 

### ISSUE THREAD

**Issue by Verguldebarman** [kalkih/mini-media-player#470]
Simple install ([here](https://github.com/kalkih/mini-media-player#simple-install)) should be:

**Simple install**

1. Download and copy `mini-media-player-bundle.js` from the [latest release](https://github.com/kalkih/mini-media-player/releases/latest) into your `config/www` directory.
2. Go to Sidebar -> Configuration -> Lovelace Dashboards -> Resources
3. Click on `+ ADD RESOURCE`
4. Type `/local/mini-media-player-bundle.js?v=1.12.0` below URL
5. Choose `JavaScript Module` below Resource Type
6. Accept

**Comment by kalkih** [comment]
Thanks, these are great instructions.

The installation instructions are in need of an overhaul, the current instructions are written primarily for Lovelace in YAML mode, which I guess is not very common anymore 🙂

**Comment by Verguldebarman** [comment]
Your welcome! A small favor to return for such a nice custom card. I have all my media devices showing up differently with your mini card, depending on the status of the entity (with conditional cards). Looks awesome on my mobile and feels like I have programmed my own media player app :-D 

![image](https://user-images.githubusercontent.com/67055019/104088442-4fde2600-5267-11eb-8104-9d25654c1fd0.png)
