### ISSUE TITLE
Improvement: template support for icons

### ISSUE THREAD

**Issue by KoljaWindeler** [kalkih/mini-media-player#471]
Hi, would you consider to add template support for the shortcut icons?
I'd like to have a "thumbs up" button that is either outline or filled, depending to an attribute value. Thanks

**Comment by kalkih** [comment]
Hello,
Template support won't be added to this card but [config-template-card](https://github.com/iantrich/config-template-card) would solve this for you, give it a try!

**Comment by KoljaWindeler** [comment]
Just to report back: I've tested config-template-card and in theory it works. 

I can get the icon to change, but it doesn't really work.

Sometimes the player won't update anymore (e.g. still showing the old track even though the Mediaplayer advanced) and if I add the Mediaplayer itself to the watch list it updates every second and with every update comes a reload so the player is constantly flickering
