### ISSUE TITLE
Custom element doesn't exist: mini-media-player.

### ISSUE THREAD

**Issue by bertorvar** [kalkih/mini-media-player#473]
Hi!

Just found this card and seemed to be just what I wanted. However, when I try to integrate the card to my UI I just get the error: Custom element doesn't exist: mini-media-player. I installed it via the HACS store and have activated it as I have done with many other plugins and they run perfectly. What can be the issue?

Thanks

**Comment by urielz** [comment]
That error is usually associated to the relevant resource of the custom component not being loaded. If you go to >Configuration> Lovelace Dashboard > Resources, can you see something like this:
/local/community/mini-media-player/mini-media-player-bundle.js ?

**Comment by bertorvar** [comment]
Thanks! I had already solved it by myself and what I had to do was to manually add /local/community/mini-media-player/mini-media-player-bundle.js in resources. All my previous cards were added automatically, but not this one, which confused me. :)

**Comment by TheFantasticLoki** [comment]
I have the same issue but the Resources tab no longer exists. How can I mitigate the issue now?

**Comment by TheFantasticLoki** [comment]
FOUND IT you have to enable advvanced mode in the user configuration to show it for those looking for the solution.
