### ISSUE TITLE
Cover Art doesnt cover full background like it used to

### ISSUE THREAD

**Issue by Royrdan** [kalkih/mini-media-player#474]
Using youtube music and "Cover" option for artwork it no longer covers the whole card but only shows in the middle of the card.
It used to cover the whole card.
![Screenshot from 2021-01-18 19-14-25](https://user-images.githubusercontent.com/31529324/104895417-93e8cd80-59c1-11eb-9d04-a79a958a2a09.png)

**Comment by kalkih** [comment]
I'm afraid I can't do much about this, this card takes the image from the integration and scales it to fit the card, if the image has actual black boxes on the sides, there's really nothing I can do unfortunately.

**Comment by Royrdan** [comment]
Hi Kalkih,
This plugin is fantastic so thanks so much for creating. You are a true genius which I see when going through the code.
Had some free time and Im revisiting this concern of mine, and as I said im going through ALL the javascript code, Im getting lost. I found in chrome dev tools if I edit the following
```
<div class="mmp_bg">
<div class="cover"
```
to include
left: -50%
and change
width : 200%
it works perfectly but I cannot work out how to make it do this in your code.
Ive been trying for a long time but I just cannot understand the code.
Even if you could please let me know how to mod your code to change this? or you could add a setting to fix it when using these settings would be greatly appreciated.
Thanks again for this card as its one of my most used cards!

**Comment by marcselman** [comment]
If you're using YouTube Music it seems the album art always contains colored boxes on the sides and black boxes above and below.
The image is 480px wide, but the actual album art is 270px. That's a factor of 1.777777777777778
By adding `transform: scale(1.777777777777778);` to the cover image element it works perfectly.

@kalkih Is that something that could be added? Maybe a theme variable to set the image scale or by adding `artwork: youtube-music` for example.
