### ISSUE TITLE
icons is vanish and how to get a media content to be played on media player

### ISSUE THREAD

**Issue by ranrinc** [kalkih/mini-media-player#475]
Got the latest mini-media-player on HA 2021.1.3 and found bug where icon did not show at all eventhough mdi:google-home is suppose to be appearing

2nd is there a possibility to add media content to play on mini-media-player just like the current media control player card?

![Screen Shot 2021-01-18 at 9 08 58 PM](https://user-images.githubusercontent.com/15801696/104925433-69067580-59d1-11eb-8cf3-8abc34140238.png)

**Comment by naamah75** [comment]
Same issue for me, no MDI icons shown

**Comment by schteff** [comment]
Duplicate https://github.com/kalkih/mini-media-player/issues/467

**Comment by kalkih** [comment]
Icons should be resolved see #467.
A feature request for the 2nd question can be found here https://github.com/kalkih/mini-media-player/issues/435
