### ISSUE TITLE
Squeezebox Speaker Group not working

### ISSUE THREAD

**Issue by Manlycookiebear** [kalkih/mini-media-player#480]
Hello,

I have several Squeezebox Speakers and tried to use the speaker group functionality, which is not working for me. I have used the example configuration.

The error I receive is: **Failed to call service squeezebox/sync. required key not provided @ data['other_player']**

I can group my speakers when issuing a service call through the Home Assistant GUI.

**Comment by kalkih** [comment]
Still having this issue?

`other_player` should be sent with the sync action.
https://github.com/kalkih/mini-media-player/blob/dee019f9fb626ca704ac025bbfb26979246166ea/src/model.js#L357-L361

**Comment by jab144** [comment]
Hello,

Has this been fixed? I still get this error in v 1.15.0.

Thanks

**Comment by kalkih** [comment]
Thanks.
Is it only when using the group all button? Can you use the switches to group them one by one without issues?

**Comment by jab144** [comment]
Yeah it appears doing them individually works. Just not the GROUP ALL button.

**Comment by jab144** [comment]
Okay. Thanks for looking and the work on this.
