### ISSUE TITLE
media_player.volumio 

### ISSUE THREAD

**Issue by Rapace29** [kalkih/mini-media-player#483]
Thank's for your work.
I use it to on Home Assistant to remotely manage a volumio on an second raspberry.
The standard media-player card offer an option to browse the media options ( browse podcast for example ).
Could-you please consider to add this to your mini-media-player card ?

**Comment by RomRider** [comment]
This is not possible yet because of https://github.com/home-assistant/frontend/issues/7145

**Comment by kalkih** [comment]
Duplicate of https://github.com/kalkih/mini-media-player/issues/435
