### ISSUE TITLE
Custom element doesn't exist: mini-media-player on linux and android/browser

### ISSUE THREAD

**Issue by mwessley** [kalkih/mini-media-player#489]
Sadly I get the error 
Custom element doesn't exist: mini-media-player. When looking into Lovelace UI with Linux and Android devices on the Webbrowser. With other devices and the android app, everything works fine.

Any way to solve this?

As suggested I already added the resource...

**Comment by kongo09** [comment]
I have no problem on an Android device. Did you install using HACS?

**Comment by kalkih** [comment]
Hello, depending on how old your browser / android webview version is the card may or may not be supported.
Try updating your browser / webview.

See https://github.com/kalkih/mini-media-player/issues/29
