### ISSUE TITLE
card not loading

### ISSUE THREAD

**Issue by Trouble-51** [kalkih/mini-media-player#494]
The mini media plater is not loading. I have deleted the card restarted home assistant and added the card again but with the same result. I have emptied the cache, but no effect. Although the message is that it is  not load it is working! I have core version 2021.3.4 and Supervisor 2021.3.6

<img width="489" alt="Screenshot 2021-03-24 at 17 25 58" src="https://user-images.githubusercontent.com/26715092/112356271-5a388980-8cc6-11eb-9647-213ede1c7833.png">

does anyone have a suggestion how to solve this issue.

**Comment by kalkih** [comment]
Hello, since this is related to HASS, please open an issue in the HASS repository instead.
