### ISSUE TITLE
Adding season and episode to titles

### ISSUE THREAD

**Issue by benquan** [kalkih/mini-media-player#495]
Home assistant has Season and Episode information for example when casting from PLEX

<img width="846" alt="Screen Shot 2021-03-30 at 10 47 05 PM" src="https://user-images.githubusercontent.com/3030645/113091843-02a88b00-91aa-11eb-9bb4-31c50c96eb11.png">

Would it be possible to add this information to the title?

**Comment by kalkih** [comment]
Hello, this should already be supported, should show up below the title, in the secondary info display. does it not show up?

https://github.com/kalkih/mini-media-player/blob/cc4296bf5919e3e567c1dc9ef917b9f9f1e738c3/src/const.js#L52-L59

**Comment by kuduacz** [comment]
is there a way to hide it?
