### ISSUE TITLE
Speaker group management with Google Home mini's not working

### ISSUE THREAD

**Issue by WHagenauw** [kalkih/mini-media-player#504]
In the part ' Speaker group management'  you give an example for Sonos and explains that with any other kind of group it must work also as long as they are the same type. I tried it with my Google Home mini's but cannot get it to work. I even see toggle bars instead of the checkbox. Am I doing something wrong or something not working in speaker group management?

**Comment by jazzyisj** [comment]
https://github.com/kalkih/mini-media-player#speaker-group-object

Google media players are not listed in the platforms supported by the speaker group function.

Use your Google Home app to create speaker groups.  The Cast integration will automatically create media player entities for those speaker groups.

**Comment by kalkih** [comment]
Yes, Google Cast is not supported, the speaker grouping feature isn't exposed publicly, you will have to manage speaker groups from within the google home app as @jazzyisj says, at least for now.

See #395, #292

**Comment by moshiko2312** [comment]
hi if i have grouping on google what the platform i need to write on the card?
