### ISSUE TITLE
Unnecessary padding left from the sortcuts buttons

### ISSUE THREAD

**Issue by GerdBlomb** [kalkih/mini-media-player#505]
Hi,

depending on the screen size (browser, mobile, tablet) i get a padding / margin left from the shortcut buttons.

It disappears, when it gets very smal (phone size?). I would like to suggest to avoid this also when the screen is in tablet oder desktop size.

**Unneccessary margin / padding:**

![grafik](https://user-images.githubusercontent.com/80357008/114673303-536dc700-9d06-11eb-91e2-b5e28e1e7a14.png)

**Ok:**

![grafik](https://user-images.githubusercontent.com/80357008/114673363-65e80080-9d06-11eb-8d71-997332508505.png)

**Comment by kongo09** [comment]
I would argue this is down to taste - I actually manipulated the card to always keep the margin. In your case, I suggest the wonderful `card_mod` HACS component https://github.com/thomasloven/lovelace-card-mod and add the following to the end of your `mini-media-card` card configuration:
```
card_mod:
  style: |
    div.mmp-player__adds {
      margin-left: 0px;
    }
```

**Comment by kalkih** [comment]
Hello, the default left padding is intended and was added to blend in better with the core HA cards, especially the row style cards.
@kongo09 great suggestion, thanks.

**Comment by GerdBlomb** [comment]
@kongo09 thanks for this tipp. Works for me and is absolut sufficent!

@kalkih thanks for this great component. I love id. And more over my wife is happy to use it, which leads to a better WAF (womens accepteance factor) for the boys tech toys :-)
