### ISSUE TITLE
tts on Alexa devices

### ISSUE THREAD

**Issue by Davecl** [kalkih/mini-media-player#507]
Alexa devices can no longer use "say" for tts they must now use 
notify.alexa_media_dave_s_echo_show
Any idea how I do this, I really like the idea of tts input on the card
Thanks

**Comment by kalkih** [comment]
Hello,
Specifying `alexa` as tts platform in the card config should call `notify.alexa_media`, this seems right according to the [docs](https://github.com/custom-components/alexa_media_player/wiki/Configuration%3A-Notification-Component).

**Comment by Davecl** [comment]
Thanks.. I'll have another look
