### ISSUE TITLE
Tts displays file name

### ISSUE THREAD

**Issue by 03397** [kalkih/mini-media-player#514]
I am using a lot of tts phrases on my Sonos speaker and I have noticed that after a certain home assistant upgrade or mini player upgrade, instead of mini media player to display the phrase like it used now it displays the filename.

For example instead of displaying the phrase "The garage door is opened" it displays the filename xxxzz.djdjdnd&en.mp3.

Any thoughs?

**Comment by kalkih** [comment]
Hello,
As you figured, this is due to external changes made outside of this card, hence nothing I can do about it unfortunately
