### ISSUE TITLE
resources - Integration 'resources' not found.

### ISSUE THREAD

**Issue by vicfalls** [kalkih/mini-media-player#517]
Does anybody know what is missing?
I followed the "simple install" instruction. Thanks

Logger: homeassistant.components.hassio
Source: components/hassio/__init__.py:482 
Integration: Home Assistant Supervisor (documentation, issues)
First occurred: 10:59:49 (1 occurrences) 
Last logged: 10:59:49

Component error: resources - Integration 'resources' not found.

I've found the issue.....

**Comment by Rocologo** [comment]
What was the isse? I have the same problem. Ressources is not found...

**Comment by kalkih** [comment]
> What was the isse? I have the same problem. Ressources is not found...

Can you post your card configuration?
