### ISSUE TITLE
Browse Media as Shortcut

### ISSUE THREAD

**Issue by blackmore190** [kalkih/mini-media-player#529]
Hello, 
I really like the customizability of this card. The shortscuts are great!
I would like to use a shortcut to bring up a pop-up with the media browser content of the media player entity. How is this possible?

Thanks!

Blackmore

**Comment by realroywalker** [comment]
Also been trying to find a way of doing this for a few days now.. so far no luck, it seems quite tied to the built in media control card.

**Comment by blackmore190** [comment]
The built-in media control card is not that bad. The only thing I miss here is a volume control. The shortcuts of the Mini Media Player Card are only a bonus. 
Have you found something that offers both, a media browser and volume control directly on the card?

**Comment by paddenstoeltje** [comment]
Would also love to see this feature. Otherwise I hae to use the lovelace default media card...

**Comment by Backslashh** [comment]
This is what I am missing also. Would be a great addition.

**Comment by nielsaust** [comment]
Same here. Loving the card and this feature would make it even better.

**Comment by alghazu** [comment]
A media button would be great, there must be a way to do it.

**Comment by kalkih** [comment]
Duplicate to #435
