### ISSUE TITLE
when background picture is set, it occupies less vertical space than the ones that have artwork.

### ISSUE THREAD

**Issue by rgogada** [kalkih/mini-media-player#54]
I have about 15 sonos speakers and I have arranged them in 3x3 grid (using vertical and horizontal stacks). I have set a background picture (sonoslogo.png) for the sonos that are connected to TVs (because they are not going to have any artwork displayed). in this setup the sonos logo background image appears smaller than the artwork images (vertically). please see the link for a picture. You can see that the Lounge sonos background image is shorter than the album art images.  I tried changing the image aspect ratio but it didn't help.

https://photos.app.goo.gl/DncM1LFNLCKUHYyV8

**Comment by kalkih** [comment]
I think this issue is related to the group option.
Would be great if you could post the card configuration for one card with background set, and one without.
Thanks!

**Comment by rgogada** [comment]
here is the code for the first few lines (until the end of first sonos. rest of the sonos were not pasted here for space reasons but all of them are similar). I have added background (sonos logo) to all of them. so that by default they show sonos logo until they start playing something, at which point the album art will override the sonos logo. the isue here is the sonos logo renders shorter (vertically) than the album art. Let me know if you need any further info.  

sample code
=============

`id: Media
  type: 'custom:card-modder'
  card:
    type: 'custom:vertical-stack-in-card'
    cards:
        type: horizontal-stack
        cards:
            type: 'custom:card-modder'
            style:
              background-size: 100% 100%
              border-radius: 15px 0px 0px 0px
              overflow: hidden
            card:
              type: 'custom:mini-media-player'
              artwork: full-cover
              background: /local/images/sonos_logo.jpg
              entity: media_player.frontroom_sonos
              group: true
              hide_icon: true
              hide_media_info: true
              hide_power: true`

**Comment by rgogada** [comment]
aha.. 
removing the group:true fixed it.
However it also aligned the name to center (instead of left align). but I can live with that. please see below the new screenshot after fixing. Thanks a lot for looking into this. This is an awesome card. really appreciate your work.
[https://photos.app.goo.gl/pqTdojiCc93TRjjDA](url)

**Comment by kalkih** [comment]
Thank you for the additional information.

The name is technically not centred, it's actually left aligned but without group set to `true` the card contains paddings. These paddings are ignored by the buttons and the volume slider though, since these elements are too big to fit in the limited width available for the cards, this makes it look a bit weird and inconsistent.

That's an interesting layout you got there. Unfortunately, the card doesn't scale very well below 170 pixels width, as you can see the volume slider and mute button starts to overflow.
If you can live without the mute button I think this layout could work better if you hide it (`hide_mute: true`).

I'll fix the alignment issues regarding the vertical space difference when using group option width/without artwork as shown in the picture in the initial post.

Thanks!

**Comment by rgogada** [comment]
I have overridden with some short names, so all good. However I am looking for a way to hide the volume control. you suggestion hide_mute: true does solve half that problem. Is there anyway to hide that volume slider as well, with turning short_info to true? here is the latest screenshot. almost perfect :) thanks for your help.

![image](https://user-images.githubusercontent.com/4284896/51014052-aef3fc00-15b5-11e9-935c-7af15f93ac9a.png)

**Comment by rgogada** [comment]
just realized, you are the author for my other custom card (mini graph card) as well. awesome work mate. I had a similar card using those too for my power usage. keep up the good work. Thanks.

![image](https://user-images.githubusercontent.com/4284896/51015001-4b200200-15ba-11e9-9abd-73dc33ae0bce.png)

**Comment by kalkih** [comment]
That is awesome!
Very creative usage of that card and stacks, looks like a native power consumption card!

**Comment by kalkih** [comment]
Fix for this is now available in [v1.0.0](https://github.com/kalkih/mini-media-player/releases/tag/v1.0.0).
Thanks!
