### ISSUE TITLE
add apple homepod support?

### ISSUE THREAD

**Issue by jrspowers** [kalkih/mini-media-player#553]
hello,

is it possible to add the support of the apple homepod to your mini media card so that we get more options in this like create group and more ?

the maker of the support for the apple homepod is :
[tis link](https://github.com/postlund/hass-atv-beta)

it would be nice if this would work

**Comment by kalkih** [comment]
Hello, I looked at the integration, there's no support for speaker grouping, so unfortunately not possible.
All features supported by the integration should otherwise work out of the box in the card.
Are there any other features in particular you are missing, other than speaker grouping.

**Comment by b-slick** [comment]
How do we get tts working with that integration. Can we create a platform option to support it? Thanks
