### ISSUE TITLE
No icons with HA version 2021.11.0b0

### ISSUE THREAD

**Issue by TheZoker** [kalkih/mini-media-player#555]
After updating to HA 2021.11.0b0 the icons of the card control are gone:
![image](https://user-images.githubusercontent.com/1368405/139166212-732eb2dc-f0b3-4399-ae4c-56a2646c5708.png)

Before the update they worked fine

No error in the console

Let me know, if you need more information.

**Comment by SmarterHomeLife** [comment]
Beta fixed for me as well, thanks!

**Comment by giustanca** [comment]
Fixed also for me. Thanks!

**Comment by LazyFoxFarms** [comment]
Tried the Beta on HA 2021.11 release and the controls are missing.

**Comment by SmarterHomeLife** [comment]
@LazyFoxFarms have you cleared your cache?

**Comment by LazyFoxFarms** [comment]
That did it! thanks!  Controls are back.  Thank you -  I should have know to do that.

**Comment by TheZoker** [comment]
I'm closing this, since it's fixed for me and seems to be fixed for everyone else 🙂
