### ISSUE TITLE
There is not mini-media-player in HACS

### ISSUE THREAD

**Issue by a-x-** [kalkih/mini-media-player#558]
But adding it as a custom repo does not work too with a message "already added"

**Comment by a-x-** [comment]
![2980EE68-B758-4192-B5A4-9B3977355272](https://user-images.githubusercontent.com/6201068/139815507-06c2d780-6e2b-4250-8184-24e4d5467d9d.jpeg)
![DFD08FEF-DC8C-4810-939A-93E5C48594F5](https://user-images.githubusercontent.com/6201068/139815516-ed4378c0-6ab2-4d7b-987d-5e24a8a170d2.jpeg)
![5A0833E0-1494-49BD-9CA9-AB8E91D5ACCE](https://user-images.githubusercontent.com/6201068/139815518-fa31d8c5-5355-4911-98b9-88201e7af8d9.jpeg)

**Comment by kalkih** [comment]
You shouldn't need to add it as a custom repository, it should be available out of the box.
Are you sure you're on the correct page when searching? just an idea but you might be searching in your currently installed frontend addons.
I've not used HACS in a long time myself so I'm not sure how to navigate it, sorry.

Anyways, if you still have the issue please open an issue in the HACS repository as they should be able to give you better assistance.

**Comment by a-x-** [comment]
It's not available, as I show on 1th and 2th pictures

Yes, it's correct page. There is no any other page

**Comment by a-x-** [comment]
reopen pleeaseee

**Comment by Borlean** [comment]
@a-x- did you find a resolution here? I'm in the same boat, won't come up when searching in the frontend section of HACS
