### ISSUE TITLE
Enabling "group" and "show_progress" together looks bad

### ISSUE THREAD

**Issue by hulkhaugen** [kalkih/mini-media-player#56]
Enabling "group" and "show_progress" together leaves no padding/margin between the secondary info and the progress bar, doesn't look good.

**Comment by kalkih** [comment]
Thanks for reporting this, that does indeed look bad 🤢 

This is mostly an issue when the player is displayed in the "collapsed view" if I'm correct.

I'll most likely end up adding some paddings to the top and bottom of the card when `group` is set to `true`. It would make the card take up slightly more vertical space, but should look way better.

| Before | After | 
| ------- | ------ |
| ![hyperion_8123_lovelace_4 1](https://user-images.githubusercontent.com/457678/51121439-ba466200-1817-11e9-9c63-1ac0a3edb642.png) | ![hyperion_8123_lovelace_4 2](https://user-images.githubusercontent.com/457678/51121446-be727f80-1817-11e9-8fd6-b134ad4477d0.png) |

**Comment by kalkih** [comment]
Okay, so I ended up making the progressbar slightly slimmer so the vertical height of the card wouldn't need to be increased more than necessary.
I'm not 100% satisfied so might change again in the future.

![hyperion_8123_lovelace_4](https://user-images.githubusercontent.com/457678/51286259-82474680-19f2-11e9-85d0-46cd7a3a3b14.png)

**Comment by kalkih** [comment]
Fix for this is now available in [v1.0.0](https://github.com/kalkih/mini-media-player/releases/tag/v1.0.0).
Thanks!
