### ISSUE TITLE
Icon placement alignment since v1.14.0

### ISSUE THREAD

**Issue by ronaldheft** [kalkih/mini-media-player#561]
I updated to Home Assistant `2021.11.1` and mini-media-player `v1.14.0` and while icons are loading, the alignment is off. It's particularly bad in Safari, but it's not perfect in Chrome either.

Safari (Mac + iOS)
<img width="508" alt="Screen Shot 2021-11-05 at 12 29 57 PM" src="https://user-images.githubusercontent.com/1143112/140545715-6630ccb5-2584-4d5c-9046-079806029249.png">

Chrome (Mac)
<img width="504" alt="Screen Shot 2021-11-05 at 12 31 08 PM" src="https://user-images.githubusercontent.com/1143112/140545771-943382b7-b5d0-49cf-92c1-1936a803a731.png">

**Comment by kalkih** [comment]
Eww yes, that looks bad.
I currently do not have a dev setup with me so might not be able to fix for a few days...

If anyone wanna give it a try to fix it, that would be very appreciated 🙂
