### ISSUE TITLE
Volume Slider Not Working

### ISSUE THREAD

**Issue by 400HPMustang** [kalkih/mini-media-player#562]
I'm using the [HASS TV Beta](https://github.com/postlund/hass-atv-beta) component to set my homepods up as media players and then controlling them with the mini media player cards. 

One the mini player cards themselves the volume slider does not work. I can be playing music and slide it up or down entirely and it doesn't change anything. However if I click on the card to bring up the "more-info" box the volume up/down buttons on that screen are working correctly. 

Is it possible to fix it so the slider works?

**Comment by kalkih** [comment]
Hello, this is most likely because the entity doesn't expose a volume state, which is needed for a slider, hence why buttons are shown in the `more-info` dialog.

Try the `volume_stateless` option, that will switch the slider to buttons.
