### ISSUE TITLE
Source dropdown displayed as just text 

### ISSUE THREAD

**Issue by wmrato** [kalkih/mini-media-player#563]
mini-media-player on an ODROID N2+ with Home assistant v2021.11.1 rendered via Chrome on a Denon AVR-X2400H

The **Source** is displayed as just text ("**CD Mux7**" in screenshot)
 with no  dropdown list showing  even with card configurations option of **source**: set to either icon or list.

The **Sound mode** still works & displays a dropdown.

Error occurred after updates of HACS "mini-media-player",  Home assistant v2021.11.0

![Screenshot from 2021-11-06 00-45-27](https://user-images.githubusercontent.com/6633365/140592253-1ae4a9b0-1132-4482-b9e5-d4f995f29901.png)

Under devices  in Configuration - the source is not shown at all, no text or dropdown.

![Screenshot from 2021-11-06 00-49-14](https://user-images.githubusercontent.com/6633365/140592259-d20d07d5-1017-4805-97ab-8a774854ba2d.png)

**Comment by TiSDStudios** [comment]
Same Issue here

**Comment by dankocrnkovic** [comment]
Same here with Denon

**Comment by mrblondeblonde** [comment]
I have the same issue with a Denon X2400

**Comment by mrblondeblonde** [comment]
This is how it is now:
![image](https://user-images.githubusercontent.com/79256035/140644457-d8f1884f-e725-419d-bd54-9b50ac108130.png)
It use to be:
![image](https://user-images.githubusercontent.com/79256035/140644499-3c7b4084-e303-4332-90d2-859f70957d16.png)

**Comment by wmrato** [comment]
**UPDATE:**  I'm wondering if this is an integration issue.
 
Source is not an array when viewed via **Developer Tools** | **States**
 & does not list the sources like the working **sound_mode**.

Plus HEOS media player does work, it showing a list of **source_list**, but is truncated.

![Screenshot from 2021-11-08 08-31-39](https://user-images.githubusercontent.com/6633365/140709633-ef664117-0ce9-4201-aecd-475451dc8844.png)

**Comment by wmrato** [comment]
> This is how it is now: ![image](https://user-images.githubusercontent.com/79256035/140644457-d8f1884f-e725-419d-bd54-9b50ac108130.png) It use to be: ![image](https://user-images.githubusercontent.com/79256035/140644499-3c7b4084-e303-4332-90d2-859f70957d16.png)

**Comment by wmrato** [comment]
have closed this Issue.
 & added as comment on already raised issue github **home-assistant/core**'s  **denonavr** 
 see [DenonAVR cannot select source anymore #59189](https://github.com/home-assistant/core/issues/59189)

**Comment by mrblondeblonde** [comment]
> Wow @mrblondeblonde your **Spotify** integration is working, mines been problematic for months, despite editing conf settings & restarting add-on. might need to raise another Has Add-on / Integration Issue.

Do need more details on my setup? It could help...?
