### ISSUE TITLE
Power button of another entity?

### ISSUE THREAD

**Issue by Stooovie** [kalkih/mini-media-player#565]
I have an old receiver plugged into a Xiaomi power plug, and Rpi2 with Moode Audio that has its own Mini Media Player card on my Lovelace.

I'd LOVE to be able to turn the receiver (i.e. the xiaomi plug) from the Pi/Moode card. Basically, I'd like to control the power of a different entity. 

Would somethiing like that be possible or possible to implement? Thanks!

**Comment by kalkih** [comment]
Hello,
You should be able to achieve this by creating a universal media player and use that entity in the card.

Please see https://www.home-assistant.io/integrations/universal/
