### ISSUE TITLE
Controls not visible after update to HA 2021.11.2 and Media Player 1.14.0

### ISSUE THREAD

**Issue by dgebhardt** [kalkih/mini-media-player#568]
<img width="508" alt="Screenshot 2021-11-09 at 18 52 56" src="https://user-images.githubusercontent.com/444214/140978734-eff94a1b-e519-405e-845b-fd90ac82c699.png">

Since the update (see versions above) the controls are no longer visible. Anyone else experiencing the issue? (it is the case no matter which style I select)

**Comment by thelvyn777** [comment]
Same here with HA 2021.11.2 and Player 1.13 and 1.14

**Comment by fabricepipart** [comment]
Ah OK i am not the only one then ;)

**Comment by fabricepipart** [comment]
Certainly related to #559 ...

**Comment by fikustommy** [comment]
I also have this issue.
Hovering over the controls shows a "highlighted" circle, but no clue as to which button does what.
![image](https://user-images.githubusercontent.com/33975922/141817255-9186bb46-6ad6-497f-b7c9-646ea44ed42e.png)
I tried restarting HA and cleared browser cache. I still have the issue. 

core-2021.11.3 
mini media player 1.14.0

**Comment by kalkih** [comment]
To the people who still have this issue after clearing cache, reinstalling the card in HACS & restarting HA, can you try in incognito mode?

If icons still doesn't show up after that... let me know what browser you are using.

**Comment by fikustommy** [comment]
I tried redownloading the mini media player card in HACS, emptying browser cache and localStorage, rebooting the HA host, updating it to 2021.11.4. 
I still have the same problem.
Logging in using incognito mode in chrome, the buttons are back.
![image](https://user-images.githubusercontent.com/33975922/142022537-b33283c9-4aef-4494-938c-37d5a79512b0.png)

I don't know if this is related, but I get these errors in the chrome console:
![image](https://user-images.githubusercontent.com/33975922/142026134-7cb94126-2853-413b-8697-ef0a83f3c13e.png)
I get the same errors in both incognito and "normal" mode, though.

**Comment by dchone** [comment]
I have the same problem in all apps (Android and Apple) and browsers (Safari and Chrome), normal and incognito modes. Clearing the cache doesn't make any difference.

**Comment by thelvyn777** [comment]
> Same here with HA 2021.11.2 and Player 1.13 and 1.14

Dont know why but it was my Kody configuration which was reset, so check here too.

**Comment by roybosch** [comment]
> 

I managed to clear the browser cache in chrome using "ctrl+h > clear browser data". I first tried this using the F12 console menu, but that didn't do the trick.

**Comment by jjwBullfrog** [comment]
Same problem here. HA 2021.11.5 and Player 1.15. I've cleared the cache in Chrome and on my iPhone (HA companion app). The icons come back for a while, but then disappear. Great HA add-on, I love it!

**Comment by roybosch** [comment]
> Same problem here. HA 2021.11.5 and Player 1.15. I've cleared the cache in Chrome and on my iPhone (HA companion app). The icons come back for a while, but then disappear. Great HA add-on, I love it!

My issues aren't gone either after clearing the cache. Icons and info keep disappearing.

**Comment by abates** [comment]
Possibly related to https://github.com/home-assistant/frontend/issues/10521?

**Comment by Talvien** [comment]
Same issue here also after cash clearing in Chrome and restart.

**Comment by quizzical86** [comment]
Since November this happens to me occasionally both in the browser and on the Home Assistant Companion app on Android. I have no clue why the problem then suddenly disappears and some time later reappears.

**Comment by michaelhenningersrb** [comment]
Same problem here:

![image](https://user-images.githubusercontent.com/18479766/145997785-11f7ceef-7b94-4646-969a-2adf50014e49.png)


Any ideas?

**Comment by olehdutko** [comment]
The same issue

**Comment by jlbphotos** [comment]
Clear cache, tried different browsers, full retart of HA nuc, reloaded via hacs and rebooted.
deleted card recreated from examples still no buttons for power etc in lovelace :(

**Comment by jjwBullfrog** [comment]
I figured out how to fix it...downgrade to 2021.10.7...fixed! Hehe.

Seriously though, I'm looking forward to an actual fix. I love this card!

**Comment by michaelhenningersrb** [comment]
@kalkih Any news on this problem?

![image](https://user-images.githubusercontent.com/18479766/152130395-dacae1e8-0bbf-46cf-bd8d-bcd3716c6b4c.png)

**Comment by jjwBullfrog** [comment]
I found my problem.

I had multiple links listed under resources for the "mini-media-player-bundle.js" file. Perhaps an update with HACS changed file locations and created duplicates?

The link I deleted was "/local/mini-media-player-bundle.js?v=1.9.1". 
The link I kept is "/hacsfiles/mini-media-player/mini-media-player-bundle.js?hacstag=[string of numbers]]"

Perhaps this is the same problem as other? I hope it helps.

**Comment by Talvien** [comment]
Great comment, I checked it and realised I was using a local version. Switched to HACS version, deleted the respective line from config file and restarted. Now I have the buttons back.
________________________________
Von: jjwBullfrog ***@***.***>
Gesendet: Sunday, February 13, 2022 1:11:56 AM
An: kalkih/mini-media-player ***@***.***>
Cc: Talvien ***@***.***>; Comment ***@***.***>
Betreff: Re: [kalkih/mini-media-player] Controls not visible after update to HA 2021.11.2 and Media Player 1.14.0 (Issue #568)


I found my problem.

I had multiple links listed under resources for the "mini-media-player-bundle.js" file. Perhaps an update with HACS changed file locations and created duplicates?

The link I deleted was "/local/mini-media-player-bundle.js?v=1.9.1".
The link I kept is "/hacsfiles/mini-media-player/mini-media-player-bundle.js?hacstag=[string of numbers]]"

Perhaps this is the same problem as other? I hope it helps.

—
Reply to this email directly, view it on GitHub<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkalkih%2Fmini-media-player%2Fissues%2F568%23issuecomment-1037600260&data=04%7C01%7C%7C9762754eaa0a49a3781608d9ee8572a9%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637803079193177043%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=QwZYEUXtUqf0ItgYjEaTCHmLjn6KoRRvhIuJ%2FuOeijs%3D&reserved=0>, or unsubscribe<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FADR7NHKSCARDCCUSE2BGM4DU23ZMZANCNFSM5HV5JXFQ&data=04%7C01%7C%7C9762754eaa0a49a3781608d9ee8572a9%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637803079193177043%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=HajDeq6igHiwbKgjGS0LDOC1FD1txabellBVHOB6BKo%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C9762754eaa0a49a3781608d9ee8572a9%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637803079193177043%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=j3aexlKyDPET4JuvlDSf0IVIQs%2FW6lH051Gpe8%2B579E%3D&reserved=0> or Android<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C9762754eaa0a49a3781608d9ee8572a9%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637803079193177043%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=J6JNLj6YB9XhojLRTHeL9ygUIB7BVuGlwGMwYb%2FWpEI%3D&reserved=0>.

**Comment by kalkih** [comment]
Thanks for the replies.
Yes, the icon-button implementation in HA had a breaking change in HA 2021.11.0, we adjusted to this change in the v1.14.0 of this card.

If you have issues with invisible buttons, you are most likely loading an older version of the card, either from cache or through an old resource reference as suggested by @jjwBullfrog above. Please try clearing cache and check for (and delete) old or duplicate resource references.

**Comment by kalkih** [comment]
#559

**Comment by jjwBullfrog** [comment]
> Thanks for the replies. Yes, the icon-button implementation in HA had a breaking change in HA 2021.11.0, we adjusted to this change in the v1.14.0 of this card.
> 
> If you have issues with invisible buttons, you are most likely loading an older version of the card, either from cache or through an old resource reference as suggested by @jjwBullfrog above. Please try clearing cache and check for (and delete) old or duplicate resource references.

Hi @kalkih - The installation instructions still reference the local file path. If this is not the case, then maybe the installation instructions need updating? https://github.com/kalkih/mini-media-player

**Comment by michaelhenningersrb** [comment]
Thanks, @jjwBullfrog this solved it also for me ;)

**Comment by kalkih** [comment]
The installation instructions are still valid for when you want to install the card manually.
