### ISSUE TITLE
Volume up button kind of stuck

### ISSUE THREAD

**Issue by MarcinL1977** [kalkih/mini-media-player#572]
Strange issue - I have the automation set to start playing internet radio in the mornings through Bluesound streamer. I set volume to 6% using media_player.volume_set. All seem to work fine, but when I want to turn volume up by clicking on volume up button, I cannot do this. I can go below 6% and back, but not higher, as if volume_set was acting as a threshold. Clicking on a card and using slider works fine and unlocks functionality of volume up button. I am very new to home assistant, so if I need to provide any logs or further info please point me in the right direction.

**Comment by TobiasSchwarz74** [comment]
Are you using sonos speakers?
I had the same issue, even when controlling the volume using a zigbee remote with node-red automation.

I fetched the current volume level, added "0.01" to set it with the new value - it stuck at 6%.

This seems to be a rounding issue of the sonos integration i think - i fixed this issue by adding "0.011" instead.
This workaround also works with MMP - set "volume_step: 1.1" and the volume will increase correctly in %-steps.

**Comment by MarcinL1977** [comment]
No, media player is bluesound and speakers attached are wired ones.

**Comment by TobiasSchwarz74** [comment]
Ok, so perhaps a HA issue - definitely not a MMP issue.
Have you tried my workaround? It solved my issues with node-red as well as with MMP.

**Comment by kalkih** [comment]
Hello, when you have this issue, is the issue present in the default media-control card as well?

**Comment by kalkih** [comment]
No worries, I would suggest opening an issue in the core HA repository for a better chance to get this resolved.
Thanks!
