### ISSUE TITLE
Source button not working

### ISSUE THREAD

**Issue by TimBeekman** [kalkih/mini-media-player#574]
Since the v1.14.0 update I no longer can select or change the source of my Denon (heos) amplifier. 
![2754E79E-0F7D-49C5-B81A-5E06CA401319](https://user-images.githubusercontent.com/89469564/142507983-7b84fa1d-03ae-457b-b73d-0af27ab6999d.png)

**Comment by ollisulopuisto** [comment]
Same here. Tried restarting HA and clearning browser (and iOS app) cache, doesn't help.

**Comment by pascal-puetz** [comment]
Same here, the issue appeared after upgrading Home Assistant to 2021.11.4 from 2021.10.x (not sure which version I was on). I also updated this card to the newest release before I updated HA, but I'm completely uncertain from which version and if the error was already present before the HA update.

**Comment by ollisulopuisto** [comment]
BTW this was fixed for me by HA 2001.11.5, see [this issue](https://github.com/home-assistant/core/pull/59768)

**Comment by TimBeekman** [comment]
Same for me, HA 2001.11.5 fixed the issue!
