### ISSUE TITLE
hey just curious how if there is a way to make the media library button appear

### ISSUE THREAD

**Issue by arlynxyu** [kalkih/mini-media-player#575]
seems like this icon would be shown by the hide browse true | false arg but i'm not actually sure what that does as it makes no change visually. on the default media player card this button shows up by default, but it only shows up in the popup when you click on the mini-media-player card. is there any way to make the media library button show up or could you add support for it? also great job on this i appreciate it and you for making it very much! :)

**Comment by kalkih** [comment]
That would indeed be great, unfortunately currently not possible for custom cards to access this feature in HA.

See https://github.com/kalkih/mini-media-player/issues/435 for more info.

Thanks!
