### ISSUE TITLE
Power button unresponsive 

### ISSUE THREAD

**Issue by direx1** [kalkih/mini-media-player#584]
I'm getting a warning of [homeassistant.helpers.service] unable to find referenced entities related when I press the power button. Volume and media art are displayed fine and working just not power. This was working until latest core version.

**Comment by kalkih** [comment]
Should not be related to this card but rather to the media player integration you are using. Open an issue in the core home assistant repository if its an official integration.

**Comment by direx1** [comment]
> Should not be related to this card but rather to the media player integration you are using. Open an issue in the core home assistant repository if its an official integration.

Ah great but there's no issues with any other media cards, just this.

**Comment by chriscolden** [comment]
I too have this issue but it's only with Google cast audio group. Individuals are fine. If I stop this from the media player entity itself it stops. This seems to be a bug with this card.
