### ISSUE TITLE
Actions on Volume Up/Down

### ISSUE THREAD

**Issue by fakethinkpad85** [kalkih/mini-media-player#592]
I´m using a Volumio media player and a DAC with SPDIF output that dousent support volume control, what i would like to achieve is using the built in Volume Up and Down buttons to call a Service for my Broadlink RM4 Mini to control the volume by IR.

I suppose this could be done using "shortcuts" but i need to have the player as compact as possible and I´m not sure the Shortcuts can be placed at the top which would be one solution. 

Another solution would be if we could use the default Up/Down buttons and set a custom Action/Service on them.

![Skärmbild 2022-01-15 133816](https://user-images.githubusercontent.com/59344078/149621991-13f5f7b2-ef30-4f8a-a4b7-68d8cbb52660.png)

**Comment by kalkih** [comment]
Hello,
I would suggest creating a [Universal Media Player](https://www.home-assistant.io/integrations/universal/), and map the volume commands to the desired service, and use that entity in the `mini-media-player` card
