### ISSUE TITLE
Show Idle Google Cast Devices as off

### ISSUE THREAD

**Issue by ThirteenTX** [kalkih/mini-media-player#599]
With the recent update to 2022.2 Chromecasts now show as Idle where they used to show as off.

Make idle chromecasts appear as idle instead of off ([@emontnemery](https://github.com/emontnemery) - [#61786](https://github.com/home-assistant/core/pull/61786)) ([cast docs](https://www.home-assistant.io/integrations/cast/))

This causes them to never retract back into the "off" state. Is there a way to make Idle show as off?

**Comment by dankocrnkovic** [comment]
That would be really great.

**Comment by Bastiencc** [comment]
+1

**Comment by snp88** [comment]
maybe add function to hide volume bar when status is idle

**Comment by adrez99** [comment]
I'm using this as a workaround, but it shows the entity state and would like to get rid of it:

    idle_view:
      when_idle: true

**Comment by snp88** [comment]
> idle_view:
>   when_idle: true

thx somehow i miss this ;)

**Comment by dankocrnkovic** [comment]
Looks like its fixed with the latest HA hotfix release. 2022.2.5
