### ISSUE TITLE
feature request: speaker media-player

### ISSUE THREAD

**Issue by ycardon** [kalkih/mini-media-player#6]
Hello, great project !

Several of my media-players are speakers (AirPlay endpoints exported by the [iTunes component](https://www.home-assistant.io/components/media_player.itunes/)).

Using mini-media-player I get redondants controls:

![mini-media-player-speakers](https://user-images.githubusercontent.com/1177253/45940108-4fa6b780-bfd7-11e8-9e56-3fb0e36a264b.jpeg)

Could you add some options to hide __controls button__ (not needed on the speakers), __volume slider__ (not needed on the iTunes media player) and __mute button__ (does not work with the iTunes component)?

Ideally, I'd love to have a way to configure one-liner controls to gain screen space: 
- iTunes: name + controls
- speaker: name + volume + power

![mockup-mini-media-player](https://user-images.githubusercontent.com/1177253/45940619-60a4f800-bfda-11e8-836a-9ba3500554e6.jpeg)

**Comment by kalkih** [comment]
This should now be possible to achieve in [v0.8](https://github.com/kalkih/mini-media-player/releases/tag/v0.8) with the `hide_volume` and/or `hide_controls` option.
Let me know how it works, thanks!

**Comment by ycardon** [comment]
It works great and looks very cool now on my setup 👍

<img width="423" alt="image" src="https://user-images.githubusercontent.com/1177253/46095597-319aac00-c1bd-11e8-928f-0698b1f7485c.png">

Many thanks :)

**Comment by kalkih** [comment]
Great! Thanks for the suggestion!
