### ISSUE TITLE
Shuffle button not respecting Scale setting

### ISSUE THREAD

**Issue by suneworld** [kalkih/mini-media-player#602]
All buttons increase in size if I adjust scale, but the Shuffle button will only increase a certain amount (see image)
Thanks for a wonderful card by the way!

![image](https://user-images.githubusercontent.com/74769325/152832315-1a8cea5c-6076-41af-9ea8-bf36a40d905d.png)

**Comment by kalkih** [comment]
Should be fixed in latest release
