### ISSUE TITLE
Grouping of media_player domain (and HEOS)

### ISSUE THREAD

**Issue by tmjo** [kalkih/mini-media-player#604]
Hi @kalkih and thanks for your awesome card! I've used it for a long time, and also did a custom integration for HEOS to enable grouping. In HA 2021.12 grouping was added to the official integration of HEOS after a really long time and a architectural discussion on how to organize grouping of media players in HA.

However, we see some issues with the card in combination with your card. Basic grouping (1+1 player) works just fine, but trying to add a second player to the group it replaces the first player with the second one. According to the official [HEOS integration docs](https://www.home-assistant.io/integrations/heos/) all members should be part of the _group_members_ call, not only the recently added. I do not know if this is the case for HEOS only, but I would believe that after such a long architectural discussion it had been decided that this is the way once the HEOS feature was added. Would you happen to know what is correct?

See the [forum ](https://community.home-assistant.io/t/heos-group-support/126501/110)for discussions on the subject. Below an animation of what happens taken from the forum:
![heos-mini-media-card](https://user-images.githubusercontent.com/54450177/153681675-6678396c-17df-4c79-b071-cecc104e123d.gif)

I did a tweak to my fork of your card in _handleGroupChange_:
```
        case PLATFORM.MEDIAPLAYER:
          let members = this.group;
          members.shift() // remove master from list
          members.push(entity); // add new entity to group
          return this.callService(e, 'join', {
            entity_id: this.entityId,
            group_members: members,
          }, platform);

```

and this seems to achieve what I want it to. I would be happy to propose a PR on this, but I would like to hear your opinion on how to do it first.

PS! Once done, HEOS should be added to the supported players list :)

**Comment by kalkih** [comment]
Hello,

Thanks for the detailed explanation, and great work on the custom implementation!

Do you know if this new "standard" way of implementation is adopted by the other media player integrations with `media_player.join`/`media_player.unjoin` support as well? I think e.g. musicCast https://github.com/kalkih/mini-media-player/issues/528 & Roon https://github.com/kalkih/mini-media-player/issues/519 already used these services and the current service call in this card seems to work there, or at least it did...

If we think this is the way forward in HA, I think we should make the change and a PR would be appreciated!
And if other integrations break because of the change we could just add special cases for those.

**Comment by kalkih** [comment]
Alright,
Yes, We could add a heos case for now, and leave the media_player case as is for now until we see these changes in other integrations.

**Comment by tmjo** [comment]
Great, I'll propose a PR. Thought I had it ready, but ran into some issues with the Ungroup button (when ungrouping whole group), but it may be a temporary problem in my installation. I'll do some more testing before presenting the PR.

**Comment by tmjo** [comment]
Please see if you find PR #607 to your liking and let me know if you prefer I change something. 

It seems to be working fine in my installation now (one of my units needed rebooting after too much 'unhealthy' testing, that was what gave me issues on the ungroup all command previously).

**Comment by tmjo** [comment]
Hmm, se the checks failed. Will see into that later, it I couldn't see exactly what it is failing on, but it's getting late :)

**Comment by tmjo** [comment]
Was some stupid linting issues from my side, should be ok now. I get some errors on my local installation on lint (on code I didn't change), but I guess it is something with my nvm/npm installation, but at least it is passing lint tests on the server so it should be good to go.

**Comment by kalkih** [comment]
https://github.com/kalkih/mini-media-player/pull/607 now available in latest release, great stuff @tmjo  👍🏼
