### ISSUE TITLE
issue with source dropdown from HA core-2022.3.0b0

### ISSUE THREAD

**Issue by n00bcodr** [kalkih/mini-media-player#612]
The source dropdown is always open and does not have a background.

![image](https://user-images.githubusercontent.com/49611451/155574176-23db6f0a-43e8-4d2e-8df0-b2918b374d12.png)

**Comment by itkama** [comment]
Can confirm this problem with core-2022.3.0b0 and core-2022.3.0b1:
<img width="375" alt="image" src="https://user-images.githubusercontent.com/37951363/155582233-c0820744-bf3c-43b3-ad8b-0765bb96487b.png">

**Comment by KNXBroker** [comment]
Same here, 2022.3.0 will destroy the card completely:

Default view (not clicked anything)
![image](https://user-images.githubusercontent.com/25910703/155598639-1c111456-50bf-43a1-b3be-e6722476a9ff.png)

**Comment by tomlut** [comment]
Duplicate https://github.com/kalkih/mini-media-player/issues/606
