### ISSUE TITLE
Issue with GUI configuration with HA core-2022.3.0b1

### ISSUE THREAD

**Issue by KNXBroker** [kalkih/mini-media-player#613]
HA core-2022.3.0 destroys the graphical configuration in HA editor:

![image](https://user-images.githubusercontent.com/25910703/155599185-1af16af2-eedc-4e3d-96b2-a96257d6fb34.png)

**Comment by tomlut** [comment]
Duplicate https://github.com/kalkih/mini-media-player/issues/606
