### ISSUE TITLE
Remove ability to use raw source

### ISSUE THREAD

**Issue by kalkih** [kalkih/mini-media-player#62]
* Remove external imports, replace with npm packages.
* Remove source file from tracker.json.
* Rename source, less confusion?

**Comment by iantrich** [comment]
I'm really interested to see what you come up with on this and think this should probably be the default way custom cards handle dependencies

**Comment by kalkih** [comment]
The build process right now is: source -> rollup -> babel -> output.

Rollup to replace the external dependencies CDN urls with equivalent npm package, resolve dependencies & generate a bundle.
Babel to transpile ES6/ES7 syntax & minify.

I'll remove the external CDN urls in the imports and replace them with the npm packages directly in the source, making it impossible to use the source directly, forcing people to use the bundle 😈

**Comment by nervetattoo** [comment]
So, you left an opening for hijacking this issue @iantrich :D 

I'm in the process of doing pretty much the same with [simple-thermostat](https://github.com/nervetattoo/simple-thermostat), and along the way I'm hoping to discover ways to improve the custom card maintainer story.
I just published [tracker-json](https://www.npmjs.com/package/tracker-json) as a first step on this journey.

I'm still serving the source file on master into tracker.json but I'm intending to change it to use assets in a GH release.

Seeing as this one of the cards with the most sophisticated dev processes we should collaborate on finding a good set of patterns for building custom cards. The biggest issue I'm seeing being surfaced with pre-built bundles is that we will be shipping a lot of bytes of JS to d/l and parse for the end users as different cards will have duplicates of packages.

I've been pondering how the build step can be moved to the consumer most easily. 
I've begun publishing simple-thermostat on NPM and will do so for future cards to easily allow creating your own bundle with NPM or Yarn locally. If you can publish this onto NPM as well I would have 2 cards I can experiment with building locally, which would be great.

What I'm envisioning is to push for the community to:

1. Publish cards on NPM, tagging them with a given keyword
2. Document how to build bundles locally and end up with 1 custom cards bundle
3. Create a new custom component that programmatically manages NPM to install new dependencies and build a bundle. 
4. Get said custom component into HA&lovelace for official support

I would love to take this dialogue somewhere more practical :)

**Comment by iantrich** [comment]
Excellent! I think #devs_frontend on the HA discord is a great place to discuss this further. We should have the ability to create UI editors in a release soon as well. I think balloob is very committed to making custom cards as powerful and easy as possible.

**Comment by kalkih** [comment]
@nervetattoo 
Indeed, shipping one instance of LitElement/lit-html with every custom card is not the most elegant or efficient solution.

Interesting ideas, automating the build process would most likely be one of the key features to get this going. I think the process would have to be accessible, streamlined and easy for the user to setup and use.

I'll publish this project to npm asap when I get home tomorrow.

**Comment by kalkih** [comment]
@nervetattoo npm@[mini-media-player](https://www.npmjs.com/package/mini-media-player)
