### ISSUE TITLE
Visual editor dropdowns not working in 2022.3 Core

### ISSUE THREAD

**Issue by jbeardon** [kalkih/mini-media-player#621]
Hi Guys
It would appear the visual configuration dropdowns are now broken after updating to 2022.3 - cache cleared and have tried multiple browser (including incognito mode)

Dropdowns are now just displayed as a list so the player cannot be configured visually.

I have updated the player to the current stable version which fixed the drop downs for the frontend

![image](https://user-images.githubusercontent.com/14904316/156613267-5f3fe1a3-b249-4714-8bfa-edb4db223c66.png)

**Comment by lfrlucas** [comment]
same issue here

**Comment by lopjos24** [comment]
Same issue on my side. Thanks in advance for the fix 👍

**Comment by Bill-Dung** [comment]
Same issue here, deinstallation, reboot, installation did not help.

**Comment by panzerwaffen** [comment]
I believe this is more of an HA issue.  Same problem with picking cameras on the Frigate Card.

**Comment by jbeardon** [comment]
> I believe this is more of an HA issue. Same problem with picking cameras on the Frigate Card.

It's an HA issue in respect of the the fact that HA have transitioned the front end to material design standards. It's an addon developer issue for ignoring what has been a well publicised and planned change.

**Comment by kalkih** [comment]
Fixed in latest release, sorry for the wait!

**Comment by kalkih** [comment]
Yes in v1.16.2 https://github.com/kalkih/mini-media-player/releases/tag/v1.16.2
