### ISSUE TITLE
Source Dropdown In Card isnt hidden by default

### ISSUE THREAD

**Issue by davidrustingha** [kalkih/mini-media-player#623]
The dropdown menu for the source is shown by default, and its behind other cards (see picture). 

Last working version was 2022.2.X
![Screenshot_1](https://user-images.githubusercontent.com/62120423/156651204-a4842f87-cfbb-455f-b70c-fc75788d6aed.jpg)

**Comment by kalkih** [comment]
Fixed in the latest version of the card, see #606
