### ISSUE TITLE
Dropdown (source/sound/shorcuts) not always expanding

### ISSUE THREAD

**Issue by 03397** [kalkih/mini-media-player#624]
Guys in relation with issue 606, this solves the issue for me but sometimes it is not responding, doing nothing and it is giving me error saying
https://xxxxxxxxxzzzz/hacsfiles/mini-media-player/mini-media-player-bundle.js?hacstag=1485208381160:1:154147 Uncaught SyntaxError: Failed to execute 'querySelector' on 'DocumentFragment': '#9bpap80z7-menu' is not a valid selector.

**Comment by kalkih** [comment]
Does this happen other than when switching in and out of the UI editor?

**Comment by 03397** [comment]
It just happens when  I just hit the arrow to bring the list. But randomly. 
In addition, it happens through the home assistant on my mobile either application or browser
I could not replicate it using a  browser on a laptop 

This is the actual setup I have if it is related.
cards:
  - entity: media_player.sonos_one
    hide:
      info: false
      power: true
      runtime: false
      shuffle: false
    info: scroll
    name: Master Bedroom
    type: custom:mini-media-player
    group: false
  - entity: media_player.sonos_one
    hide:
      controls: true
      icon: true
      info: true
      name: true
      power: true
      progress: true
      source: true
      volume: true
    volume_stateless: true
    type: custom:mini-media-player
    source: full
    sound_mode: full
    artwork: full-cover
    group: false
type: vertical-stack

**Comment by sdotter** [comment]
> Guys in relation with issue 606, this solves the issue for me but sometimes it is not responding, doing nothing and it is giving me error saying https://xxxxxxxxxzzzz/hacsfiles/mini-media-player/mini-media-player-bundle.js?hacstag=1485208381160:1:154147 Uncaught SyntaxError: Failed to execute 'querySelector' on 'DocumentFragment': '#9bpap80z7-menu' is not a valid selector.

I experienced the same thing... 

```
mini-media-player-bundle.js:1 Uncaught (in promise) DOMException: Failed to execute 'querySelector' on 'DocumentFragment': '#8eo551tco-menu' is not a valid selector.
    at ec.firstUpdated (https://rpi-hassio/local/modules/mini-media-player/mini-media-player-bundle.js:1:153520)
    at ec.performUpdate (https://rpi-hassio/local/modules/mini-media-player/mini-media-player-bundle.js:1:131322)
    at https://rpi-hassio/local/modules/mini-media-player/mini-media-player-bundle.js:1:130872
    at Generator.next (<anonymous>)
    at cb (https://rpi-hassio/local/modules/mini-media-player/mini-media-player-bundle.js:1:48215)
    at f (https://rpi-hassio/local/modules/mini-media-player/mini-media-player-bundle.js:1:48399)

```

**Comment by kalkih** [comment]
Thanks for the details.
The reference to themenu is set after the first render of the dropdown, the menu element is proably unmounted/remounted in the DOM which breaks the reference.

Will fix tonight.

**Comment by sdotter** [comment]
Niceee!! Thanks!

**Comment by marph-DE** [comment]
Fix dropdown would be nice, Thanks

**Comment by kongo09** [comment]
Not sure if this is related, but the dropdown also positions itself under the next widget instead of above:

![image](https://user-images.githubusercontent.com/640121/156806590-ee72f484-cabe-4d8e-9dcf-01f1e4190feb.png)

**Comment by kalkih** [comment]
Fixed in latest release
