### ISSUE TITLE
Error of "Specify an entity from within the media_player domain" after 2022.3 update

### ISSUE THREAD

**Issue by DaveCBr** [kalkih/mini-media-player#630]
In addition to the drop down issue, all of my zones now show this error "Specify an entity from within the media_player domain."  

Prior to 2022.3, all zones were working as expected.  my media_player.{area name} zones are a Russound CAV 6.6 and my source is SONOS.

**Comment by DaveCBr** [comment]
Just wondering if this has been looked into or addressed.  The drop down is fixed apparently but this issue persists.

**Comment by kalkih** [comment]
Hello, can you post one of the confurations for the card where you see this issue.

**Comment by rjenx** [comment]
Hi 
This is the card config that generates the error, First attempt using card configuration no entity is added when highlighting the media player. Resorting to adding in the code editor gives this error. 

    `type: custom:mini-media-player
     entity_id: media_player.sky_q
     volume_stateless: false
     volume_step: '1'
     max_volume: '100'
     min_volume: '0'`
 
Results in the error 
![image](https://user-images.githubusercontent.com/64302977/158011659-91b4459b-51c6-4c5b-840e-8127938490e9.png)

**Comment by kalkih** [comment]
Thanks,
Strange, that configuration should never have worked.
Try changing `entity_id` to `entity`.

**Comment by rjenx** [comment]
You star, that worked.  I really strugge sometimes with the way HA format has so many variants. By the way this is my first time using this custom card, it has a lot of potential so I look forward to using it. Many thanks for your help.

**Comment by DaveCBr** [comment]
I figured I would post in this thread since I am in the same exact situation.  The card worked prior to .3 system update.  In my setup, the Source is Sonos and the Zones are Russound and each registered as media_player.kitchen and so on.  

`type: custom:mini-media-player
entity_id: media_player.kitchen
group: false
volume_step: '1'
max_volume: '60'
min_volume: '1'`

**Comment by DaveCBr** [comment]
Please note that I must select the zone now by hand in the code editor.  I can not select the zone from the card configuration screen.  Previously, I could select the player.  

![image](https://user-images.githubusercontent.com/46137958/158026347-d8e015f2-9fb9-4f74-b9af-b66392ccf4db.png)

**Comment by DaveCBr** [comment]
The more I test this, it definitely is a Visual Editor issue.  I also can select how to see cover art and so on with no impact on the card configuration.  I can manually code the card with all of the options and it all seems to work.  This I believe is a visual editor issue along with the "entity_ID" issue

**Comment by kalkih** [comment]
@rjenx 👏🏼 

@DaveCBr Visual editor selects should work again with the latest card version, released last night, make sure you clear cache the browser cache if you see no change in the behaviour.
