### ISSUE TITLE
Show "Browse Media" button on main player

### ISSUE THREAD

**Issue by kksligh** [kalkih/mini-media-player#640]
Maybe I'm doing something wrong, but I can not figure out how to put a browse media action on the mini player.  I have to click into the player's device and click "browse media" to select the media source.  Is this a feature request or is this possible currently?  See my attached image for reference.

CURRENT UX....
![image](https://user-images.githubusercontent.com/83232851/162285892-aa7b3e43-6e68-4c75-91dc-69c5b92a557c.png)

IDEAL UX....

![image](https://user-images.githubusercontent.com/83232851/162286471-3fae237a-7bb4-4dc5-ae5f-d1833af5e671.png)

Sorry for the rough drawings, but just trying to illustrate the idea.

**Comment by kalkih** [comment]
Please see https://github.com/kalkih/mini-media-player/issues/435
