### ISSUE TITLE
Unable to use mini-media-player in development environment

### ISSUE THREAD

**Issue by thierry-rhone** [kalkih/mini-media-player#643]
I'm building a media player for my stb in visual studio code and want to test in with mini-media_player card
but I can't install mini-media_player in my environment.
How It's possible to do that ?

**Comment by kalkih** [comment]
What part of the installation do you get stuck on, what doesn't work?
You should be able to install it like normally, follow the instructions in the [readme](https://github.com/kalkih/mini-media-player#install).

**Comment by thierry-rhone** [comment]
I installed it with hacs. It's appears inside.
![image](https://user-images.githubusercontent.com/65720627/162857006-a30a2f42-e802-474c-be5c-645b7cc9ea1a.png)
but in lovelace I get the message : no card type configured

![image](https://user-images.githubusercontent.com/65720627/162857127-3acc8ffb-8973-4c9a-9732-33d08cee75de.png)

**Comment by kalkih** [comment]
Remove the `-` in front of `type`

**Comment by thierry-rhone** [comment]
Thank's 
Now the car appear but I can't valid it
![image](https://user-images.githubusercontent.com/65720627/162928969-b675201c-ae84-46cf-9fc4-32da64c531f3.png)
