### ISSUE TITLE
Sonos is broken in 2022.4 and 2022.5

### ISSUE THREAD

**Issue by secbitchris** [kalkih/mini-media-player#646]
Endless amounts of this:

Logger: homeassistant.components.sonos
Source: components/sonos/__init__.py:195
Integration: Sonos ([documentation](https://www.home-assistant.io/integrations/sonos), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sonos%22))
First occurred: 9:44:13 PM (233 occurrences)
Last logged: 9:48:15 PM

Failed to connect to configured player '192.168.1.152': UPnP Error 501 received: Action Failed from 192.168.1.152
Failed to connect to configured player '192.168.1.167': UPnP Error 501 received: Action Failed from 192.168.1.167
Failed to connect to configured player '192.168.1.140': UPnP Error 501 received: Action Failed from 192.168.1.140
Failed to connect to configured player '192.168.1.225': UPnP Error 501 received: Action Failed from 192.168.1.225
Failed to connect to configured player '192.168.1.120': UPnP Error 501 received: Action Failed from 192.168.1.120

Both in auto-discovery and with a manual yaml file with all 23 of my speakers IP's added.

Same result.

**Comment by kalkih** [comment]
This issue isn't related to this card but rather the Sonos integration itself, it should instead be raised in [home-assistant/core](https://github.com/home-assistant/core)
