### ISSUE TITLE
v1.16.3 causing cards to disappear

### ISSUE THREAD

**Issue by conorlap** [kalkih/mini-media-player#657]
[v1.16.3](https://github.com/kalkih/mini-media-player/releases/tag/v1.16.3) is causing any cards with the mini-media-player attached to disappear.
I went back to v1.16.2 and everything was fine again.

**Comment by spacegaier** [comment]
What do you mean by "attached"? Single card use works fine for me, meaning the mini-media-player used as its own card.

**Comment by conorlap** [comment]
Issue has resolved itself after a full restart of the HA docker container. Not sure what the cause was as I cleared cache etc. and it still didn't fix it. Happy the full restart did the trick though!

**Comment by ThirteenTX** [comment]
I am having this issue now as well. Reboot did not solve it.

**Comment by kalkih** [comment]
Can you explain the issue in more detail, what do you mean by `any cards with the mini-media-player attached `?

**Comment by conorlap** [comment]
I've got my mini media player cards embedded within custom:stack-in-card and mushroom cards for styling. Can confirm the issue is back again for me.

**Comment by conorlap** [comment]
![Screenshot_20220505-230913_Chrome](https://user-images.githubusercontent.com/57415184/167033666-14e0737a-7346-4d10-9a08-3b3be63aee83.jpg)

**Comment by conorlap** [comment]
How it looks on v1.16.2

on v1.16.3 nothing within that stack of cards shows

**Comment by kalkih** [comment]
Thanks for the information.

Unpublished the latest release for now and made it a beta release instead, will have to look into this further and try to re-create the issue in my environment, any potential error logs or any other additional information is very welcome :)

**Comment by ThirteenTX** [comment]
Mine are also "in a stack cards" Either the default vertical stack from Home assistant or the "Custom: stack in a card" from HACS. Either way both worked before this version. 
![image](https://user-images.githubusercontent.com/51967002/167034271-12c041cb-bca2-4e7b-8f31-4c29d21982bb.png)
![image](https://user-images.githubusercontent.com/51967002/167034291-0c4d309b-c9ac-4956-b054-e4a921ba7393.png)

**Comment by ThirteenTX** [comment]
> Thanks for the information.
> 
> Unpublished the latest release for now and made it a beta release instead, will have to look into this further and try to re-create the issue in my environment, any potential error logs or any other additional information is very welcome :)

I was using Firefox on the latest version. I can try and see if there was any errors I can find in the morning.

**Comment by ThirteenTX** [comment]
I am no web developer but I went poking around and found this in the debugger. Don't know if this helps.
Uncaught (in promise) TypeError: this._attr is undefined get updatedAt mini-media-player-bundle.js:200 get idleView mini-media-player-bundle.js:200 se mini-media-player-bundle.js:200 set hass mini-media-player-bundle.js:1389 value hui-light-card.ts:35 _$AE app.0c493f99.js:1248 performUpdate app.0c493f99.js:1248 scheduleUpdate app.0c493f99.js:1248 _$EC app.0c493f99.js:1248 4 [mini-media-player-bundle.js:200:12603](https://domain.duckdns.org:8123/hacsfiles/mini-media-player/mini-media-player-bundle.js?hacstag=1485208381163)

There was also a learn more button at the bottom of that error which is here https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Unexpected_type . Let me know if there is anything else I can do to assist.

**Comment by spacegaier** [comment]
Can someone please provide a concrete (minimal) example with the corresponding YAML configuration of the bug? Currently there is not much to go on.

Just adding the `mini-media-player` into a HA `vertical-stack`works just fine for me.

```yaml
type: vertical-stack
cards:
  - type: custom:mini-media-player
    entity: media_player.sonos_living_front
```

**Comment by spacegaier** [comment]
Based on the stack trace provided above it looks a bit like the issue here https://github.com/kalkih/mini-media-player/issues/658. Can you please confirm that you are using the idle feature? As a test, if it works without it, then I think this issue here can be closed as a duplicate.

**Comment by ThirteenTX** [comment]
> ```yaml
> type: vertical-stack
> cards:
>   - type: custom:mini-media-player
>     entity: media_player.sonos_living_front
> ```

Sure. 
![image](https://user-images.githubusercontent.com/51967002/167207791-e5913e3f-fa33-414c-8b1a-7a9dc6986cb3.png)
![image](https://user-images.githubusercontent.com/51967002/167208083-40b0f43d-0679-4095-b4f8-f6f17d164a43.png)

It works with the default YAML you provided.

**Comment by spacegaier** [comment]
> It works with the default YAML you provided.

And when does it start failing? Once you enable the idle view feature?

**Comment by ThirteenTX** [comment]
> Based on the stack trace provided above it looks a bit like the issue here #658. Can you please confirm that you are using the idle feature? As a test, if it works without it, then I think this issue here can be closed as a duplicate.

You are correct, this must be the idle view issue as removing it made it show back up.

**Comment by mfabiani53** [comment]
Same problem here. I tried to find 1.16.2 but no success...

**Comment by kalkih** [comment]
v1.16.2 gets unpublished automatically here on GitHub for some strange reason... I've republished it now.
New release should be out tomorrow.
