### ISSUE TITLE
SONOS Unjoin, leave and ungroup functions not working in HA core 2022.5.1

### ISSUE THREAD

**Issue by Jmanitpro** [kalkih/mini-media-player#661]
Speaker group functionality on the SONOS platform can only join a speaker(although the indicator is not working), none of the unjoin or leave functionality is working,  Reverted back to HA core 2022.4.7 and all SONOS join/unjoin functionality works as designed.

5.1 release notes mention a breaking changed related to SONOS
The sonos_group attribute on Sonos media players has been renamed to group_members to align with other integrations.

**Comment by spacegaier** [comment]
For HA 2022.5 you need the card version of at least v1.63 which however has been temporarily pulled due to some other issue.

**Comment by kalkih** [comment]
Thanks for your patience.
New release available, Sonos services updated and previous issues should be fixed, let me know otherwise :)
