### ISSUE TITLE
Css overrides not working

### ISSUE THREAD

**Issue by cowboysdude** [kalkih/mini-media-player#662]
The css overrides aren't working after the 1st one.... 

`style: |
          ha-card {
          margin: 0px 14px -5px 14px
          mini-media-player-artwork-opacity: 9
          }`
Anything after the 1st line is ignored.

**Comment by kalkih** [comment]
This is unrelated to this card, but I believe you're missing a comma
```js
margin: 0px 14px -5px 14px, mini-media-player-artwork-opacity: 9
```
