### ISSUE TITLE
material not displaying correctly in 1.16.3

### ISSUE THREAD

**Issue by Hackashaq666** [kalkih/mini-media-player#665]
material not displaying correctly in 1.16.3, reverting back to 1.16.2 fixes it.

**Comment by spacegaier** [comment]
That is way too little information for someone to help you. What is your exact card config setup? What exactly is not correctly displayed?

**Comment by Hackashaq666** [comment]
Thank you for your reply, apologies for the lack of detail. The card setup is pasted below. In 1.16.3 the material artwork shows correctly but the dynamic colors are missing. It works as expected with artwork and dynamic colors in versions <1.16.3.

`entities:
  - type: custom:mini-media-player
    entity: media_player.forked_daapd_server
    hide: null
    source: icon
    artwork: material
`

**Comment by kalkih** [comment]
Thanks for your patience.
New release available, should fix these issues, let me know otherwise :)
