### ISSUE TITLE
sonos_group

### ISSUE THREAD

**Issue by moshiko2312** [kalkih/mini-media-player#666]
attribute on Sonos media players has been renamed to **group_members** to align with other integrations.

**Comment by spacegaier** [comment]
Yes, and I had already updated this card a few days ago to account for that 😉: https://github.com/kalkih/mini-media-player/pull/656

Card v.1.16.3 contains the fix.

**Comment by moshiko2312** [comment]
1.16.3 ? can you send a link ?

**Comment by spacegaier** [comment]
https://github.com/kalkih/mini-media-player/releases/tag/v1.16.3

Looks like the release was now completely pulled by @kalkih (it was originally reverted back to a beta release on HACS due to another found bug).

**Comment by moshiko2312** [comment]
its working :-)
Thank you very much

**Comment by moshiko2312** [comment]
Thank you very much
