### ISSUE TITLE
Source menu always open on Brave browser

### ISSUE THREAD

**Issue by idogrf** [kalkih/mini-media-player#671]
Hi,

Recently updated home assistant to 2022.5 and the mini-media-player card to 1.16.4

For some reason, when I use Brave browser, the sources menu of the card is always shown - 
![image](https://user-images.githubusercontent.com/15867904/168314499-cc067399-ca5f-44d1-94e9-c8eed1f0bf9b.png)

I tried this on chrome and on edge and the menu works fine there...
Also tried reverting back to default theme to see if that has anything to do with it, getting the same...

I also get the same issue when trying to edit the UI with the visual editor - all the menus are open - 
![image](https://user-images.githubusercontent.com/15867904/168314832-02e0f818-8d5b-4e9b-9be6-3912341fa2e0.png)

This does not happen for other cards which use drop-down menus such as input_booleans or any other card in the visual editor

**Comment by kalkih** [comment]
Hey, my guess is that an older version of the card is being loaded from cache, try clearing the browser cache.

You could also confirm this theory by opening HA in an incognito tab in Brave, and see if the issue is gone.
