### ISSUE TITLE
Volume control issue since HA 2022.5.X

### ISSUE THREAD

**Issue by ALaDoffe** [kalkih/mini-media-player#672]
Hello 

Env : HA 2022.05.03, MMP 1.6.4, Sonos Speakers

Since the latest HA updated the "main" volume slider does not control voume. 
When opening the card, volume slider  works fine.
When grouped with sync_volume option main slider changes only secondary speakers volume and the slider in the open card control only this speaker and it is not sync over group.

[HA_MMP_card.txt](https://github.com/kalkih/mini-media-player/files/8694666/HA_MMP_card.txt)

Thanks for your help

**Comment by ALaDoffe** [comment]
Am i alone that have this issue ? :-)

**Comment by jdiegmueller** [comment]
> Am i alone that have this issue ? :-)

My issue is that when i have speaker_group I can mute/unmute but it only affects the primary entity.  I can't adjust volume from the card, although if I click on the entity to bring up more-info I can adjust the volume there.  Group'ing doesn't seem to work either.  Still investigating.

**Comment by jdiegmueller** [comment]
> My issue is that when i have speaker_group I can mute/unmute but it only affects the primary entity. I can't adjust volume from the card, although if I click on the entity to bring up more-info I can adjust the volume there. Group'ing doesn't seem to work either. Still investigating.

Ok, this was my fault.  The issue I was having is that if I listed one or more of the speaker_group entities with entity: instead of entity_id:, the entry would still show up .. but it would effectively break all grouping.  Once I changed the entity: entries to entity_id: I was back in business, including sync_volume+volume_offset.  I'm on 2022.5.4.

**Comment by richie-svk** [comment]
> Am i alone that have this issue ? :-)

No, having the same issue here.

**Comment by danoc** [comment]
I was having those same until I updated to the latest version of mini-media-player.

**Comment by spencer-scott** [comment]
T

> > My issue is that when i have speaker_group I can mute/unmute but it only affects the primary entity. I can't adjust volume from the card, although if I click on the entity to bring up more-info I can adjust the volume there. Group'ing doesn't seem to work either. Still investigating.
> 
> Ok, this was my fault. The issue I was having is that if I listed one or more of the speaker_group entities with entity: instead of entity_id:, the entry would still show up .. but it would effectively break all grouping. Once I changed the entity: entries to entity_id: I was back in business, including sync_volume+volume_offset. I'm on 2022.5.4.

Thanks for updating your problem because I was doing the same thing and it helped me hunt to the right spot.

**Comment by vantech14** [comment]
@spencer-scott I am having the same issue. Can you confirm what you did to fix it? 

For me, the main volume slider does not control the entity it's attached to, but does control its grouped speakers. 

Any help would be appreciated. 

Thanks.

**Comment by Vansmak** [comment]
> Hello
> 
> Env : HA 2022.05.03, MMP 1.6.4, Sonos Speakers
> 
> Since the latest HA updated the "main" volume slider does not control voume. When opening the card, volume slider works fine. When grouped with sync_volume option main slider changes only secondary speakers volume and the slider in the open card control only this speaker and it is not sync over group.
> 
> [HA_MMP_card.txt](https://github.com/kalkih/mini-media-player/files/8694666/HA_MMP_card.txt)
> 
> Thanks for your help

I know this post is 5 mos ago but I am having this same issue on latest ha and latest mini

**Comment by lampenlampen** [comment]
I had the same issues and this (#695) fixed the problem for me.
