### ISSUE TITLE
Sonos grouping button not showing in iOS Home Assistant app

### ISSUE THREAD

**Issue by sholder89** [kalkih/mini-media-player#68]
The Sonos grouping button disappears when viewing in the Home Assistant iOS app.

iOS App: https://i.imgur.com/plidkXM.jpg

Chrome on iOS: https://i.imgur.com/UcofbdB.jpg

iPhone X, iOS 12.1.3, Home Assistant Companion 1.5.0, mini-media-player 0.9.8, Home Assistant 0.86.1

**Comment by sholder89** [comment]
This resolved itself after some time. Guessing it was a caching issue.

**Comment by kalkih** [comment]
Sounds like a caching issue indeed, but good to know, thanks!
