### ISSUE TITLE
Source missing from the mini-media-player card

### ISSUE THREAD

**Issue by ScottGA** [kalkih/mini-media-player#686]
Sometime fairly recently, I noticed that the "Source" icon is missing from all my mini-media-player cards.  I've tried switching the source setting from "icon" to "full" without any change in the cards.  I've also confirmed that source is not set to hide.    I don't know what happened.  There used to be the drop down arrow I could click that would bring up the list of Sonos Favorite channels.  Now there is no sign of that drop down arrow.

**Comment by zstonez** [comment]
> Sometime fairly recently, I noticed that the "Source" icon is missing from all my mini-media-player cards. I've tried switching the source setting from "icon" to "full" without any change in the cards. I've also confirmed that source is not set to hide. I don't know what happened. There used to be the drop down arrow I could click that would bring up the list of Sonos Favorite channels. Now there is no sign of that drop down arrow.

**Comment by zstonez** [comment]
Hi
did you got this issue solved?

**Comment by StephanSchuster** [comment]
@ScottGA: I have the same behavior: no source selection. How did you fix it?

**Comment by StephanSchuster** [comment]
Okay, I see ...
https://github.com/kalkih/mini-media-player/issues/642
