### ISSUE TITLE
Request: Please add support for custom updater

### ISSUE THREAD

**Issue by rpitera** [kalkih/mini-media-player#7]
[Custom Updater project](https://github.com/custom-components/custom_updater)

This project is helping us keep track of custom cards and components.  It would be awesome if you added the required JSON file to your repo to help us to know when you have a new version out!

**Comment by kalkih** [comment]
Support for the [custom_updater](https://github.com/custom-components/custom_updater) component added in master with [v0.8.2](https://github.com/kalkih/mini-media-player/releases/tag/v0.8.2)

**Comment by rpitera** [comment]
Thanks for your awesome card as well as your awesome support!!
