### ISSUE TITLE
Sonos group management not working

### ISSUE THREAD

**Issue by jansenfd** [kalkih/mini-media-player#702]
Running 1.16.4

The group option for Sonos is not working anymore. Error message: 
_**Failed to call service sonos/join. Service not found.**_

> Home Assistant 2022.8:
> 
> BREAKING CHANGE - The sonos.join and sonos.unjoin services will be removed in 2022.8 in favor of the standard media_player.join and media_player.unjoin services.

Hope it can be fixed easily.

**Comment by spacegaier** [comment]
Are you really sure you are running 1.16.4 because I had fixed the issue you reported here in https://github.com/kalkih/mini-media-player/pull/656 which is part of 1.16.4.

If you are on that version, please refresh your browser cache.

**Comment by jansenfd** [comment]
Going to double check it right now. Keep you updated

**Comment by jansenfd** [comment]
Fault from my end, works like a charm :)
