### ISSUE TITLE
Outline border appears once updated to 2022.11

### ISSUE THREAD

**Issue by TimBeekman** [kalkih/mini-media-player#704]
![image](https://user-images.githubusercontent.com/89469564/199685316-b61674f5-a11f-4ae8-b992-2eb958c85452.png)

Once added to an card, an outline appears

**Comment by aheath70** [comment]
Same issue here, caused by changes to the HA UI in 2022.11.

**Comment by mikekay1** [comment]
Same issue here, I am guessing an update is coming soon -- I think in the linked ticket above there was a merge requested

**Comment by kalkih** [comment]
New release available, thanks to @breakthestatic for the fix!

**Comment by mikekay1** [comment]
Thank you so much for the fix and even faster pull and merge... Sorry to reopen this but I am still seeing the borders and have updated everything. Any ideas?

![image](https://user-images.githubusercontent.com/52670539/201392953-0f2fd09e-bd3d-4def-9432-079312ec1f9e.png)

**Comment by mikekay1** [comment]
I just deleted cache and refreshed :| and it worked, have a great weekend. Thanks again for all your hard work!

**Comment by tomlut** [comment]
I have the opposite problem. Sine the merging of this PR I can no longer apply a border.
