### ISSUE TITLE
Progress not visible with group true

### ISSUE THREAD

**Issue by akpuggy** [kalkih/mini-media-player#71]
When setting group to true, the progress bar is not visible (although still functional if that area is clicked). 

![image](https://user-images.githubusercontent.com/35150876/52255164-5dead580-28df-11e9-8cfd-34b0e6862018.png)

**Comment by kalkih** [comment]
Resolved in the latest release [v1.0.1](https://github.com/kalkih/mini-media-player/releases/tag/v1.0.1).
Thanks!
