### ISSUE TITLE
Sonos sync_volume bugged

### ISSUE THREAD

**Issue by kalkih** [kalkih/mini-media-player#72]
From: https://community.home-assistant.io/t/lovelace-mini-media-player/68459/604?u=kalkih

> seems I found a bug with the sync_volume options for the Sonos Group
evenif I have not grouped my Sonos Player the volume will be synced across both players (see video)
![video](https://community-home-assistant-assets.s3.dualstack.us-west-2.amazonaws.com/original/3X/7/0/70a1091fd88eb87a5bf6dab4eeb76d523393d904.gif)

>I get also two error messages in my log
>
>>Error doing job: Task exception was never retrieved
>>Traceback (most recent call last):
>>File “/usr/lib/python3.5/asyncio/tasks.py”, line 241, in _step
>>result = coro.throw(exc)
>>File “/srv/homeassistant/lib/python3.5/site-packages/homeassistant/helpers/service.py”, line 289, in _handle_service_platform_call
>>await func(entity, data)
>>File “/usr/lib/python3.5/asyncio/futures.py”, line 380, in iter
>>yield self # This tells Task to wait for completion.
>>File “/usr/lib/python3.5/asyncio/tasks.py”, line 304, in _wakeup
>>future.result()
>>File “/usr/lib/python3.5/asyncio/futures.py”, line 293, in result
>>raise self._exception
>>File “/usr/lib/python3.5/concurrent/futures/thread.py”, line 55, in run
>>result = self.fn(*self.args, **self.kwargs)
>>File “/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/media_player/init.py”, line 515, in set_volume_level
>>raise NotImplementedError()
>>NotImplementedError
>
>and
>
>>Not passing an entity ID to a service to target all entities is deprecated. Use instead: entity_id: “all”

>Attributes from the master player:
>
>>shuffle: false
>>sonos_group: media_player.schlafzimmer
>>supported_features: 64063
>>media_content_type: music
>>volume_level: 0.2
>>source_list: B5 aktuell,ego FM,PULS,Superfly FM
>>friendly_name: Schlafzimmer
>>entity_picture: /api/media_player_proxy/media_player.schlafzimmer?token=fc9a990b7b815d96a423b762c3a5bf45a832357d25dea9c3d8457330f3da75a5&cache=bef7ea045c969302
>>source: Superfly FM
>>is_volume_muted: false
>>media_title: Superfly FM
>>media_artist:
>
>Attributes from the second player:
>
>>shuffle: false
>>sonos_group: media_player.bad
>>supported_features: 64063
>>media_content_type: music
>>volume_level: 0.13
>>source_list: B5 aktuell,ego FM,PULS,Superfly FM
>>friendly_name: Bad
>>entity_picture: /api/media_player_proxy/media_player.bad?token=61c77b9d8b325ae63561a9c872b5b881defa4cb412b030cdab9b1050b62f7252&cache=078729dbdf6a88fe
>>source: Superfly FM
>>is_volume_muted: false
>>media_title: Superfly FM
>>media_artist:
>
>when ever I can help to test please let me know

**Comment by maddox** [comment]
I'm seeing the opposite, `sync_volume` is having no effect.

**Comment by kalkih** [comment]
Might be different depending on what version of HA you run.
I believe they made a change to how entity targeting works in service calls recently.
However I've got a fix in place, will release tonight or tomorrow.

**Comment by maddox** [comment]
I'm on the latest.

👍

**Comment by deluxestyle** [comment]
> However I've got a fix in place, will release tonight or tomorrow.

good to hear. looking forward to it

**Comment by kalkih** [comment]
@maddox @deluxestyle 
Should be resolved with [v1.0.1](https://github.com/kalkih/mini-media-player/releases/tag/v1.0.1),
I've only been able to test with dummy data, since I don't own any Sonos myself but should work as expected now, please let me know the results.

**Comment by deluxestyle** [comment]
it seems to work for me. Thank you

**Comment by kalkih** [comment]
Okay, closing this since that appears to have solved the issue!
Thanks!
