### ISSUE TITLE
Number in card name when media player group is used as Entity

### ISSUE THREAD

**Issue by Dillton** [kalkih/mini-media-player#768]
Hello.

I am using group of 3 speakers for whole apartment and in the name of card there is a name with +2, see screen below.
I think this is realated to number of devices in group but I am curious if I can get rid of this +2 somehow.
Also this +2 is not affected when changing the name cards name.
I have tried native media control and mushroom media card where only name is shown so I believe this is problem here in mini media player.
Anyone encountered similar behaviour?

![image](https://github.com/kalkih/mini-media-player/assets/68992112/68e2cc04-7fc1-4d27-9a50-472329a185f7)

**Comment by Traxtar928** [comment]
I also want to know this

**Comment by MrHashimoto** [comment]
yes, same here...

**Comment by killerwahn** [comment]
Same here, solution highly appreciated

**Comment by Dillton** [comment]
Found the solution when refactoring my dashboard.
Basically even if you don't use speaker_group functionality within mini media player this is happening.
All you have to do is add the following 2 lines of code in your mini media player config:
![image](https://github.com/kalkih/mini-media-player/assets/68992112/98835462-f9c4-47d8-a15c-78df9e8e5cad)

**Comment by killerwahn** [comment]
Thanks a lot, works like a charm!
