### ISSUE TITLE
Enlarge icon size of control buttons?

### ISSUE THREAD

**Issue by Rudd-O** [kalkih/mini-media-player#773]
How would I go about enlarging the icon size of the control buttons?  There seems to be no option to do so.  Thanks.

**Comment by kalkih** [comment]
There's a `scale` option, see https://github.com/kalkih/mini-media-player#card-options

If it works as intended it should scale the size of the card elements, including the buttons.

`scale: 1` === 100% normal sizing
`scale: 1.25` === 125% of the normal size
...etc

**Comment by Rudd-O** [comment]
No, this is not what I want.  I don't want to scale the whole card.  I want to scale just the buttons.

Please reopen.  Thanks.
