### ISSUE TITLE
Progress Bar invisible

### ISSUE THREAD

**Issue by Emilef22** [kalkih/mini-media-player#784]
Hi! The progress bar of all my media players (sonos, android tv, chromecast) is invisible. 
Thanks a lot!

type: vertical-stack
cards:
  - type: conditional
    conditions:
      - entity: input_boolean.media
        state: 'on'
    card:
      type: custom:mini-media-player
      entity: media_player.unnamed_room_2
      group: true
      volume_stateless: false
      toggle_power: true
      artwork: cover
      hide:
        power: true
      speaker_group:
        platform: sonos
        show_group_count: true
        entities:
          - entity_id: media_player.unnamed_room_2
            name: Salon
          - entity_id: media_player.unnamed_room
            name: Cuisine
          - entity_id: media_player.salon
            name: Sous-Sol
          - entity_id: media_player.garage_2
            name: Garage
          - entity_id: media_player.chambre_3
            name: Bureau
          - entity_id: media_player.sonos_roam
            name: Sonos Roam

**Comment by Jaykurb** [comment]
My buttons are invisible now.

**Comment by SDR3078** [comment]
It seems like all buttons are invisible

**Comment by Jaykurb** [comment]
I resolved this by removing all resources to do with mini player. Refreshing so that my cards broke. 

I then restarted HA, installed the card the card again and it was all sorted.

**Comment by SDR3078** [comment]
Did this also work for TTS input for you? Did not seem to work for me...

**Comment by Jaykurb** [comment]
I haven't got TTS  implemented on my mini media player cards. 

However, when I was trying to resolve my invisible buttons issue, I did enable TTS function quickly and it seemed to show (even when the buttons were invisible).

**Comment by Emilef22** [comment]
It dont resolved the progress bar for me

**Comment by ASNNetworks** [comment]
Correct, seems like 2023.11.X has broken this somehow. In my case I have the progress bar color declared in the theme.yaml and color it there. Perhaps something with themes in 2023.11 has changed?

**Comment by cataseven** [comment]
Same problem here. It is there but fully trasnparent

**Comment by marcis92** [comment]
> Correct, seems like 2023.11.X has broken this somehow. In my case I have the progress bar color declared in the theme.yaml and color it there and use var(--) in the card. Perhaps something with themes in 2023.11 has changed?

Hi @ASNNetworks, which variable have you used for the progress bar coloring?

**Comment by WallyDW** [comment]
The same is an issue with ballons on slider-row-entity cards.
There is a fix for it in the PR here which might be of help to solve thise one too.
https://github.com/thomasloven/lovelace-slider-entity-row/issues/279

**Comment by johanfrick** [comment]
Progress bar also stopped working in my Sonos Card after 2023.11, the fix was quite easy in the end. Just use a div with colored background, instead of `<paper-progress>`.
https://github.com/johanfrick/custom-sonos-card/commit/b67505cc222129b0b6baba0835bfc0f21abeeef5

**Comment by Boh1** [comment]
Possibly related, but the volume sliders are no longer showing numerical values above them any more after 2023.11.x .

**Comment by regystro** [comment]
In the meantime, does anyone know if that's fixable with card-mod CSS styles?

**Comment by flyman1664** [comment]
> Possibly related, but the volume sliders are no longer showing numerical values above them any more after 2023.11.x .

Change "ignore-bar-touch pin" by "ignore-bar-touch labeled pin". It fixes the issue ;)

**Comment by Boh1** [comment]
I'm getting the impression that we will soon all be maintaining our own branches of this code.

**Comment by flyman1664** [comment]
If anyone can figure out how to modify the card file to get the progressive bar working again would be very appreciated. I looked at @johanfrick modification but don't get what to change exactly in the file. Is the paper-progress element can be changed to an other variable?

Thank you in advance!

**Comment by johanfrick** [comment]
I can take a look, but won't be able to do so until next week.

**Comment by johanfrick** [comment]
@Drafteed @Californian Care to take a look?
(tagged you based on this: https://github.com/kalkih/mini-media-player/issues/789#issuecomment-1818949303)
