### ISSUE TITLE
TTS input field disappeared with last update of Home Assistant (2023.11.0)

### ISSUE THREAD

**Issue by SDR3078** [kalkih/mini-media-player#785]
TTS input field disappeared 

![image](https://github.com/kalkih/mini-media-player/assets/82957942/d3496369-5a94-4720-b42c-a405df7f066e)

**Comment by freirejc** [comment]
Same issue here.

**Comment by bernikr** [comment]
just referencing a fix in another custom card for the devs: bernikr/lovelace-notify-card#20

**Comment by TheSimTek** [comment]
same here.  tried reinstalling card without success.

**Comment by a1xs** [comment]
![image](https://github.com/kalkih/mini-media-player/assets/35153440/649f199e-fd8b-4c79-8f84-37d13998026c)

**Comment by Sinitronics** [comment]
There's a pull request in to fix the issue but looks like the project is dead in the water. 
#786

**Comment by flyman1664** [comment]
Seems to be an issue with paper-input being depreciated. But not sure what to change in the js file to make it work again.

**Comment by Stef42300** [comment]
same problem

**Comment by freirejc** [comment]
> Seems to be an issue with paper-input being depreciated. But not sure what to change in the js file to make it work again.

I've tried to apply the below change but didn't work. 


[https://github.com/bernikr/lovelace-notify-card/commit/88761d4d742ce588a05344941278d0cf6026c4d4]

**Comment by sonyboypatrick** [comment]
> There's a pull request in to fix the issue but looks like the project is dead in the water. #786

Thanks for the hint. This does the trick!

**Comment by a1xs** [comment]
I changed the "paper-input" field to "ha-textfield" in the files "/config/www/mini-media-player-bundle.js" and "/config/www/community/mini-media-player/mini-media " -player-bundle.js" And everything started working! Thank you!
![image](https://github.com/kalkih/mini-media-player/assets/35153440/95547f1c-0837-46ab-a470-d60d5a4702a1)

**Comment by Emilef22** [comment]
Did you change all the 29 paper-input fields?

**Comment by freirejc** [comment]
> Did you change all the 29 paper-input fields?
> 
> 
> 
> 

Good question. I was wondering the same.

**Comment by a1xs** [comment]
> Did you change all the 29 paper-input fields?

Yes, I did. The send button never worked, but I didn’t need it

**Comment by TheSimTek** [comment]
Changed all paper-input fields to ha-textfield but still no tts function.  Anyone had success yet?

**Comment by sonyboypatrick** [comment]
Just replace all references to paper-input with ha-textfield in the js file and compress the new js file with gzip

**Comment by sonyboypatrick** [comment]
> Changed all paper-input fields to ha-textfield but still no tts function. Anyone had success yet?

Just replace all references to paper-input with ha-textfield in the js file and compress the new js file with gzip

**Comment by TheSimTek** [comment]
Thanks sonyboypatrick but this did not work.  Both the js and gz have ha-textfield but there is still no TTS functionality.

**Comment by sonyboypatrick** [comment]
Have you cleared your cache? For me it took a few minutes to appear. You could double check: https://yourhomeassistanturl/hacsfiles/mini-media-player/mini-media-player-bundle.js if you missed any paper-input

This is my config

`type: custom:vertical-stack-in-card
cards:
  - type: vertical-stack
    title: Nachricht
    cards:
      - type: custom:mini-media-player
        entity: media_player.echo_show_buro
        artwork: none
        group: false
        tts:
          platform: alexa
        enity_id: media_player.echo_show_buro
        hide:
          icon: true
          source: true
          progress: true
          controls: true
          volume: true
          info: true
          power: true
          name: true
        card_mod:
          style: |
            ha-card {
              border: none;
              box-shadow: none;
            }  `

**Comment by dysphasi** [comment]
As @sonyboypatrick said, if after making the changes to the .js file you aren't seeing the text input boxes still, do make sure to relaod the cache on your frontend. 

Once you've done this everything should work just fine without any changes to your card in lovelace.

This is simple in a browser.
For the iOS app, it's a bit different: Side bar -> Settings -> Companion App ->  Debugging -> Resent frontend cache (you may need to do a 'swipe-down' to reload the page from the Home Aisstant lovelac screen).

In android, again a bit different: go to your android OS settings (the system settings, not in the HA app) -> Apps storage -> Home Assistant -> Clear Cache.

**Comment by Stef42300** [comment]
![2023-11-06_14-21-10](https://github.com/kalkih/mini-media-player/assets/96921482/dfd7740f-bb23-44c8-9ddc-6320a8d1506d)
I have a problem, I replace all 29 references to paper-input with ha-textfield in the js file and compress it. I copied the 2 files in the folder but an error appear
![2023-11-06_14-24-33](https://github.com/kalkih/mini-media-player/assets/96921482/876c8d40-1dda-406f-93f1-4a99767ed574)

I made a mistake but where ?

**Comment by TheSimTek** [comment]
After repeating the steps to replace all paper-input with the ha-textfield in the js file and compress it I am in the same situation as Stef42300.  The custom element does not exist.

Anyone got the two files that work in a dropbox for us to try?  Is there other settings in the configuration.yaml that were needed?

**Comment by flyman1664** [comment]
> As @sonyboypatrick said, if after making the changes to the .js file you aren't seeing the text input boxes still, do make sure to relaod the cache on your frontend.
> 
> Once you've done this everything should work just fine without any changes to your card in lovelace.
> 
> This is simple in a browser, just follow your usual broswer cache reset procedure.
> 
> For the iOS app, it's a bit different: Side bar -> Settings -> Companion App -> Debugging -> Resent frontend cache (you may need to do a 'swipe-down' to reload the page from the Home Aisstant lovelac screen).
> 
> In android, again a bit different: go to your android OS settings (the system settings, not in the HA app) -> Apps storage -> Home Assistant -> Clear Cache.

Try to delete .gz file from the directory

**Comment by flyman1664** [comment]
> ![2023-11-06_14-21-10](https://user-images.githubusercontent.com/96921482/280721856-dfd7740f-bb23-44c8-9ddc-6320a8d1506d.png) I have a problem, I replaced all 29 references to paper-input with ha-textfield in the js file and compress it. I copied the 2 files in the folder but an error appear when I cleared the browser cache ![2023-11-06_14-24-33](https://user-images.githubusercontent.com/96921482/280722645-876c8d40-1dda-406f-93f1-4a99767ed574.png)
> 
> I made a mistake but where ?

Try to delete .gz file from the directory

**Comment by Stef42300** [comment]
> ha-textfield

Thanks, it works! You must delete the "mini-media-player-bundle.js.gz" and it generate a new file named "mini-media-player-bundle.js.bak"
![image](https://github.com/kalkih/mini-media-player/assets/96921482/316a4c3f-a747-4fe9-baef-d5ef05883e6e)

**Comment by freirejc** [comment]
So let's see if it is the step by step:
1. replace all paper-input with the ha-textfield in the js file
2. Delete the compressed file
3. Restart HA and clear the cash

Is it right?


> Thanks, it works! You must delete the "mini-media-player-bundle.js.gz" and it generate a new file named "mini-media-player-bundle.js.bak"
> 
> ![image](https://github.com/kalkih/mini-media-player/assets/96921482/316a4c3f-a747-4fe9-baef-d5ef05883e6e)
> 
> I restart an cleared the cache and it's good.
> 
> ![image](https://github.com/kalkih/mini-media-player/assets/96921482/5b104327-aeb5-4c10-a81b-20aa5ee743b5)
> 
>

**Comment by Stef42300** [comment]
> So let's see if it is the step by step:
> 
> 1. replace all paper-input with the ha-textfield in the js file
> 2. Delete the compressed file
> 3. Restart HA and clear the cash
> 
> Is it right?
> 
> > Thanks, it works! You must delete the "mini-media-player-bundle.js.gz" and it generate a new file named "mini-media-player-bundle.js.bak"
> > ![image](https://user-images.githubusercontent.com/96921482/281123377-316a4c3f-a747-4fe9-baef-d5ef05883e6e.png)
> > I restart an cleared the cache and it's good.
> > ![image](https://user-images.githubusercontent.com/96921482/281124195-5b104327-aeb5-4c10-a81b-20aa5ee743b5.png)

Yes 😉

**Comment by TheSimTek** [comment]
Now working as above.  Many thanks for the assistance in getting this feature back up and running.

**Comment by freirejc** [comment]
> > So let's see if it is the step by step:
> > 
> > 1. replace all paper-input with the ha-textfield in the js file
> > 2. Delete the compressed file
> > 3. Restart HA and clear the cash
> > 
> > Is it right?
> > > Thanks, it works! You must delete the "mini-media-player-bundle.js.gz" and it generate a new file named "mini-media-player-bundle.js.bak"
> > > ![image](https://user-images.githubusercontent.com/96921482/281123377-316a4c3f-a747-4fe9-baef-d5ef05883e6e.png)
> > > I restart an cleared the cache and it's good.
> > > ![image](https://user-images.githubusercontent.com/96921482/281124195-5b104327-aeb5-4c10-a81b-20aa5ee743b5.png)
> 
> Yes 😉

Tnx...

all working now!
SUPER

**Comment by richsimpson** [comment]
Great work on the solution. Worked for me

**Comment by sekonicpr** [comment]
Hi:
Thanks now I have the tts again. I don't know if it has to do with the change but every time I send a TTS on Alexa it ends up with a noise that it didn't make before. 
Is there a way to change the theme (see pic) to make it look transparent?

![image](https://github.com/kalkih/mini-media-player/assets/40529944/cc65f811-1079-4531-8530-129bfed3c1e1)

**Comment by SDR3078** [comment]
The solution worked for me en for others, I will close the issue.

**Comment by SDR3078** [comment]
The solution worked for me en for others, I will close the issue.

**Comment by Korpip** [comment]
Why close this?  It is still not a rolled out solution.

**Comment by zenderman** [comment]
> I changed the "paper-input" field to "ha-textfield" in the files "/config/www/mini-media-player-bundle.js" and "/config/www/community/mini-media-player/mini-media-player-bundle.js" And everything started working! Thank you! ![image](https://user-images.githubusercontent.com/35153440/280535606-95547f1c-0837-46ab-a470-d60d5a4702a1.png)

Thanks it helped me!

**Comment by SDR3078** [comment]
> Why close this? It is still not a rolled out solution.

I'll reopen, you're right

**Comment by bkr1969** [comment]
This is a stupid question, but can someone step-by-step "clear the cache?' I do not want to go into Google and clear the cache as all my passwords will be lost (the way I usually do it).  Is there a simpler way?

**Comment by bkr1969** [comment]
This has not worked for me at all.  Edited the .js file, deleted the .gz, recompressed the .js, cleared the cache, restarted, nothing different.

**Comment by GigaVik** [comment]
> У меня это вообще не сработало. Отредактировал файл .js, удалил .gz, повторно сжал .js, очистил кеш, перезапустил, ничего особенного.

I didn't squeeze anything. Just fixed .js and removed .gz. Restarted HA.
Another correct way to clear the application and browser cache is:
For Chrome:
1. In your browser, type the key combination Ctrl + Shift + Delete. After this, the “Clear history” page will automatically open in the settings.
2. Check only the “Images and other files saved in cache” checkbox. Then select the desired time range from the drop-down list.
Passwords and authorizations are saved (they are in cookies).

**Comment by christopher-lambe** [comment]
The fix worked for me.. Grabbed the file with winscp and compressed it to gzip with 7-zip and copied it back again

**Comment by TechEnthusiastHA** [comment]
I'm fairly "green" to HA and the learning curve has been tremendous.

So far I've replaced all instances of "paper-input" to "ha-textfield"
then I deleted the .gz file.

My questions now are the next steps:
1) how do I compress the file to produce the .bak file? I'm using Studio Code Server in the Desktop App.
2) is it necessary to clear the cache in the browser if I am doing this all in the desktop app? It doesnt make sense to me so I'm just trying to understand.

**Comment by dysphasi** [comment]
1. You can use an app such as 7-zip to compress in the correct format.
However, I believe you should be fine to just delete the gz file and a new
one will be made automatically - someone correct me please if I'm wrong.

2. Yes, you absolutely need to clear browser cache if you wish to see the
changes right away. Else it will just show what was already there, the
newly adapted file will not be used, only what has been pre-stored into the
browser cache. Cache provides means for faster access/loading of a
site/page that has already been opened before. When the same site is loaded
after the browser is closed, it's like a snapshot of an instance...

**Comment by TechEnthusiastHA** [comment]
Maybe I’m missing a step but I don’t see how to force it to generate a new compressed file as some have stated on here. I did use the 7-zip file and uploaded the file named .js.bak to the folder and also cleared cache cookies from chrome and edge. No dice. Will keep seeing what I’m doing wrong.

**Comment by TechEnthusiastHA** [comment]
Guys I figured it out, I didn’t hit save in the studio editor. Everything looks good now, thank you!
