### ISSUE TITLE
Parse or Strip tags in media names

### ISSUE THREAD

**Issue by LordBoos** [kalkih/mini-media-player#79]
Hi, I'm using this card with Kodi and some addons use tags in media names which looks bad on the card.

Can you strip the tags or style text according to those tags?

Steps to reproduce: 
1. play media with stylized title from Kodi addon 
2. look at the lovelace card
3. title looks bad: [I]12:15[/I] [B]Svatební Zvony[/B] ([LIGHT]Prima MAX[/LIGHT]) - CZ (2016)

Expected behavior:
- title will have tags stripped down: 12:15 Svatební Zvony (Prima MAX) - CZ (2016)
- title will be styled according to tags: _12:15_ **Svatební Zvony** (Prima MAX) - CZ (2016)

**Comment by kalkih** [comment]
Does the default `media-control` card do this?
And what are those add-ons you mention.

**Comment by Boosik** [comment]
Default media-control card does not do this.
Addon I encountered it with is Stream Cinema CZ/SK, but other addons also use format codes.
Addon github: https://github.com/bbaronSVK/plugin.video.stream-cinema
Repository: https://kodi-czsk.github.io/repository/
Repository github: https://github.com/kodi-czsk/repository

**Comment by kalkih** [comment]
Okay, thanks for the information.
Unfortunately, I don't think I will add this functionality.
I feel like the use case is just too specific.

**Comment by iantrich** [comment]
A possible alternative would be regex support.

**Comment by kalkih** [comment]
Maybe, but unless someone comes with a PR for it and it doesn't add too much complexity, I don't see it happening. 😉

**Comment by kalkih** [comment]
I'm gonna go ahead and close this as I don't see it happening.
