### ISSUE TITLE
Volume slider knob no longer shows state value on hover or action, broken by HA update 11.x

### ISSUE THREAD

**Issue by jksalvo** [kalkih/mini-media-player#794]
The volume slider knob no longer shows the state value on hover or action.  This was apparently caused by a change in the November 2023 HA update that affected all custom component slider knobs.  I updated the other components that use sliders but was still having problems with all of them until I removed the Mini Media Player resource, reinstalled the component via HACS (perhaps unnecessary), then added the MMP resource back.  This fixed the other sliders (although not in the companion app, for some reason) but not the ones for MMP.

Thanks!

**Comment by djgrazzy** [comment]
Awesome, thanks for the quick reply..

**Comment by jksalvo** [comment]
This worked perfectly and fixed all the problems in the app as well, thank you for your help!
