### ISSUE TITLE
HACS url to the local resource seems to have changed

### ISSUE THREAD

**Issue by arner** [kalkih/mini-media-player#814]
On the latest home assistant + HACS 1.33.0, the js file gets downloaded to config/www/community/mini-media-player/mini-media-player-bundle.js.

Instead of configuring the resource as `/local/mini-media-player-bundle.js?v=1.16.8` (which failed), this worked for me: `/local/community/mini-media-player/mini-media-player-bundle.js?v=1.16.8`.

**Comment by Drafteed** [comment]
HACS automatically sets resources of card. You don't need to specify them manually.
