### ISSUE TITLE
Error with Gradient

### ISSUE THREAD

**Issue by jhemak** [kalkih/mini-media-player#815]
Hello!  There seems to be a small formatting issue with using the full-cover option for Artwork.  The gradient seems to be lacking the corner radius at the bottom, causing points to show in the corners.

Details and examples are posted here: https://github.com/kalkih/mini-media-player/pull/793#issuecomment-1841790400

Thanks in advance to anyone who might be able to fix this!

**Comment by jhemak** [comment]
Thank you!  Do you need help testing?

**Comment by Drafteed** [comment]
@jhemak Thanks 👍 Fixed in the latest release.
