### ISSUE TITLE
Replace paper-button or something

### ISSUE THREAD

**Issue by kalkih** [kalkih/mini-media-player#82]
The paper-button element is getting removed in HA 0.88.0, and replaced by mwc-button.
Need to make the card compatible with upcoming HA 0.88.0 while maintaining support for previous versions.

**Comment by balloob** [comment]
```ts
if (!customElements.get('mwc-button')) {
  customElements.define(
    'mwc-button',
    class extends customElements.get('paper-button'){}
  )
}
```

🙈

**Comment by kalkih** [comment]
Many thanks @balloob , great solution!
Only issue I have with the mwc-button is the min-width, which I can't get rid of, also can't seem to set the paddings.

**Comment by balloob** [comment]
You can always create a `<kalkih-button>` that extends mwc-button and patches what you want, or  implement your own button completely that does exactly what you want.
