### ISSUE TITLE
Progress doesn't show up in v. 1.0.1

### ISSUE THREAD

**Issue by quantummobile** [kalkih/mini-media-player#84]
Can't get progress to work. Using v 1.0.1.
Any ideas?
![screenshot 2019-02-17 at 16 20 55](https://user-images.githubusercontent.com/47085307/52914365-0c274f80-32d0-11e9-944e-f5fe7fc7ffec.png)

**Comment by kalkih** [comment]
Yes,
Looks like it's the Spotify component you are using as the entity in the cards.
The Spotify component doesn't expose the necessary attributes to calculate the progress.
`media_duration`, `media_position` and `media_position_updated_at`.

Nothing I can do about it, sorry.

**Comment by quantummobile** [comment]
Well, but your very example shows the progress when Spotify component is used as an entity, doesn't it? Please see the screenshot attached.
![screenshot 2019-02-17 at 16 36 20](https://user-images.githubusercontent.com/47085307/52914556-89ec5a80-32d2-11e9-85ee-a3c0a9bfc45c.png)

**Comment by kalkih** [comment]
That's just a mockup. You can name your entities anything, doesn't necessarily mean it's using the Spotify component because it's name is Spotify.
But I see your point, could be confusing, will rename it next version 👍
