### ISSUE TITLE
can't hide power button 

### ISSUE THREAD

**Issue by IoSonoAndreaZ** [kalkih/mini-media-player#841]
Hi, just discovered this nice project.
I'm trying to create a player without the power button.

My code so far:

```
card:
  type: custom:mini-media-player
  entity: media_player.plex_plexamp_krogpc_skylake
  group: true
  volume_stateless: false
  artwork: cover
  source: full
  sound_mode: icon
  info: scroll
  replace_mute: stop
  tap_action: false
  volume: false
  power: false
```

however i can't seem to hide power e volume bar, what i'm doing wrong?

**Comment by allannk** [comment]
Check out the hide section of the documentation, I think you should put the volume/power under the `hide:`-section

```
card: 
  type: custom:mini-media-player
  < your other configurations >
  hide:
    volume: true
    power: true
