### ISSUE TITLE
Feature request: Able to set an image rather then an icon/text

### ISSUE THREAD

**Issue by peternijssen** [kalkih/mini-media-player#89]
First of all, thanks for this great card!

I would like to be able to set images rather then buttons with an icon and text. Reason for that is that I would like my daughter to also be able to pick something she wants to watch. Since she can't read yet, it's easier for her to pick something based on an image.

I have a work-around currently, but that requires me to work with scripts, the media_extractor etc. Would be nice if it was somehow possible in this card.

Below my workaround, to get a bit of an idea what I mean. Would be nice to also be able to add a name that overlays like the default picture-entity does. That however sounds like an extra :)

![work-around](https://i.ibb.co/YdGWV6P/Schermafbeelding-2019-02-23-om-14-29-19.png)

**Comment by kalkih** [comment]
This will not be implemented, there are already other cards that should do the job just fine and I honestly think your workaround looks great.

By utilizing the [picture-entity](https://www.home-assistant.io/lovelace/picture-entity/) card, you should be able to get the text overlay as well.
