### ISSUE TITLE
SUggestion - Alternative Icon for Sonos Group

### ISSUE THREAD

**Issue by rgogada** [kalkih/mini-media-player#92]
Just a suggestion. Please see if the below (mdi:speaker-multiple) icon for Sonos group makes any sense.

![image](https://user-images.githubusercontent.com/4284896/53691369-7100a080-3dcc-11e9-8eb0-a394b1a8b32f.png)

**Comment by kalkih** [comment]
Makes sense, not sure how good it looks though:

![hyperion_8123_lovelace_4 44](https://user-images.githubusercontent.com/457678/53696233-5676f900-3dc5-11e9-96f9-d6e7c9753012.png)

**Comment by kalkih** [comment]
Could look good if scaled down a bit I think, I'll play around with it.

**Comment by kalkih** [comment]
The button has now been changed in the latest release.
