### ISSUE TITLE
Minor flaws when using scrolling media info

### ISSUE THREAD

**Issue by cicero22** [kalkih/mini-media-player#93]
When I hide icon and name of a media_player and set `info: scroll`, the scolling info text should be aligned with the control buttons:

![scroll](https://user-images.githubusercontent.com/6802528/53807590-3d4e8380-3f50-11e9-913f-e35289b02d92.png)

If the media info is an app_name, it is not displayed at all.

**Comment by kalkih** [comment]
Should be fixed in the latest release [v1.0.3](https://github.com/kalkih/mini-media-player/releases/tag/v1.0.3)

**Comment by cicero200272** [comment]
Fixed indeed. Thanks!
