### ISSUE TITLE
[Feature request] Kodi remote support

### ISSUE THREAD

**Issue by cyclops1982** [kalkih/mini-media-player#97]
Hi,

I'm really enjoying this mini-media-player. Great stuff!

I've used the buttons to switch sources on my denon. works like a charm and the icons from MDI is great too.

I use the phone for this stuff and i'd turn it on and then have to switch to the Kodi app to control that (as a remote). It would be great if this card could have remote-control options too.
There's (https://community.home-assistant.io/t/kodi-remote/97652) available, but i believe it would be much nicer if it was built-in to this card already.

**Comment by iantrich** [comment]
I would suggest using the popup-card to display whatever other card you want rather than trying to bring full remote support into this card. It would work for the example you linked already. https://github.com/thomasloven/lovelace-popup-card

**Comment by kalkih** [comment]
Yes, this is a bit out scope for this project, Please consider @iantrich's suggestion.
